### ISSUE TITLE
Check out and run geodata service in Travis

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#103]
Set up checkout and running geodata in `.travis.yml`.

Then enable test at https://github.com/hbz/lobid-organisations/blob/master/src/test/java/flow/TestGeoEnrich.java#L76 (as separate `@Test`).

**Comment by fsteeg** [comment]
Depends on https://github.com/hbz/geodata/issues/23.

**Comment by acka47** [comment]
Can we close this one, @fsteeg?
