### ISSUE TITLE
Fix telephone data type

### ISSUE THREAD

**Issue by nichtich** [hbz/lobid-organisations#105]
In `context.jsonld`, the `telephone` field is defined as URI or blank node identifier:

 		"telephone": {
			"@type": "@id",
			"@id": "http://schema.org/telephone"
		},

The current data, however, contains strings, such as `0049 5121 8 83-93010` which are no URIs. Either change `context.jsonld` or normalize phone numbers to [RDF 3966](https://tools.ietf.org/html/rfc3966), e.g. `tel:+49-5121-8-83-93010`. A regex for a reasonable subset of RDF3966 is `^tel:\+([0-9][.()-]?)+[0-9]+$`.

**Comment by nichtich** [comment]
See http://beta.lobid.org/organisations/DE-700 for another example:

   "telephone": "0049 541 9 69-4320 und -4323"

**Comment by acka47** [comment]
Thanks for the pointer, @nichtich . We will adjust the `telephone` entry in the JSON-LD context.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/organisations/context.jsonld

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://beta.lobid.org/organisations/context.jsonld
