### ISSUE TITLE
Multilingual names

### ISSUE THREAD

**Issue by nichtich** [hbz/lobid-organisations#106]
How to add multilingual names to libraries e.g. German name and English name?

**Comment by acka47** [comment]
There are no write functionalities planned so far in lobid-organisations. We currently only do transformation from ISIL registry and DBS and offer readable Linked Data. Thus, I suggest adding "Englische Anzeigeform des Namens" at the respective entry at http://sigel.staatsbibliothek-berlin.de/startseite/ .

I will make an issue to add these English names to the RDF.

**Comment by acka47** [comment]
> I will make an issue to add these English names to the RDF.

Actually, we already have the names in the RDF as `alternateName`, see e.g. http://beta.lobid.org/organisations/DE-B2042. Thus, we should move this to `name` and add language tags – at least to literals of the `name` property.

**Comment by acka47** [comment]
Currently, there are obviously not very much English names recorded in the ISIL registry, e.g. you get 108 results [searching for "library"](http://sigel.staatsbibliothek-berlin.de/suche.html?tx_sbbyaz_pi1[q]=library). For planning implementation and out of curiosity: What is your use case? Does the English name in `alternateName` suffice for now? Do you need a language tag?

**Comment by acka47** [comment]
I made another issue regarding the support of multilingual data in lobid-organisations: #107

**Comment by acka47** [comment]
For now, we will implement English name versions as shown in https://github.com/hbz/lobid-organisations/issues/107#issuecomment-187064777.

**Comment by fsteeg** [comment]
I've started working on an implementation along the lines of https://github.com/hbz/lobid-organisations/issues/107#issuecomment-187064777 (see https://github.com/hbz/lobid-organisations/commit/336bb68f845a8555cf76a01cb1551dee60594425 & https://github.com/hbz/lobid-organisations/commit/e34fd2572326227cfb8db64cb36467dd3df51cfd).

Looking into the source data, I saw that `029@.a` with `029@.4 code d` is a long, english name, while code a-c are different, short german names. While working on the localized UI, the approach from https://github.com/hbz/lobid-organisations/issues/107#issuecomment-187064777 seems odd: the long english name is not the localized version of the short german form. It's actually the localized form of the normal name.

I checked the JSON-LD spec [on internationalization](http://www.w3.org/TR/json-ld/#string-internationalization) again and would suggest the following approach:

```json
{
  "@context": {
    "name": "http://schema.org/name",
    "name_en": { "@id": "http://schema.org/name", "@language": "en" }
  },
  "name": "Leibniz-Institut für Zoo- und Wildtierforschung. Bibliothek",
  "name_en": "Leibniz Institute for Zoo and Wildlife Research Berlin, Library",
  "alternateName": ["Berlin IZW WGL", "Berlin Inst.Zoo-u.Wildtier WGL"]
}
```

I've discussed this approach with @dr0i and he agrees. Will continue like this unless @acka47 vetoes.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/organisations/DE-B2042

**Comment by SBRitter** [comment]
+1

**Comment by nichtich** [comment]
Well, this does not solve multilinguality in general but only the primary name. Alternate names still have no language indicator but the major request has been solved, thanks!

**Comment by acka47** [comment]
I think this is a pragmatic solution as we currently only convert German ISIL and DBS data. It doesn't look like we will work towards an international database anytime soon. If we will incorporate more non-German data in some years we can update the data model then.
