### ISSUE TITLE
Support multilingual data? 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#107]
From https://github.com/hbz/lobid-organisations/issues/106#issuecomment-171919226. Currently you can't automatically get the English name from the RDF. Example http://beta.lobid.org/organisations/DE-B2042 (snippet):

```javascript
{
   "name": "Leibniz-Institut für Zoo- und Wildtierforschung. Bibliothek",
   "id": "http://beta.lobid.org/organisations/DE-B2042#!",
   "alternateName": [
      "Berlin IZW WGL",
      "Berlin Inst.Zoo-u.Wildtier WGL",
      "Leibniz Institute for Zoo and Wildlife Research Berlin, Library"
   ]
}
```

The English name comes from 029, subfield a with code d (see [documentation](http://sigel.staatsbibliothek-berlin.de/vergabe/adressenformat/410/)), e.g.:

```xml
<ppxml:tag id="029@" occ="">
   <ppxml:subf id="a">
     Leibniz Institute for Zoo and Wildlife Research Berlin, Library
   </ppxml:subf>
   <ppxml:subf id="4">d</ppxml:subf>
</ppxml:tag>
```

It would make sense to add the feature built into RDF "language tags" to differ between german and English names.  At this point of development, it is not so easy to just add language tags to the JSON. We would have to re-make the whole data structure (similar to what we are doing at https://github.com/hbz/oerworldmap) with multilinguality in mind. Until now, we've been creating a mono-lingual application as we only use data sources in German. 

Another argument for language tags apart from the English names from ISIL registry is the perspective of adding LoC organization data, see #5.

**Comment by acka47** [comment]
I will rename this as this addresses a fundamental question triggered by the concrete issue of English names.

**Comment by acka47** [comment]
So that we know what we are talking about, here is an example of how an entry would look like supporting multilinguality:

```javascript
{
   "dbsID":"ED069",
   "isil":"DE-B2042",
   "isPrimaryTopicOf":"http://dispatch.opac.d-nb.de/DB=1.2/CMD?ACT=SRCHA&IKT=8529&TRM=DE-B2042",
   "@context":"http://beta.lobid.org/organisations/context.jsonld",
   "@type":"http://schema.org/Library",
   "rs":"011000000000",
   "name":{
      "@value":"Leibniz-Institut für Zoo- und Wildtierforschung. Bibliothek",
      "@language":"de"
   },
   "url":"http://www.izw-berlin.de/",
   "@id":"http://beta.lobid.org/organisations/DE-B2042#!",
   "telephone":"0049 30 51 68-106",
   "email":"mailto:biblio@izw-berlin.de",
   "address":{
      "postOfficeBoxNumber":"70 04 30",
      "addressLocality":{
         "@value":"Berlin",
         "@language":"de"
      },
      "@type":"http://schema.org/PostalAddress",
      "addressCountry":"DE",
      "postalCode":"10324"
   },
   "location":[
      {
         "type":"http://schema.org/Place",
         "address":{
            "postalCode":"10315",
            "streetAddress":"Alfred-Kowalke-Str. 17",
            "addressLocality":{
               "@value":"Berlin",
               "@language":"de"
            },
            "addressCountry":"DE",
            "@type":"http://schema.org/PostalAddress"
         },
         "openingHoursSpecification":{
            "@type":"http://schema.org/OpeningHoursSpecification",
            "comment":{
               "@value":"um telefonische Anmeldung wird gebeten",
               "@language":"de"
            },
            "description":{
               "@value":"Mo-Fr 9.00-15.00",
               "@language":"de"
            },

         },
         "geo":{
            "lat":"42.9797695",
            "lon":"-88.1016844"
         }
      }
   ],
   "classification":{
      "@id":"http://purl.org/lobid/libtype#n81"
   },
   "fundertype":{
      "@id":"http://purl.org/lobid/fundertype#n06",
      "label":{
         "@language":"de",
         "@value":"Sonstige öffentliche Trägerschaft"
      }
   },
   "stocksize":{
      "@id":"http://purl.org/lobid/stocksize#n06",
      "label":{
         "@language":"de",
         "@value":"10.001 - 30.000"
      }
   },
   "alternateName":[
      {
         "@value":"Berlin Inst.Zoo-u.Wildtier WGL",
         "@language":"de"
      },
      {
         "@value":"Berlin IZW WGL",
         "@language":"de"
      },
      {
         "@value":"Berlin Inst.Zoo-u.Wildtier WGL",
         "@language":"de"
      },
      {
         "@value":"Leibniz Institute for Zoo and Wildlife Research Berlin, Library",
         "@language":"en"
      }
   ],
   "sameAs":[
      "http://ld.zdb-services.de/resource/organisations/DE-B2042",
      "http://ld.zdb-services.de/resource/organisations/DE-B2042"
   ],
   "containedIn":"http://www.geonames.org/6547539",
   "ags":"11000000",
   "subject":[
      {
         "@value":"Ernährungsphysiologie",
         "@language":"de"
      },
      {
         "@value":"Ethologie",
         "@language":"de"
      }
      ...
   ]
}
```

**Comment by acka47** [comment]
@fsteeg What do you think. How much effort is it to implement this provided with a list of fields that should support multilinguality?

**Comment by fsteeg** [comment]
If I understand correctly, the `alternateName` is the only field for which we actually have english values.

We should then keep the changes limited to that, and attempt a JSON-like approach like this:

```
"alternateName": {
  "de" : ["Berlin Inst.Zoo-u.Wildtier WGL", "Berlin Inst.Zoo-u.Wildtier WGL"],
  "en" : ["Leibniz Institute for Zoo and Wildlife Research Berlin, Library"]
}
```

This is what I described in my post some time ago [1], where Manu Sporny pointed me to the JSON-LD way to do this: http://www.w3.org/TR/json-ld/#string-internationalization (at the bottom of that section).

[1] https://fsteeg.wordpress.com/2014/01/28/one-issue-with-json-ld-that-seems-not-so-pragmatic/

**Comment by acka47** [comment]
> If I understand correctly, the `alternateName` is the only field for which we actually have english values.

This is right – for now. But we have been thinking for adding the organization data from LoC for some time (and in fact DID provide this data when we started with lobid-organisations). In the initial comment I pointed to the respective issue #5.

There might be reasons that speak against doing this but nonetheless I think to make the API more future-proof whe should add string internationalization to all fields that may have values in multiple languages.

**Comment by acka47** [comment]
BTW, in the OER worldmap we do multilinguality like I did above see e.g. curl -H "Accept: application/json" https://oerworldmap.org/resource/urn:uuid:63905512-0eb3-47cb-ab8e-b6bd83fea18e

**Comment by acka47** [comment]
We decided to not implement multilingual support for all text fields but will only focus on the English names for now – as they are the only English strings in the data. Closing this ticket and discussing details for implementation in #106 .
