### ISSUE TITLE
Wrong stocksizes

### ISSUE THREAD

**Issue by hauschke** [hbz/lobid-organisations#110]
Stocksizes are defined in https://raw.githubusercontent.com/lobid/vocabs/master/stocksize.ttl.

Example:
```
stocksize:n08
  a skos:Concept ;
  skos:inScheme stocksize:scheme ;
  skos:notation "08"^^xsd:integer ;
  skos:prefLabel "100.001 - 300.000"@de;
  skos:prefLabel "100,001 - 300,000"@en .
```   
There are libraries with stocksize:n08, but different values for stocksize. Examples:

http://beta.lobid.org/organisations/DE-H360
no value

http://beta.lobid.org/organisations/DE-Mz2
"value" : "bis 1.000"

http://beta.lobid.org/organisations/DE-123
"value" : "300.001 - 1.000.000"

http://beta.lobid.org/organisations/DE-D5
 "value" : "30.001 - 100.000"

http://beta.lobid.org/organisations/DE-D568
 "value" : "3.001 - 5.000"

This issue concerns all stocksizes, as fas as I can see.

**Comment by acka47** [comment]
Thanks for the pointer. There seems to be a problem with fundertype classification as well. E.g. look at http://beta.lobid.org/organisations/search?q=fundertype.value%3Aev. and you will find that all entries only have the label `Ev. Kirche` but don't have the associated concept URI and also the concept URI for stocksize is completely missing.

**Comment by fsteeg** [comment]
This is probably caused by the fact that the IDs and the values come from different sources.

The IDs are taken from the Sigel registry, the values from DBS. See:

https://github.com/hbz/lobid-organisations/blob/master/src/main/resources/morph-enriched.xml#L273

**Comment by fsteeg** [comment]
The same issue as for `stocksize` and `fundertype` exists for `classification`.

Deployed fix for all three to staging, see:

http://test.lobid.org/organisations/DE-568
http://test.lobid.org/organisations/DE-D5
http://test.lobid.org/organisations/DE-123
http://test.lobid.org/organisations/DE-Mz2
http://test.lobid.org/organisations/DE-H360
http://test.lobid.org/organisations/search?q=fundertype.value:ev

If both the ID from the Sigel registry and a label from the DBS exists, the Sigel data takes precedence.

@acka47: you mentioned you'd like a way to see cases where `stocksize` in Sigel and DBS data don't correspond. I don't see a straightforward way to do that. If it's important, perhaps we should track that in a different issue (such conflicts might occur for other fields, too).

**Comment by acka47** [comment]
+1 Having a look at some library home pages I get the feeling that the stocksize classification is often applied incorrectly. But that is nothing we can deal with in an automatic way...
