### ISSUE TITLE
Remove fields "email" and "telephone" from DBS-derived data

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#111]

**Comment by fsteeg** [comment]
Deployed to staging:

http://beta.lobid.org/organisations/DBS-NK894 vs.
http://test.lobid.org/organisations/DBS-NK894

http://beta.lobid.org/organisations/DBS-XY882 vs.
http://test.lobid.org/organisations/DBS-XY882

Note that this removes the fields only for DBS-only data. If we also have a Sigel entry for the DBS entry, it will contain the email and the telephone number from the Sigel data.

**Comment by acka47** [comment]
> Note that this removes the fields only for DBS-only data. If we also have a Sigel entry for the DBS entry, it will contain the email and the telephone number from the Sigel data.

Sounds reasonable to me. Nobody complained for the last 5 years or so that we publish their email/telephone information.
+1
