### ISSUE TITLE
Wrong identifier with slash generated

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#114]
See http://beta.lobid.org/organisations/search?q=dbsID:AE088 where `"id": "http://beta.lobid.org/organisations/DE-14/00#!"` which isn't dereferencable. 

It should read `"id": "http://beta.lobid.org/organisations/DE-14-00#!"`

(BTW, why SLUB has two ISIL registry entries isn't clear to me...)

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/organisations/search?q=name:slub+OR+alternateName:slub
http://test.lobid.org/organisations/search?q=dbsID:AE088
http://test.lobid.org/organisations/DE-14-00
http://test.lobid.org/organisations/DE-14

**Comment by acka47** [comment]
+1
