### ISSUE TITLE
Entries of archives without type and with wrong classification

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#116]
Got to take a deeper look at this at some point: http://beta.lobid.org/organisations/DE-H368#!

**Comment by acka47** [comment]
Another one: http://beta.lobid.org/organisations/DE-2212#!

Both have `"classification" : { "id" : "http://purl.org/lobid/libtype#n59" }` which is not part of libtype vocab.

**Comment by acka47** [comment]
http://beta.lobid.org/organisations/DE-2143#! is one without "type" and http://purl.org/lobid/libtype#n52.

**Comment by acka47** [comment]
Seems to be a problem with archives, there's lots of them in http://beta.lobid.org/organisations/search?size=400&q=name:archiv.

According to [libtype vocab](http://purl.org/lobid/libtype) archives should have classification http://purl.org/lobid/libtype#n85. http://beta.lobid.org/organisations/search?q=classification.id:n85 gives zero results, though...

**Comment by acka47** [comment]
I find the following classications in the "archiv" list (two of them only once): 

- http://purl.org/lobid/libtype#n51
- http://purl.org/lobid/libtype#n52
- http://purl.org/lobid/libtype#n53
- http://purl.org/lobid/libtype#n54
- http://purl.org/lobid/libtype#n55
- http://purl.org/lobid/libtype#n56
- http://purl.org/lobid/libtype#n57
- http://purl.org/lobid/libtype#n58
- http://purl.org/lobid/libtype#n59

We should probably map all of them to http://purl.org/lobid/libtype#n85.

**Comment by acka47** [comment]
The values are correctly taken from the ISIL registry. Obviously, they have removed the notation "85" for archive (which still is in the libtype vocab) and added different types of archives to the 5* notations. See the documentation: http://sigel.staatsbibliothek-berlin.de/vergabe/adressenformat/805/#c72416

Perhaps @cKlee can say something about this. How could we have realized this change earlier to be able to adapt our data accordingly?

We will have to:

1.Adjust http://purl.org/lobid/libtype.
2. Make sure that we notice classification changes changes up-front in the future.

**Comment by acka47** [comment]
@fsteeg I am curious how the libtype vocab is incorporated in lobid-organisations data. Will the changes to the vocab from https://github.com/lobid/vocabs/issues/44 be reflected in the data automatically?

**Comment by fsteeg** [comment]
No, I'm afraid not.

As far as I know the vocabulary is only used in the morph: https://github.com/hbz/lobid-organisations/blob/master/src/main/resources/morph-enriched.xml

There, `libtype` is used in three ways:

1. A mapping of libtype numbers to URIs (to choose a `type` for the organisations), stored at http://lobid.org/download/lookup-tables/data/libtype-map.csv
2. A mapping of libtype numbers to labels (to map Sigel IDs to labels): https://github.com/hbz/lobid-organisations/blob/master/src/main/resources/morph-enriched.xml#L425
3. A mapping of labels to libtype URIs (to map DBS data to URIs): https://github.com/hbz/lobid-organisations/blob/master/src/main/resources/morph-enriched.xml#L477

If I understand this correctly, the `libtype.ttl` file currently only provides a place the URIs point to.

Is `libtype.ttl` used for something else outside of lobid-organisations?

**Comment by acka47** [comment]
I understand. Then I will have to adjust 1. and 2. after the vocab is updated. As a change to the vocabulary shouldn't happen too often, I think we won't have to change this setup. It is only important to know about those changes early enough.

**Comment by cKlee** [comment]
> Perhaps @cKlee can say something about this. How could we have realized this change earlier to be able to adapt our data accordingly?

I wasn't aware of the changes either. Will ask my colleague when he's back from Bibliothekskongress.

**Comment by acka47** [comment]
@cKlee Funny. Please think about a way to communicate those changes in the future. You are welcome to maintain the SKOS vocabulary together with us.

**Comment by fsteeg** [comment]
Deployed to production:

http://beta.lobid.org/organisations/DE-H368
http://beta.lobid.org/organisations/DE-2212

**Comment by acka47** [comment]
+1. Closing.
