### ISSUE TITLE
Adopt side-car approach in lobid-organisations

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#117]
Currently, labels for a classification are delivered in lobid-organisations as follows:

```json
{
   "id":"http://beta.lobid.org/organisations/DE-6#!",
   "classification":{
      "id":"http://purl.org/lobid/libtype#n60",
      "value":"Zentrale Universitätsbibliothek"
   },
   "fundertype":{
      "id":"http://purl.org/lobid/fundertype#n02",
      "value":"Land"
   },
   "stocksize":{
      "id":"http://purl.org/lobid/stocksize#n10",
      "value":"1.000.001 und mehr"
   }
}
```

We actually use the side-car approach here but differently as in lobid-resources. To align both, we should also use "label" mapped to rdfs:label in the context. (BTW, "value" isn't part of the context anyway.)

To do:
- [ ] Use "label" instead of value in the JSON
- [ ] Add  `"label":"http://www.w3.org/2000/01/rdf-schema#label"` to the context

**Comment by fsteeg** [comment]
What's currently used in data 2.0 is `preferredName`: http://lobid.org/resources/HT014180974

I remember we discussed the field name in a more or less recent meeting, but I'm not sure what we decided. I like the simple `label` but seem to remember we favored something like `prefLabel` (@jschnasse also thinks so). In any case, it would not be consistent with the current field in data 2.0.

**Comment by acka47** [comment]
In https://github.com/hbz/lobid-rdf-to-json/issues/30 I wrote down an example with "label" mapped to rdfs:label and I am quite sure that we all agreed on this.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/organisations/DE-6

(Context not changed yet)

**Comment by acka47** [comment]
+1
