### ISSUE TITLE
Use simple strings for types, mapped to URI in context

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#123]
As we will do this in lobid-resources (see https://github.com/hbz/lobid-rdf-to-json/issues/26), we should also do this with organisations. I guess, we will just have to update both http://lobid.org/download/lookup-tables/data/libtype-map.csv and the [context](https://github.com/hbz/lobid-organisations/blob/master/web/conf/context.jsonld) and will be done. Right, @fsteeg?

**Comment by fsteeg** [comment]
Sounds right.

**Comment by fsteeg** [comment]
Deployed to production, see:

http://beta.lobid.org/organisations/DE-6
http://beta.lobid.org/organisations/context.jsonld

**Comment by acka47** [comment]
+1. Closing.
