### ISSUE TITLE
Add provenance information

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#128]
We should have information about the source dataset(s) of a record that enables people to filter results list so that only orgs in ISIL/DBS are listed.

**Comment by acka47** [comment]
Regarding the concrete use case I just realized that one can already filter by source through the `isil` and `dbsID` fields.

- results included in ISIL registry: http://beta.lobid.org/organisations/search?q=isil:*
- results included in DBS : http://beta.lobid.org/organisations/search?q=dbsID:*

What's missing is the possibilit to use the scroll parameter for API queries. Will open another issue for this. Regarding this issue, I rename it to cover provenance information in general which we should add.

**Comment by acka47** [comment]
We should add provenance information like we do in lobid-resources, e.g.:

```json
"id": "http://lobid.org/resources/HT017203152#!",
"describedby":[
   {
      "dateCreated":"20120417",
      "dateModified":"20120426",
      "id":"http://lobid.org/resources/HT017203152"
   }
]
```

As schema.org property we should use http://schema.org/mainEntityOfPage. The creation and modification dates of the source record are in fields 001A resp. 001B. Here is a first draft of how it could look like. 

```json
{
   "@context":{
      "id":"@id",
      "mainEntityOfPage":{
         "@id":"http://schema.org/mainEntityOfPage",
         "@type":"@id"
      },
      "dateCreated":"http://purl.org/dc/terms/created",
      "dateModified":"http://purl.org/dc/terms/modified",
      "wasDerivedFrom":"http://www.w3.org/ns/prov#wasDerivedFrom"
   },
   "id":"http://beta.lobid.org/organisations/DE-6#!",
   "mainEntityOfPage":[
      {
         "id":"http://beta.lobid.org/organisations/DE-6",
         "dateModified":"2016-01-06",
         "wasDerivedFrom":"http://services.dnb.de/sru/bib?operation=searchRetrieve&query=isl%3DDE-6&recordSchema=PicaPlus-xml&version=1.1",
         "isPartOf": [ "http://lobid.org/organisations/DBS", "http://lobid.org/organisations/ISIL" ]
      }
   ]
}
```

In this example draft, we would have to create descriptions of the DBS dataset and ISIL registry at  http://lobid.org/organisations/DBS and http://lobid.org/organisations/ISIL. I will take some time looking into [PROV ontology](https://www.w3.org/TR/prov-o/) to find a pragmatic approach.

**Comment by acka47** [comment]
After taking a look at the PROV ontology, I suggest something like this, the following approach of describing the merging activity, pointing to the base records (we'll need to create an entry for DBS data for each record) and the morph files:

```json
{
   "@context":{
      "id":"@id",
      "mainEntityOfPage":{
         "@id":"http://schema.org/mainEntityOfPage",
         "@type":"@id"
      },
      "dateCreated":"http://schema.org/dateCreated",
      "dateModified":"http://schema.org/dateModified",
      "wasGeneratedBy":{
         "@id":"http://www.w3.org/ns/prov#wasGeneratedBy",
         "@type":"@id"
      },
      "Activity":"http://www.w3.org/ns/prov#Activity",
      "startedAtTime":{
         "@id":"http://www.w3.org/ns/prov#startedAtTime",
         "@container":"xsd:dateTime"
      },
      "endedAtTime":{
         "@id":"http://www.w3.org/ns/prov#startedAtTime",
         "@container":"xsd:dateTime"
      },
      "used":{
         "@id":"http://www.w3.org/ns/prov#used",
         "@type":"@id"
      }
   },
   "id":"http://lobid.org/organisations/DE-6#!",
   "mainEntityOfPage":{
      "id":"http://lobid.org/organisations/DE-6",
      "wasGeneratedBy":{
         "type":"Activity",
         "startedAtTime":"2016-09-01T04:30:00Z",
         "endedAtTime":"2016-09-01T05:00:00Z",
         "used":[
            {
               "id":"http://services.dnb.de/sru/bib?operation=searchRetrieve&query=isl%3DDE-6&recordSchema=PicaPlus-xml&version=1.1",
               "dateModified":"2016-11-16",
               "dateCreated":"1999-11-18"
            },
            {
               "id":"http://lobid.org/dbs/AC006"
            },
            "https://github.com/hbz/lobid-organisations/blob/master/conf/morph-sigel.xml",
            "https://github.com/hbz/lobid-organisations/blob/master/conf/morph-dbs.xml",
            "https://github.com/hbz/lobid-organisations/blob/master/conf/morph-enriched.xml"
         ]
      }
   }
}
```

**Comment by fsteeg** [comment]
Simple version as discussed offline deployed to stage: http://stage.lobid.org/organisations/DE-38.json

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See http://lobid.org/organisations/DE-38.json

(But is this really all we need for this issue to be complete?)

**Comment by acka47** [comment]
Reopening as we need to link to the source data. I suggest to use the approach from https://github.com/hbz/lobid-organisations/issues/128#issuecomment-326559579 wich gets a bit simpler by now as, we stopped merging information from the two sources (sigel registry and dbs) in one entry.

**Comment by acka47** [comment]
Here is an updated version of the proposal:

```json
{
  "@context":{
    "id":"@id",
    "mainEntityOfPage":{
      "@id":"http://schema.org/mainEntityOfPage",
      "@type":"@id"
    },
    "dateCreated":"http://schema.org/dateCreated",
    "dateModified":"http://schema.org/dateModified",
    "wasGeneratedBy":{
      "@id":"http://www.w3.org/ns/prov#wasGeneratedBy",
      "@type":"@id"
    },
    "Activity":"http://www.w3.org/ns/prov#Activity",
    "startedAtTime":{
      "@id":"http://www.w3.org/ns/prov#startedAtTime",
      "@container":"xsd:dateTime"
    },
    "endedAtTime":{
      "@id":"http://www.w3.org/ns/prov#startedAtTime",
      "@container":"xsd:dateTime"
    },
    "used":{
      "@id":"http://www.w3.org/ns/prov#used",
      "@type":"@id"
    }
  },
  "id":"http://lobid.org/organisations/DE-6#!",
  "mainEntityOfPage":{
    "id":"http://lobid.org/organisations/DE-6",
    "dateModified":"2016-11-16",
    "dateCreated":"1999-11-18",
    "wasGeneratedBy":{
      "type":"Activity",
      "startedAtTime":"2016-09-01T04:30:00Z",
      "endedAtTime":"2016-09-01T05:00:00Z",
      "used":[
        {
          "id":"http://services.dnb.de/sru/bib?operation=searchRetrieve&query=isl%3DDE-6&recordSchema=PicaPlus-xml&version=1.1"
        },
        "https://github.com/metafacture/metafacture-core",
        "https://github.com/hbz/lobid-organisations/blob/master/conf/morph-sigel.xml",
        "https://github.com/hbz/lobid-organisations/blob/master/conf/morph-enriched.xml"
      ]
    }
  }
}
```

If we did it all correctly, we'd have to add `dateCreatedand `dateModified` to the PicaPlus-xml resource but that would mean an API break (see also https://github.com/hbz/lobid-resources/issues/809#issue-316248933)).

**Comment by TobiasNx** [comment]
@acka47 any reason why we do not use `describedBy` as in lobid-resources here?

**Comment by acka47** [comment]
> any reason why we do not use describedBy as in lobid-resources here?

We chose another approach for lobid-organisations: to use schema.org where applicable and add properties in lobid-vocabs if schema.org does not contain what we want.

**Comment by TobiasNx** [comment]
@acka47:
for dbs:
```
	"mainEntityOfPage": {
		"id": "http://lobid.org/organisations/DE-9#!",
		"wasGeneratedBy": {
			"type": "Activity",
			"used": [
				{
					"sourceOrganisation": {
						"id": "https://www.bibliotheksstatistik.de/",
						"label": "Deutsche Bibliotheksstatistik (DBS)"
					}
				},
				"https://github.com/metafacture/metafacture-core",
				"https://github.com/hbz/lobid-organisations/blob/master/conf/fix-dbs.fix",
				"https://github.com/hbz/lobid-organisations/blob/master/conf/fix-enriched.fix"
			]
		}
	},
```

for sigil:
```
	"mainEntityOfPage": {
		"id": "http://lobid.org/organisations/DE-294#!",
		"dateCreated": "18-11-99",
		"dateModified": "24-04-12",
		"wasGeneratedBy": {
			"type": "Activity",
			"used": [
				{
					"id": "http://services.dnb.de/sru/bib?operation=searchRetrieve&query=isl%3DDE-294&recordSchema=PicaPlus-xml&version=1.1",
					"sourceOrganisation": {
						"id": "https://sigel.staatsbibliothek-berlin.de/vergabe/isil/",
						"label": "Deutsche ISIL-Agentur und Sigelstelle an der Staatsbibliothek zu Berlin"
					}
				},
				"https://github.com/metafacture/metafacture-core",
				"https://github.com/hbz/lobid-organisations/blob/master/conf/fix-sigel.fix",
				"https://github.com/hbz/lobid-organisations/blob/master/conf/fix-enriched.fix"
			]
		}
	}
``

**Comment by TobiasNx** [comment]
http://test.lobid.org/organisations/search?q=mainEntityOfPage.wasGeneratedBy.used.sourceOrganisation.id%3A%22https%3A%2F%2Fwww.bibliotheksstatistik.de%2F%22&location=

http://test.lobid.org/organisations/search?q=mainEntityOfPage.wasGeneratedBy.used.sourceOrganisation.id%3A%22https%3A%2F%2Fsigel.staatsbibliothek-berlin.de%2Fvergabe%2Fisil%2F%22&location=

Perhaps we introduce a facette for this.

**Comment by TobiasNx** [comment]
> http://test.lobid.org/organisations/search?q=mainEntityOfPage.wasGeneratedBy.used.sourceOrganisation.id%3A%22https%3A%2F%2Fwww.bibliotheksstatistik.de%2F%22&location=
> 
> http://test.lobid.org/organisations/search?q=mainEntityOfPage.wasGeneratedBy.used.sourceOrganisation.id%3A%22https%3A%2F%2Fsigel.staatsbibliothek-berlin.de%2Fvergabe%2Fisil%2F%22&location=
> 
> Perhaps we introduce a facette for this.

Changed property name:

http://test.lobid.org/organisations/search?q=mainEntityOfPage.wasGeneratedBy.used.sourceOrganization.id%3A%22https%3A%2F%2Fwww.bibliotheksstatistik.de%2F%22&location=

http://test.lobid.org/organisations/search?q=mainEntityOfPage.wasGeneratedBy.used.sourceOrganization.id%3A%22https%3A%2F%2Fsigel.staatsbibliothek-berlin.de%2Fvergabe%2Fisil%2F%22&location=

**Comment by TobiasNx** [comment]
Add Info about provenance to GUI #497 

ElasticSearch is not able to provide mixed arrays of strings and of objects in `used` therefore we only use the link to the sourcedata now.
