### ISSUE TITLE
Provide a way to get full data dumps for arbitrary queries

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#129]
See https://github.com/hbz/lobid-organisations/issues/128#issuecomment-208819469 and the corresponding ticket where this was implemented by @dr0i for the lobid-resource endpoint: https://github.com/hbz/lobid/issues/176

**Comment by fsteeg** [comment]
Since we're switching to Elasticsearch 2.3 (see https://github.com/hbz/lobid-organisations/issues/130), we should reevaluate the technical details to implement this. Updating title and unassigning myself.

**Comment by acka47** [comment]
Today, we got the following request by @a-nnika re. offering other RDF serializations via the API:

> Zur konkreten Verwendung der API 2.0 haben wir noch einige Fragen, da 
> uns das ausgelieferte Datenformat leider leichte Probleme bereitet.  Für 
> den Import der Daten in unser ERMS amsl benötigen wir diese als RDF, 
> optimalerweise als Turtle, NTriple oder RDF/XML. Die bisherige API 
> konnte über Content Negotiation genau diese Formate liefern. Gibt es 
> auch bei der neuen API eine solche Konfigurationsmöglichkeit?
> 
> Falls nicht, wäre es natürlich auch möglich, das gelieferte JSON-LD in 
> Turtle o. ä. umzuformen. Hierbei stellt sich uns aber die Schwierigkeit, 
> dass die Daten in einen weiteren JSON-Rahmen eingebettet sind. In der 
> API-Dokumentation auf Github haben wir leider keine genaue Erläuterung 
> dieses Rahmens gefunden. Können die Daten auch direkt, also nicht 
> eingebettet, abgerufen werden? Dann könnten wir sie ohne wesentlichen 
> zusätzlichen Programmieraufwand konvertieren.

As the use of RDF is more widespread in the library context than in a general web development context we might re-think our approach re. content negotiation. An alternative is to provide documentation on how to easily transform lobid JSON-LD to ntriples, turtle etc.

**Comment by fsteeg** [comment]
Independent of our approach to other serializations, the first step is to fix the issue mentioned in the request, which is that unlike a direct GET for a specific organisation like [1], a search request is no valid JSON-LD, but wrapped into the Elasticsearch response [2].

[1] http://beta.lobid.org/organisations/DE-6
[2] http://beta.lobid.org/organisations/search?q=name%3Astadtbibliothek%2Bberlin

**Comment by fsteeg** [comment]
Opened separate issue for https://github.com/hbz/lobid-organisations/issues/129#issuecomment-214689671. JSON-LD responses and RDF usage documentation: #140.

**Comment by fsteeg** [comment]
On the topic of this issue: given the small size of the organisations data set we could try to avoid the original issue causing the need for scrolling in the first place, and simply serve all results for any request, instead of offering only up to 100 results via pagination.

**Comment by fsteeg** [comment]
Increased max_result_window to support getting full data with one request:

`curl "http://test.lobid.org/organisations/search?q=*&size=25000" > orgs.json`
