### ISSUE TITLE
Update lobid-organisations Elasticsearch version

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#130]
See https://github.com/hbz/lobid/issues/300

**Comment by fsteeg** [comment]
To ease deployment and get a simpler, more self contained setup, we should try using Elasticsearch in embedded mode for lobid-organisations. The lobid-organisations data set is very small, the indexing takes a few seconds only, so I don't think there is a good reason to use a separate server for this data. 

We should take the ES update from this issue as an opportunity to do this.

Our current setup has three quite separate components: the webapp (a Play application launched using the activator), the transformation (a command line application launched with Maven), and the Elasticsearch cluster, managed as a service on our Ubuntu servers.

These three components are actually deployed to three different servers (transformation on weywot2, webapp on quaoar1, ES cluster on quaoar2 and 3). The transformation is triggered by a cron job (from yet another server, weywot1), which calls a bash script, which calls the Maven build.

I propose we try to create a setup where the lobid-organisations repo is all that is needed to set up the full system: check out the repo, run the Play application, and everything else happens behind the scenes: the transformation is triggered, transformation updates are scheduled, an embedded  index is created.

@acka47 @SBRitter @jschnasse Does this sound sensible? Any thoughts?

**Comment by SBRitter** [comment]
Fixes #130

**Comment by fsteeg** [comment]
After https://github.com/hbz/lobid-organisations/pull/133 is deployed, this issue will be resolved.

To follow up on the plan described in https://github.com/hbz/lobid-organisations/issues/130#issuecomment-211335949 I see these next steps:

- Replace Elasticsearch server on localhost with embedded Elasticsearch: https://github.com/hbz/lobid-organisations/issues/136
- Move top-level and web/ projects into a single project with a single build: https://github.com/hbz/lobid-organisations/issues/137
- Replace cron job with internal scheduler: https://github.com/hbz/lobid-organisations/issues/138

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/organisations

**Comment by acka47** [comment]
+1. I tried out the examples on the home page and from bibcast. Everything works. The indices on beta and test don't seem to be identical, though. For some queries beta has one or two results more than test, e.g. 
http://test.lobid.org/organisations/search?q=fundertype.label%3Aland&location=52%2C12+53%2C12+53%2C14+52%2C14
vs.
http://beta.lobid.org/organisations/search?q=fundertype.label%3Aland&location=52%2C12+53%2C12+53%2C14+52%2C14
