### ISSUE TITLE
Enable truncation of ISILs

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#131]
Currently, you can't use truncation searching the `isil` field. This would be useful to filter by sub-libraries of a specific library e.g. for the many Institutsbibliotheken of the ULB Münster http://beta.lobid.org/organisations/search?q=isil:DE-6*.

**Comment by fsteeg** [comment]
The `isil` field also should be `not_analyzed` (or use an ID analyzer), see results for http://beta.lobid.org/organisations/search?q=isil:DE-6

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/organisations/search?q=isil:DE-6
http://test.lobid.org/organisations/search?q=isil:DE-6*

**Comment by dr0i** [comment]
+1
