### ISSUE TITLE
Get correct "Regionalschlüssel" for all entries

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#134]
In http://hbz.github.io/slides/bibcast16/ I showed with two examples how to utilize the "Regionalschlüssel" (RS) for querying organisations in a Bundesland, Landkreis or Gemeinde by utilizing the RS. Unfortunately there are a lot of organizations from the ISIL registry that don't have a RS. If they have one, it may be out of date as – according to A. Heise – this particular information isn't maintained in the ISIL registry as well as in the DBS data:

On 14.04.2016 at 10:53 @cklee wrote in an email:
> Allerdings hat Herr Heise darauf hingewiesen, dass die bestehenden Daten 
> teilweise veraltet sein können, da wir diese den letzten Jahren nicht 
> systematisch überprüft haben. Da sich durch ständige Gebietsreformen in 
> den Bundesländern der Gemeindeschlüssel ändern kann. Dies wird uns von 
> den meldenden Einrichtungen oft nicht mitgeteilt.

For one, this shows that it doesn't make sense that we use the RS from ISIL registry when the information is in both source data sets. However, the ISIL colleagues suggested that we provide an up-to-date RS for the ISIL entries and they will add the corresponding field to the edit form. (It currently is missing and, thus, RS additions/corrections can't be proposed.)

Thus, we somehow need to reliably get the RS for each entry. I think we should first look at Wikidata and then check GeoNames if Wikidata doesn't has what we want.

**Comment by acka47** [comment]
We can check the quality of the enrichment by comparing the data with the manually curated data from the DBS.

**Comment by acka47** [comment]
Here some more data on the current state from the email response to ISIL colleagues I just sent:

> Hier ein kurzer Überblick über die Daten:
> 
> - Einträge gesamt: 23312 [1]
>      - davon mit DBS-ID: 12292 [2]
>      - mit ISIL: 16086 [3]
>      - mit ISIL und DBS-ID: 5066 [4]
> - mit Regionalschlüssel: 13904 [5]
> - mit Reginalschlüssel und DBS-ID: 12078 [6]
> - mit Reginalschlüssel und ISIL: 6728 [7]
> - mit Regionalschlüssel, ISIL und DBS-ID: 4902 [8]
> 
> Natürlich gibt es eine ganze Menge ISIL-Einträge, die gar keinen 
> Regionalschlüssel bekommen können/sollten, z. B. Organisationen 
> außerhalb Deutschlands und E-Ressourcen-Pakete:
> 
> - ISIL-Einträge in Deutschland: 14791 [9]
> - ISIL-Einträge in Deutschland, die E-Ressourcen-Pakete sind: 1064 [10]
> 
> Wenn ich das richtig sehe, fehlen also Regionalschlüssel für etwa 7000 
> ISIL-Einträge: 14791 - 6728 - 1064 = 6999
>
> [1] http://beta.lobid.org/organisations/search?q=*
> [2] http://beta.lobid.org/organisations/search?q=dbsID:*
> [3] http://beta.lobid.org/organisations/search?q=isil:*
> [4] http://beta.lobid.org/organisations/search?q=dbsID:*+AND+isil:*
> [5] http://beta.lobid.org/organisations/search?q=rs:*
> [6] http://beta.lobid.org/organisations/search?q=dbsID:*+AND+rs:*
> [7] http://beta.lobid.org/organisations/search?q=isil:*+AND+rs:*
> [8] 
> http://beta.lobid.org/organisations/search?q=isil:*+AND+dbsID:*+AND+rs:*
> [9] 
> http://beta.lobid.org/organisations/search?q=isil:*+AND+location.address.addressCountry:DE 
> 
> [10] 
> http://beta.lobid.org/organisations/search?q=isil:*+AND+location.address.addressCountry:DE+AND+type:Collection

**Comment by acka47** [comment]
The "Gemeindeschlüssel" field is now part of the ISIL template, see

- http://sigel.staatsbibliothek-berlin.de/beantragung/
- http://sigel.staatsbibliothek-berlin.de/aenderungen-mitteilen/

**Comment by nichtich** [comment]
Ich hab mal nachgeschaut ob sich Regional- und Gemeindeschlüssel in Wikidata ermitteln lassen:

https://www.wikidata.org/wiki/User:JakobVoss/Bibliotheken

Da bislang nicht mal 5.000 Biblioheken einen Wikidata-Eintrag haben (Einträge, die nicht explizit als Bibliothek gekennzeichnet sind nicht mitgezählt, das könnten noch viel mehr sein), finden sich bislang nur 191 Bibliotheken mit Gemeindeschlüssel.

**Comment by acka47** [comment]
Here is a list of the – currently 7950 – entries missing data in field `rs`: http://beta.lobid.org/organisations/search?q=_missing_:rs

**Comment by acka47** [comment]
This might be a good source for mapping: http://www.fa-technik.adfc.de/code/opengeodb/DE.tab It associates an AGS with one or more postal codes.

Or we ask wikidata, e.g. like this: http://tinyurl.com/z3d67s8

**Comment by acka47** [comment]
Also geonames,e.g. http://www.geonames.org/search.html?q=52062&country=DE. This will also work via the geonames API. But there are limits on daily calls to the API...

**Comment by acka47** [comment]
> Also geonames,e.g. http://www.geonames.org/search.html?q=52062&country=DE.

Although geonames shows the Regionalschlüssel in the [HTML](http://www.geonames.org/6553047/aachen.html) ("05334002") I can't get it via geonames or Mapzen API.

**Comment by fsteeg** [comment]
I can't find it even in the HTML (and I think you mentioned that the other day).

The remaining sources linked in https://github.com/hbz/lobid-organisations/issues/134#issuecomment-234968184 only provide AGS, not RS - so not what we want, right?

**Comment by acka47** [comment]
> I can't find it even in the HTML (and I think you mentioned that the other day).

Its here: http://www.geonames.org/6553047/aachen.html

**Comment by acka47** [comment]
> The remaining sources linked in https://github.com/hbz/lobid-organisations/issues/134#issuecomment-234968184 only provide AGS, not RS - so not what we want, right?

We got a lookup table for this which @SBRitter provided, see https://github.com/hbz/lookup-tables/blob/master/data/ags-rs-map.csv

**Comment by acka47** [comment]
I think the best way is to move forward with http://www.fa-technik.adfc.de/code/opengeodb/DE.tab and create a plz-ags-map from it that we can use.

**Comment by fsteeg** [comment]
Deployed to staging:

http://test.lobid.org/organisations/search?q=_missing_:rs
http://test.lobid.org/organisations/search?q=_missing_:ags

**Comment by acka47** [comment]
Looks good. The important question is for how many institutions in Germany the keys are missing: http://test.lobid.org/organisations/search?q=_missing_:rs+AND+location.address.addressCountry:DE I will take a deeper look at that later.

**Comment by acka47** [comment]
What is the current behaviour when a postal code is mapped to multiple keys. Will there be no key assigned? I think this would be the best behaviour. If it is like that: +1

**Comment by fsteeg** [comment]
No, it will take one of the keys. And yes, skipping these would make sense. Will look into a way to do that.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/organisations/DE-MUS-859916?format=json (no RS, AGS)

**Comment by acka47** [comment]
+1. I added #268 to take care of this later.
