### ISSUE TITLE
Implement content negotiation for searches and resources

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#157]
I'd imagine a setup in which both resource URIs like `http://beta.lobid.org/organisations/DE-6` and search URIs like `http://beta.lobid.org/organisations/search?q=fundertype.label:land` return HTML if requested via `Accept: text/html`, and JSON otherwise. The `format=html` query parameter used for #33 and #155 should remain working for browser usage, but not be documented as API.

Creating in `backlog`, will be `ready` after #33 and #155 are closed.

**Comment by fsteeg** [comment]
Deployed to staging, see documentation at http://test.lobid.org/organisations/api

**Comment by SBRitter** [comment]
+1
