### ISSUE TITLE
Expand API documentation

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#159]
Query string syntax (see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax)

Cookbook-style instructions, e.g. for:
- Auto-suggest usage (as in the API 1.x documentation)
- OpenRefine reconciliation usage (see https://github.com/hbz/lobid-organisations/issues/55#issuecomment-129771979)

**Comment by acka47** [comment]
Is this a duplicate of #65?

**Comment by fsteeg** [comment]
Yes, I'd say so.

**Comment by acka47** [comment]
Closing because duplicate.
