### ISSUE TITLE
Visual map facet/aggregation on search result list and as initial search

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#161]
See NWBib coverage facet: http://nwbib.de/search?q=braunkohle

Implemented in: https://github.com/hbz/nwbib/blob/master/app/views/tags/coverage_map.scala.html

On the main search page we could display such a map with a `q=*` query as a visual search entry.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/organisations

**Comment by SBRitter** [comment]
+1
