### ISSUE TITLE
Normalize ö/oe etc.

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#168]
Based on Snowball token filter with `German2`, see: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-snowball-tokenfilter.html, see also NWBib/Lobid implementation in https://github.com/lobid/lodmill/blob/master/lodmill-rd/src/main/resources/index-config.json

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/organisations/search?q=köln
http://test.lobid.org/organisations/search?q=koeln
http://test.lobid.org/organisations/search?q=koln

**Comment by SBRitter** [comment]
+1
