### ISSUE TITLE
Wrong geo locations with old lookup

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#173]
With the geodata service disabled, we get many wrong geo locations.

To reproduce:

- Disable new lookup in application.conf: `transformation.geo.lookup.server=""`
- Run with transformation (delete `tmp/enriched.out.json`)
- See map at `loclahost:9000/organisations` (in particular if you zoom out)

I think it makes sense to remove the old lookup altogether, as it's replaced with the geodata service.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/organisations

**Comment by SBRitter** [comment]
+1
