### ISSUE TITLE
Visual indicator and easy removal of current facet filters

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#181]

**Comment by fsteeg** [comment]
Deployed to staging, see:
http://test.lobid.org/organisations/search?format=html&from=0&size=20&q=*%20AND%20classification.label:%22Zentrale%20Universit%C3%A4tsbibliothek%22%20AND%20stocksize.label:%221.000.001%20und%20mehr%22

**Comment by SBRitter** [comment]
nice!
+1
