### ISSUE TITLE
Tweak details page popup

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#191]
- Striped rows: http://getbootstrap.com/css/#tables-striped (also for actual details?)
- Full width to fit table, see: http://beta.lobid.org/organisations/DE-2239?format=html

**Comment by SBRitter** [comment]
I would suggest to leave the table width and rather use line breaks (comes for free with bootstrap).

**Comment by SBRitter** [comment]
Deployed to staging: http://test.lobid.org/organisations/DE-2239?format=html

**Comment by fsteeg** [comment]
+1
