### ISSUE TITLE
Map is not being displayed for some organisations

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#197]
Map is not being displayed for some organisations, most probably institutions without geo data, see e.g. http://test.lobid.org/organisations/DBS-CH300?format=html.

Originally reported by @SBRitter in https://github.com/hbz/lobid-organisations/pull/195#issuecomment-226234666

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/organisations/DBS-CH300?format=html

**Comment by SBRitter** [comment]
+1
