### ISSUE TITLE
Don't skip markers for orgs without ISIL

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#202]
See:

http://beta.lobid.org/organisations/search?location=&format=html&from=0&size=20&q=*+AND+classification.label:%22Blindenbibliothek%22

http://beta.lobid.org/organisations/search?q=*+AND+classification.label%3A%22Blindenbibliothek%22&location=&format=json

**Comment by fsteeg** [comment]
Deployed to staging.

See:

http://test.lobid.org/organisations/search?location=&format=html&from=0&size=20&q=*+AND+classification.label:%22Blindenbibliothek%22

http://test.lobid.org/organisations/search?q=*+AND+classification.label%3A%22Blindenbibliothek%22&location=&format=json

**Comment by SBRitter** [comment]
+1
