### ISSUE TITLE
Don't show facet header (and map) if there are no facet values

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#203]
See:

http://beta.lobid.org/organisations/search?q=ebsco&format=html

http://beta.lobid.org/organisations/search?location=&format=html&from=0&size=20&q=*%20AND%20classification.label:%22Blindenbibliothek%22+AND+fundertype.label:%22Land%22

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/organisations/search?q=ebsco&format=html

http://test.lobid.org/organisations/search?location=&format=html&from=0&size=20&q=*%20AND%20classification.label:%22Blindenbibliothek%22+AND+fundertype.label:%22Land%22

**Comment by SBRitter** [comment]
+1
