### ISSUE TITLE
Javascript map timeout issue

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#204]
Click `2` cluster on map at http://beta.lobid.org/organisations/search?q=hbz&format=html

**Comment by fsteeg** [comment]
Deployed to staging, click clusters at:

http://test.lobid.org/organisations/search?q=zbw&format=html
http://test.lobid.org/organisations/search?q=fraunhofer&format=html

There are no direct equivalents on beta to compare, since the clusters causing the issue no longer exist (they were due to multiple markers on the same location).

**Comment by SBRitter** [comment]
+1
