### ISSUE TITLE
Handle multiple locations in details view

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#210]
Sample: http://beta.lobid.org/organisations/DE-Bo104?format=json

Perhaps using multiple tabs in the current map area, each displaying one location (as table, or if available, as map with table in popup).

See http://getbootstrap.com/components/#nav-tabs

**Comment by fsteeg** [comment]
Perhaps the postal adress could also be in a tab, see 
http://beta.lobid.org/organisations/DE-605?format=html

**Comment by SBRitter** [comment]
Deployed to staging. See the following examples:

| | postal address | single location with geo | two locations, only one with geo | two locations, both with geo | single location without geo | 
| ---- | ---- | ---- | ---- |  ---- | --- |
| http://test.lobid.org/organisations/DE-Bo104?format=html | | | x | | |
| http://test.lobid.org/organisations/DE-9?format=html | x | x | | | |
| http://test.lobid.org/organisations/DE-393?format=html | | x | | | |
| http://test.lobid.org/organisations/ZDB-Test3?format=html | x | | x | | |
| http://test.lobid.org/organisations/DBS-KA747?format=html | | | | | x |
| http://test.lobid.org/organisations/DE-2178?format=html | | | | x | |
| no example found | x | | | | |

**Comment by fsteeg** [comment]
Best 'deployed to staging' comment ever! :+1:

I've tweaked the code and visuals a bit in https://github.com/hbz/lobid-organisations/pull/213/commits/b9fe901bb77f441d112c141b7c047c7e818d0033 and deployed that to staging. What do you think?

**Comment by SBRitter** [comment]
I like it! The js code looks much better like this!
