### ISSUE TITLE
Improve tokenization for hyphenated words

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#218]
Hyphenated and non-hyphenated words should be normalized, see:

http://beta.lobid.org/organisations/search?q=feuerzeugmuseum
http://beta.lobid.org/organisations/search?q=%22feuerzeug-museum%22

**Comment by SBRitter** [comment]
Deployed to staging: 
http://test.lobid.org/organisations/search?q=feuerzeugmuseum&location=
http://test.lobid.org/organisations/search?q=feuerzeug-museum&location=

**Comment by acka47** [comment]
+1
