### ISSUE TITLE
Name isn't shown in detail view

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#223]
E.g. http://beta.lobid.org/organisations/DE-2174 curently looks like this:

![lobid-org-name-missing](https://cloud.githubusercontent.com/assets/160292/16622798/b045c5d2-439b-11e6-8d95-6553be4780a6.png)

The name probably was shown before instead of the ISIL.

**Comment by acka47** [comment]
The problem only occurs when "English" is selected as language. As the labels for funder type and classification (better would be "additional type" or something similar) are in German, though we have English labels for them I made another issue at #224.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/organisations/DE-2174
http://test.lobid.org/organisations/DE-B2042

**Comment by acka47** [comment]
+1
