### ISSUE TITLE
Show name instead of ID as heading of single entries

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#225]

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/organisations/DE-2174
http://test.lobid.org/organisations/DE-B2042

**Comment by acka47** [comment]
+1
I have problems with the two headers "lobid-organisations — A comprehensive directory of German library institutions" and the organisation's name, though. Will make another issue for this.
