### ISSUE TITLE
Rework layout

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#228]
Here are some problems I have with the current layout:

- The hbz logo at the top left could be moved into the footer
- "lobid-organisations" should be in the top panel besides the tabs, like for example at https://oerworldmap.org/

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/organisations

**Comment by acka47** [comment]
The top panel looks good. Now, we should remove the "lobid-organisations — A comprehensive directory of German library institutions" header. We may keep it on the home page but it shouldn't be shown for single entries.

I think it also make sense to move the "search" field to the top panel instead of the "search" tab.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/organisations
http://test.lobid.org/organisations/search?q=zbw
http://test.lobid.org/organisations/DE-Sol1

**Comment by acka47** [comment]
This is much better. +1
