### ISSUE TITLE
Rename the service with own domain

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#229]
I don't like the name "lobid-organisations". It is ok for describing an endpoint of the lobid API but as end-user oriented service it ~~sucks~~ it's not very good. I could imagine using another name for the HTML version (that also delivers JSON when asked) and giving it a distinct name. What do you think?

I don't have a good idea for a name yet, though. Some bad ideas: "InfoVZ", "LAM Base", "LAM Atlas (LAMA)" ...

**Comment by nichtich** [comment]
"glamdir" is not used much yet, but the twitter account `@glamdir` is taken. "glamorgs" is free in domains and Social Media.

**Comment by fsteeg** [comment]
With its focus on german organisations maybe a german (or neutral/international) name makes sense?

Bib*, Info*, Kultur*

**Comment by acka47** [comment]
I like _domo_ ("Directory of Memory Organizations"). The domain situation isn't good, though. (One could buy domo.info for 499 €...)

Other possibilities:
- memorydir.org 
- memoryhub.org

**Comment by acka47** [comment]
Simply glams.org is also available.

**Comment by jschnasse** [comment]
kulturregister.org

**Comment by jschnasse** [comment]
or more international

register-of-cultural-institutions.org 
library-register.info
glam-register.info
your-library.org

**Comment by fsteeg** [comment]
Noch was mit Kultur:

kultur.institute
kultureinrichtungen.org|net|info

Oder was akronymisches für Bibliotheken, Archive, Museen:

bam.institute
bibam.net|info

**Comment by jschnasse** [comment]
+1 for kultur.institute

**Comment by acka47** [comment]
Ideen von Ira:

- was mit "Adressen" oder "Index"
- kulturkontakt (sieht nicht so gut aus von domains her)

**Comment by acka47** [comment]
kulturkontakt.net is available.

**Comment by acka47** [comment]
nachweis.bar

**Comment by acka47** [comment]
""Kultur. nachschlagbar" als Name des Dienstes mit domain kulturnachschlag.bar. Und als Logo eine große Kelle mit Büchern, Schriftrollen, einer Skulptur, einem Gemälde über einem Teller.

**Comment by dr0i** [comment]
`bam.institute`

**Comment by fsteeg** [comment]
In an offline discussion, we decided to launch as `lobid.org/organisations` to stay on time (see https://github.com/hbz/lobid-organisations/issues/247).

Moving to backlog.

**Comment by acka47** [comment]
Because of licensing problems with DBS data (see https://github.com/hbz/lobid-organisations/issues/247#issuecomment-246604018) we didn't need to launch the service last week. In discussions about a LOD hbz flyer we came back to the point that we should resolve the questions around lobid as a "platform" hosting different products ("lobid-organisations" and "lobid-resources"). Thus, this is still a current issue.

**Comment by acka47** [comment]
I have another proposal: lamda as name, lamda.info as domain. "LAM" referring to libraries, archives and museums and "da" to the German pointer to a location.

**Comment by fsteeg** [comment]
I do kind of like `lamda`, but isn't it just as cryptic as `lobid`?

**Comment by acka47** [comment]
> I do kind of like `lamda`, but isn't it just as cryptic as `lobid`?

Currently, it is not called "lobid" but "lobid-organisations". And the problem is that we don't know how to distinguish and uphold some kind of identity for "lobid" itself – considering the different services that are running under this moniker ("lobid-organisations" and "lobid-resources" as well as "lobid-subjects" or what you might call it).Thus, it is most important to resolve this "identity crisis" with a distinct name for the service (and for the other API 2.0 launches to come...).

And yes, "lamda" is not a descriptive name. But this isn't that important – at least to me. The descriptive names we came up with are often inaccurate in their description (kultur.institute, glams.org) or have other problems. In my view, the name should be short, easily memorizable and have a good sound.

**Comment by fsteeg** [comment]
Internal discussion is leading towards a unified subdomain approach for different lobid products.

At the same time, we're considering a perspective for this service to widen its content beyond GLAM.

As we don't have a good suggestion for a subdomain that covers non-GLAM either, I think we should stick with https://github.com/hbz/lobid-organisations/issues/229#issuecomment-244711756: launch what we've got as `lobid.org/organisations`, and close this issue.

**Comment by acka47** [comment]
Closing.
