### ISSUE TITLE
Omit "mailto:" befor emails

### ISSUE THREAD

**Issue by nichtich** [hbz/lobid-organisations#231]
E.g. at http://test.lobid.org/organisations/DE-7 it shows

    Email  mailto:sekretariat@sub.uni-goettingen.de

but better show

    Email  sekretariat@sub.uni-goettingen.de

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/organisations/DE-7

**Comment by acka47** [comment]
+1
