### ISSUE TITLE
Phrase search does not work

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#236]
E.g. http://beta.lobid.org/organisations/search?q=%22DE-1549%22 returns thousands of libraries, though I would only like to see the one with this ISIL.

**Comment by fsteeg** [comment]
This is probably due to the hyphen, see #218. Ping @SBRitter.

**Comment by fsteeg** [comment]
This seems to be an issue with the hyphen filter we use, phrase search, and searching over all fields.

General phrase search works:
http://beta.lobid.org/organisations/search?q=%22Maristengymnasium+F%C3%BCrstenzell%22

Specific ISIL field search also works:
http://beta.lobid.org/organisations/search?q=isil:DE-1549

@acka47 Is this good enough?

**Comment by acka47** [comment]
DI don't have the time to deeper look into this now. Anyhow, there was a similar issue in the OER World Map project see https://github.com/hbz/oerworldmap/issues/831#issuecomment-243883412. Maybe it helps...

**Comment by fsteeg** [comment]
We're actually using the tokenizer Jörg mentioned in that comment. I think our current behavior is good.

**Comment by acka47** [comment]
+1 I think it is ok like it is:

- Getting a institution by ISIL: http://test.lobid.org/organisations/search?q=isil:DE-6
- Getting branches/subordinated libraries by using asterisk: http://test.lobid.org/organisations/search?q=isil:DE-6*
