### ISSUE TITLE
Problems with 15 orgs that have DBS ID "DBS" in ISIL registry

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#237]
Here is a list of the 15 organisations (excluding the first hit AT-DBSBG): http://sigel.staatsbibliothek-berlin.de/suche.html?tx_sbbyaz_pi1[q]=%22DBS%22

There currently is only one entry in lobid that has the DBS ID "DBS" in ISIL registry:

http://beta.lobid.org/organisations/DE-1699?format=json (same as http://ld.zdb-services.de/resource/organisations/DE-1586)

This entry has a lot of (all?)  `alternateName`s from other orgs with DBS ID "DBS".

The other 14 orgs with DBS ID "DBS" in ISIL registry are missing, e.g. 

http://beta.lobid.org/organisations/DE-1507 -> http://ld.zdb-services.de/resource/organisations/DE-1507
http://beta.lobid.org/organisations/DE-1549 -> http://ld.zdb-services.de/resource/organisations/DE-1549 
http://beta.lobid.org/organisations/DE-1672 -> http://ld.zdb-services.de/resource/organisations/DE-1672
http://beta.lobid.org/organisations/DE-1586 -> http://ld.zdb-services.de/resource/organisations/DE-1586

The ISIL data should be corrected, nonetheless this shouldn't happen during transformation. I will fix ISIL entries after we have taken care of the transformation issue.

**Comment by fsteeg** [comment]
Deployed to staging:

http://test.lobid.org/organisations/search?q=dbsID:DBS&format=json
http://test.lobid.org/organisations/DE-1699?format=json
http://test.lobid.org/organisations/DE-1507?format=json
http://test.lobid.org/organisations/DE-1549?format=json
http://test.lobid.org/organisations/DE-1672?format=json
http://test.lobid.org/organisations/DE-1586?format=json

**Comment by acka47** [comment]
+1
