### ISSUE TITLE
Empty popup when clicking on marker

### ISSUE THREAD

**Issue by SBRitter** [hbz/lobid-organisations#239]
After the page is loaded, marker pop up marker is fine (table with address data is shown). However, when marker is click pop up is created again without content. (see for example -- click on marker: http://beta.lobid.org/organisations/DBS-AA611)

**Comment by SBRitter** [comment]
Deployed to staging: http://test.lobid.org/organisations/DE-MUS-718716

1. Close pop up
2. Click on the marker to open it again
3. See that the table is there again! :-)

**Comment by acka47** [comment]
+1
