### ISSUE TITLE
Organisation data entries with identical id

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-organisations#24]
Moved this issue originated in  lobid/lodmill#627  created by @SBRitter (since it affects not the old graph based transformation, but the new record centristic one): 

"There are some organisations that possess an inr and an isil in their DBS entry but only an isil in their Sigel entry. Because the merging of entries is done on the basis of inr, these entries are not merged. Thus, the organisation will exist twice in the data, as do many organisations. However, in this particular case both entries will recieve their isil (exists in both data sources -- Sigel and DBS) as their id for Elasticsearch indexing. As a consequence, there will be two entries with identical ids before indexing. During indexing, the second entry with this id will overwrite the first. The order of the entries is determined by the internal id in Metafacture -- i.e. the inr or the isil. At the moment, there are around 150 duplicate entries of this kind (about 0.5% of the data)."

**Comment by philboeselager** [comment]
I assume the DOD to be:
- Organisations are merged in accordance to their isil if one of the entries (either Sigel or DBS) does not contain an inr. This rule also applies to the Sigel update mechanism.
- The resulting data set does not contain any duplicates based on an "missing inr" mismatch.
@dr0i : Please confirm.

**Comment by dr0i** [comment]
confirmed

**Comment by dr0i** [comment]
What am I expected to do?

**Comment by philboeselager** [comment]
Was accidentally closed without merge.

**Comment by philboeselager** [comment]
A list of isil=dbsID merged documents is provided in https://github.com/hbz/lobid-organisations/pull/80 . You can verify the ticket by comparing the results of requests to indices pre and post this ticket. On quaoar1, there is

* old: organisations-issue51-premergeissue24
* new: organisations-issue51

Requests on the new index should reveal all infos from DBS dump and the correspondent Sigel update (aside from single fields/triples are replacing one another, of course).

**Comment by acka47** [comment]
> You can verify the ticket by comparing the results of requests to indices pre and post this ticket. On quaoar1, there is
old: organisations-issue51-premergeissue24
new: organisations-issue51

I won't take this effort and trust you on this one. +1

**Comment by philboeselager** [comment]
Deployed to beta.lobid.org. Closing.
