### ISSUE TITLE
Add 'subject' to details view

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#240]
See http://beta.lobid.org/organisations/DE-B2042?format=json

**Comment by fsteeg** [comment]
Deployed to staging:

http://test.lobid.org/organisations/search?q=subject:*
http://test.lobid.org/organisations/DE-121

**Comment by acka47** [comment]
Looks good. I am not sure about "Themen" as German labelb but it might be better for some users than "Schlagwörter". +1
