### ISSUE TITLE
Blog post(s) to announce   the launch

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#247]
Two things will happen in September:
- On September 8th the final decision to publish DBS Stammdaten under an open license will (most probably) be made.
- On 17-18 September the hackathon Coding da Vinci Nord will be kicked off (see https://codingdavinci.de/).

With the opening of DBS data all lobid-organisations data will be openly licensed and, thus, could be used in the Coding da Vinci hackathon. We will take the opportunity and officially launch lobid-organisations and its UI by mid-September. Things to be done before launch will be tagged with ["org-launch"](https://waffle.io/hbz/lobid?label=org-launch).

**Comment by acka47** [comment]
Last week, the [KNB Steering Body](http://www.bibliotheksportal.de/wir-ueber-uns/kompetenznetzwerk/hintergrund.html#c2600) did not make a final decision on the opening of DBS address data. They agreed that an open license for the DBS address data is the way to go but only decided on a recommendation for the  [KMK](https://www.kmk.org/). I guess, it will probably take 1-2 years or even more until the final decision. :disappointed:

**Comment by fsteeg** [comment]
Collecting some things to do right after/with the launch:

- redirect `beta.lobid.org/organisations` to `lobid.org/organisations`
- when #245 #65 #229 are done , we should summarize that in a blog post, and mention #259

**Comment by fsteeg** [comment]
Updating title to reflect remaining task (proxy without beta been in place for a while, #259 will happen later, blogging about the launch remains).

**Comment by acka47** [comment]
We also need to write a "Pressemitteilung" for the hbz homepage.

**Comment by acka47** [comment]
Done, see https://www.hbz-nrw.de/aktuelles/nachrichten/relaunch-von-lobid-resources-und-lobid-organisations & http://blog.lobid.org/2017/07/04/lobid-launch.html. Closing.
