### ISSUE TITLE
Adjust URIs

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#248]
Currently, there are beta.lobid.org URIs in the JSON-LD. We will need to remove the "beta" with the launch. (Another option would be to remove lobid.org/organisations altogether and completely move to a the new domain – if we find one.)

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/organisations/DE-Sol1?format=json

**Comment by acka47** [comment]
+1
