### ISSUE TITLE
Adjust URIs for linkedTo statements

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#249]
Currently `linkedTo` statements point to the old lobid-organisations, see https://github.com/hbz/lobid-organisations/blob/5471bf34586ba186e29441f021379bf6926af241/app/transformation/morph-enriched.xml#L340-L359. We should exchange these before launch. (Related to #248 and #229.)

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/organisations/DE-Sol1?format=json

**Comment by acka47** [comment]
+1
