### ISSUE TITLE
Minor data adjustments

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#25]
The JSON-LD of all organisation says the `@context` is still at http://data.lobid.org/organisations/context.jsonld. That is not the case as we exchanged the 'data' by 'beta. Thus, the context is now at http://beta.lobid.org/organisations/context.jsonld.

Please adjust in the data.

**Comment by acka47** [comment]
@dr0i Will you do this or should I assign @philboeselager?

**Comment by acka47** [comment]
Same with the `@id` URI.  E.g. http://beta.lobid.org/organisations/DE-11 (snippet):

```
{
    "dbsID": "AD011",
    "isil": "DE-11",
    "isPrimaryTopicOf": "http://dispatch.opac.d-nb.de/DB=1.2/CMD?ACT=SRCHA&IKT=8529&TRM=DE-11",
    "wikipedia": "http://de.wikipedia.org/wiki/Universitätsbibliothek_der_Humboldt-Universität_zu_Berlin",
    "@context": "http://data.lobid.org/organisations/context.jsonld",
    "@type": "http://schema.org/Library",
    "linkedTo": "http://lobid.org/organisation/DE-602",
    "rs": "011000000000",
    "name": "Humboldt-Universität zu Berlin Universitätsbibliothek",
    "url": "http://www.ub.hu-berlin.de",
    "provides": "http://casanova.ub.hu-berlin.de",
    "@id": "http://data.lobid.org/organisations/DE-11",
    ...
}
```

Should be changed to `"http://beta.lobid.org/organisations/{isil}`

**Comment by acka47** [comment]
Also, as soon as the new context is merged (#27), we should replace all occurences of `@type` and `@id` in the data by `type` and `id`.

**Comment by SBRitter** [comment]
Made changes and opened pull request

**Comment by dr0i** [comment]
When deploying and recreating data, the file `enriched.out.json` reads like this `{"index":{"_index":"organisations","_type":"organisation","_id":null}}`. The `_id` is null , and this goes for all dox, resulting in one lonely doc.
Investigating.

**Comment by SBRitter** [comment]
I encountered this problem yesterday with my test data. The problem was the following:
- The JsonSearchBulk constructor gets the parameter for _id: JsonToElasticsearchBulk("id", "organisation", "organisations");
- When I ran it for the first time, the code still had @id instead of id in it
- Because we got rid of the @-symbols, @id has now become id

Please check whether the JsonToElasticsearchBulk gets constructed correctly in the method continueWith() of the class Enrich.

**Comment by dr0i** [comment]
Uh - had forgotten to build the jar ;P
Now it's working, have a look.

**Comment by dr0i** [comment]
Everything seems fine now - closing.
