### ISSUE TITLE
Describe lobid-organisations dataset

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#255]
See https://www.w3.org/TR/dwbp/#metadata. I will first provide a JSON file using schema.org/dcat descibring the lobid-organisations dataset.

**Comment by acka47** [comment]
```json
{
  "@context": {
    "@vocab": "http://schema.org/",
    "dct:": "http://purl.org/dc/terms/",
    "dcat": "http://www.w3.org/ns/dcat#"
  },
  "id": "http://lobid.org/organisations#!",
  "type": "Dataset",
  "name": "lobid-organisations",
  "keywords": [
    "libraries",
    "archives",
    "museums",
    "locations"
  ],
  "spatial": [
    "http://www.wikidata.org/entity/Q183",
    "http://www.wikidata.org/entity/Q39",
    "http://www.wikidata.org/entity/Q40"
  ],
  "datePublished": "2016-09-14",
  "contactPoint": {
    "url": "http://lobid.org/contact"
  },
  "dct:accrualPeriodicity": "http://purl.org/linked-data/sdmx/2009/code#freq-B",
  "inLanguage": [
    "de",
    "en"
  ],
  "publisher": "http://lobid.org/organisations/DE-605#!",
  "distribution": [
    {
      "id": "http://lobid.org/organisations/search#!",
      "type": "dcat:Distribution",
      "name": "lobid-organisations API",
      "description": "The API gives access to machine-readable data. For documentation see http://lobid.org/organisations/api.",
      "dcat:accessURL": "http://lobid.org/organisations/search",
      "dcat:mediaType": [
        "text/csv",
        "application/json",
        "application/ld+json"
      ],
      "license": "https://creativecommons.org/publicdomain/zero/1.0/"
    }
  ]
}
```

**Comment by acka47** [comment]
lobid (resources) data already has an entry on at least three open data portals:

- http://www.europeandataportal.eu/data/de/dataset/lobid-resources
- https://www.govdata.de/apps/-/details/lobid-resources
- https://datahub.io/de/dataset/lobid-resources

Obviously, the first two got/get their data from the datahub.

**Comment by acka47** [comment]
We decided to add an "about" page for this information with a human-readable version of the text generated from the JSON-LD. I will start with updating the file and putting it into an `about.jsonld` file in `/conf` folder.

**Comment by acka47** [comment]
From https://github.com/hbz/lobid-organisations/pull/312#issuecomment-284992034:

> If suggest putting this information (= the about page) under http://lobid.org/organisations/dataset and update the id to http://lobid.org/organisations/dataset#!.

**Comment by fsteeg** [comment]
Deployed to staging:

http://test.lobid.org/organisations/dataset
http://test.lobid.org/organisations/dataset.jsonld

**Comment by acka47** [comment]
I adjusted the dataset URI and added an `alternateName` in German and English. +1

**Comment by ChristophEwertowski** [comment]
@acka47 : The description link for the German documentation leads to the English one. Also there is a blank too much in the last sentence of the English description of the rights. Otherwise +1

**Comment by acka47** [comment]
Thanks, fixed it.

**Comment by fsteeg** [comment]
Current version deployed at:

http://test.lobid.org/organisations
