### ISSUE TITLE
Set up 301 redirect from 1.0 to 2.0

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#259]
From #32:

> When switching the beta to production and cutting of lobid-organisations 1.0, we will have to implement a redirect from 1.0 to 2.0 with HTTP status code 301, see also http://patterns.dataincubator.org/book/unpublish.html.

**Comment by acka47** [comment]
Before we switch of 1.0 and add the redirect, we should announce the launch of 1.0 and run both in parallel for some weeks.

**Comment by fsteeg** [comment]
After the launch we should also redirect `beta.lobid.org/organisations` to `lobid.org/organisations`.

**Comment by fsteeg** [comment]
When all is set up, including #245 #65 #229, we should summarize that in a blog post.

**Comment by fsteeg** [comment]
Moved some previous content from here to https://github.com/hbz/lobid-organisations/issues/247#issuecomment-265091472

**Comment by acka47** [comment]
Redundant with https://github.com/lobid/lodmill/issues/800. Closing.
