### ISSUE TITLE
Use https as default

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#263]
i.e. redirect http:// URLs to the corresponding https:// URL.

The big question is: Shouldn't we better use https URIs in the RDF with https as default?

**Comment by fsteeg** [comment]
In the spirit of https://www.w3.org/DesignIssues/Security-NotTheS.html I'd favor HTTP URIs in the data.

**Comment by acka47** [comment]
https://www.w3.org/blog/2016/05/https-and-the-semantic-weblinked-data/ also suggests to go on using "http".

**Comment by dr0i** [comment]
http://lobid.org/organisations and all subsequent URIs should now be redirected to the https variant.

**Comment by acka47** [comment]
We reverted the change as it meant a huge API break and looking at the logs, several clients did not follow the redirect. Thus, we should only implement this change after an announcement and time to adjust clients (if at all).
Closing this issue now in favor of the general issue https://github.com/hbz/lobid/issues/352.
