### ISSUE TITLE
Remove test entries

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#269]
See also https://twitter.com/collidoscope/status/775269236218429441. I guess, these are all test entries:

http://lobid.org/organisations/DBS-SP001
http://lobid.org/organisations/DBS-WB001
http://lobid.org/organisations/ZDB-Test2

**Comment by cKlee** [comment]
Our test records are:
ZDB-Test2
ZDB-Test2a
ZDB-Test3

**Comment by acka47** [comment]
Thanks, @cKlee . http://lobid.org/organisations/ZDB-Test2a is there and should also be removed. http://lobid.org/organisations/ZDB-Test3 already can't be found in lobid anyway...

**Comment by TobiasNx** [comment]
http://test.lobid.org/organisations/DBS-SP001
http://test.lobid.org/organisations/DBS-WB001
http://test.lobid.org/organisations/ZDB-Test2
http://test.lobid.org/organisations/ZDB-Test2
http://test.lobid.org/organisations/ZDB-Test2a
http://test.lobid.org/organisations/ZDB-Test3

all are deleted

**Comment by acka47** [comment]
+1

**Comment by TobiasNx** [comment]
> http://test.lobid.org/organisations/DBS-SP001 http://test.lobid.org/organisations/DBS-WB001 http://test.lobid.org/organisations/ZDB-Test2 http://test.lobid.org/organisations/ZDB-Test2 http://test.lobid.org/organisations/ZDB-Test2a http://test.lobid.org/organisations/ZDB-Test3
> 
> all are deleted

http://lobid.org/organisations/DBS-SP001 http://lobid.org/organisations/DBS-WB001 http://lobid.org/organisations/ZDB-Test2 http://lobid.org/organisations/ZDB-Test2 http://lobid.org/organisations/ZDB-Test2a http://lobid.org/organisations/ZDB-Test3

Deployed with #450
