### ISSUE TITLE
Use geonames linked data URIs

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#271]
Geonames uses URIs of the form `http://sws.geonames.org/$id/`. We should also use these in our data. We probably just have to fix https://github.com/hbz/lobid-organisations/blob/4547f7ae2b8b575f8ffb3c9e82db46fe23041c5e/app/transformation/morph-enriched.xml#L346.

**Comment by fsteeg** [comment]
Deployed to staging:

http://test.lobid.org/organisations/search?q=containedIn%3A*&format=json

**Comment by acka47** [comment]
+1
