### ISSUE TITLE
Second-level types are not included in context/shortened

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#272]
http://schema.org/Place, http://schema.org/PostalAddress, http://schema.org/OpeningHoursSpecification

I think we should shorten them like the first-level types.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/organisations/DE-605?format=json

**Comment by acka47** [comment]
+1 Looks good. It's a pity we can't add the type `GeoCoordinates`, though.

I noticed another thing: On staging the link goes to the [production context](http://lobid.org/organisations/context.jsonld) which doesn't have the newly added types. In the [test context](http://test.lobid.org/organisations/context.jsonld) I can see them, though. Ideally, the context link on staging would be corrected.-

**Comment by fsteeg** [comment]
I'm sure we can address the two issues you mentioned, so if they are important we can open issues. The first issue would require a change to the geo field structure (see [1]), so that would block our 2.0 launch.

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html
