### ISSUE TITLE
Don't override relevance ranking with geo search

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#280]
When I type in a specific search (e.g. http://lobid.org/organisations/search?q=usb+k%C3%B6ln) I don't get the expected result as first hit. In my case (via vpn) it even can't be found within the first 20 hits.

There are different options to address this:
- Use the geo filter only when no query has been entered. 
- Use a combination of geo filter plus relevance ranking (take the first twenty results from the geo query and sort them by relevance.)
- ?

**Comment by acka47** [comment]
I think we should fix this before the official launch. Adding the respective label.

**Comment by fsteeg** [comment]
'Scoring by distance' sounds like what we want here, see:
https://www.elastic.co/guide/en/elasticsearch/guide/current/sorting-by-distance.html#scoring-by-distance
