### ISSUE TITLE
Describe collection as separate object

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#281]
A [discussion on twitter](https://twitter.com/fsteeg/status/805347749797498880) mad eme think about the way we say something about the collection of an organization. Generally, I think we should tweak the modelling a bit. Instead of:

```json
"id": "http://lobid.org/organisations/DE-38M#!",
"stocksize" : {
    "id" : "http://purl.org/lobid/stocksize#n09",
    "type" : "Concept",
    "label" : {
      "de" : "300.001 - 1.000.000",
      "en" : "300,001 - 1,000,000"
    }
  },
  "subject" : [ "Medizin" ]
``` 

We should do something like this:

```json
  "id": "http://lobid.org/organisations/DE-38M#!",
  "collects": [ {
    "type": "Collection",
    "extent" : {
      "id" : "http://purl.org/lobid/stocksize#n09",
      "type" : "Concept",
      "label" : {
        "de" : "300.001 - 1.000.000",
        "en" : "300,001 - 1,000,000"
      }
    },
    "subject" : [ "Medizin" ]
  } ]
``` 

This is a better way to express it and would enable us to add more info about a collection – or several collections maintained by an organization – in the future. Sorry that I come up with this now, but I think it shouldn't be too much work to implement it before official launch.

**Comment by fsteeg** [comment]
What should `collects` map to in the context document?

**Comment by acka47** [comment]
I had taken a first look at this but didn't find/decide on suitable properties. To move forward with this, we should use the following:

```json
{
   "collects":{
      "@type":"@id",
      "@id":"http://purl.org/lobid/lv#collects",
      "@container":"@set"
   },
   "extent":{
      "@type":"@id",
      "@id":"http://purl.org/dc/terms/extent"
   }
}
```

We can then describe a property `lv:collects` in the future as needed or change to another one if we find something suitable.

(An aside re. `extent`: We could also use `"@container": "@set"` for syntactic homogeneity. But obviously, we didn't decide to consistently use arrays in lobid-organisations 2.0 as we did in lobid-resources and only use arrays where multiple values are possible. Thus, it would be consistent to not use `"@container": "@set"`.)

**Comment by acka47** [comment]
I updated the example above re. using an array on `collects` as written in the proposed context snippet.

**Comment by fsteeg** [comment]
As discussed offline, for consistency with the other fields, we'll not use an array/set for both (we use arrays only for fields where we actually have multiple values in some of the data).

@acka47 Forget about the problem with arrays containing entities that I mentioned, we actually have that for the `location` field, so that should not be a general problem.
