### ISSUE TITLE
Add type schema:Library to all DBS resources

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#29]
We already added type information to resource from the ISIL registry, see lobid/lodmill#509. We also have to add type information to the resources from DBS. As all of them are libraries we can globally type them as `schema:Library`.

**Comment by acka47** [comment]
Assigning @SBRitter. Simon, let me know if you don't have the time and I will reassign.

**Comment by SBRitter** [comment]
I see the point. I added a rule for DBS-only entries and opened up a pull request. However, I am not really able to test the new transformation as I have only access to the sample data.

**Comment by dr0i** [comment]
You now have access to the data? If not : what data execatly to you need?

**Comment by dr0i** [comment]
Uhm, sorry @SBRitter . I think it was meant that I the task, away from you.

**Comment by philboeselager** [comment]
Should we add some schema:PostalAddress to DBS data as well? (Unclassified yet.)

**Comment by acka47** [comment]
> Should we add some schema:PostalAddress to DBS data as well? (Unclassified yet.)

I already told you face to face: Please add it in the `location` object, e.g.:
```
{
  "id": "http://beta.lobid.org/organisations/DBS-AA609",
  "location": [ {
        "address": {
        "type": "http://schema.org/PostalAddress",
        "streetAddress": "Am Honigbraum 13",
        "addressLocality": "Eppstein-Niederjasbach"
        }
     }
  ]
}
```

**Comment by acka47** [comment]
+1. Looks very good and [is appreciated](https://twitter.com/hauschke/status/608595551861526529). Closing.
