### ISSUE TITLE
Implement language specific URLs

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#292]
We now have the `Content-Language` header implemented (#287) but it seems as if language-specific URLs are best practice, see e.g. http://ux.stackexchange.com/questions/68368/should-language-be-part-of-a-website-url/68375 or https://support.google.com/webmasters/answer/182192.

I think, we should also do this, it will especially help us with the hypothes.is problem. What do you think?

**Comment by acka47** [comment]
This is also interesting with regard to structuring URLs for internationalization: http://webmasters.stackexchange.com/questions/403/how-should-i-structure-my-urls-for-both-seo-and-localization/44289#44289

**Comment by acka47** [comment]
Thinking about this more, I am not sure how we would use different language URLs for the single organisations, e.g. http://lobid.org/organisations/DE-38M. As we will have to implement some redirect from "URL-with-no-language.indicator" to "URL-with-language-indicator" this might work somehow, though...

**Comment by fsteeg** [comment]
How about this: since `de` is our default (if no Accept-Language header is set, the response is `de`), we could leave the URLs as they are for `de`, and redirect to include a `lang=en` query parameter otherwise.

**Comment by acka47** [comment]
Sounds good to me. but I am not sure about the query parameter approach. In http://webmasters.stackexchange.com/questions/403/how-should-i-structure-my-urls-for-both-seo-and-localization/44289#44289 it says that it wouldn't work with google...

**Comment by fsteeg** [comment]
With a path approach, I see two issues:

1. With the application base at `http://lobid.org/organisations` it would be e.g.`http://lobid.org/organisations/en/DE-150`. This seems wrong, as it implies `organisations` are restricted to `en` resources. In general the language is no structuring element, so it seems more like a parameter, less like a path segment.
2. A path segment that is optional seems wrong, we'd have `http://lobid.org/organisations/DE-150` or `http://lobid.org/organisations/en/DE-150` (different structure) vs. `http://lobid.org/organisations/DE-150` or `http://lobid.org/organisations/DE-150?lang=en` (same structure, optional parameter).

All a bit fuzzy I guess, but that's my feeling.

About the Google support: I can't imagine that's an issue. The only concrete thing mentioned in the linked answer is "For example, there is no way to set targeting in webmaster tools", which does not seem to affect us (or our users).

**Comment by acka47** [comment]
In https://support.google.com/webmasters/answer/182192?hl=en, Google discourages using the parameter approach and lists the following disadvantages:

> - URL-based segmentation difficult
> - Users might not recognize geotargeting from the URL alone
> - Geotargeting in Search Console is not possible

I don't understand the first one, the second one does not persuade me and the third one might be a good point.

**Comment by acka47** [comment]
Generally, it might be enough to only have language specific URLs for the static pages. Which wouldn't free us from deciding on how to implement the language-specific URLs...

**Comment by fsteeg** [comment]
I don't even know what "Geotargeting in Search Console" is, but I don't think we'd want this: "However, don’t use this tool if your site targets more than a single country."

**Comment by fsteeg** [comment]
Maybe we should refocus on the actual issue of multi-language annotations for the documentation page and just set up `http://lobid.org/organisations/api/de` and `http://lobid.org/organisations/api/en`.
