### ISSUE TITLE
Removing international ISILs

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-organisations#295]
I know, I know.
If we dump the international ISIL uris someone should remove them from the dbpedia, too, see e.g. http://dbpedia.org/page/AAA_Foundation_for_Traffic_Safety .
There is a github-repo where the links are referenced: https://github.com/dbpedia/links/tree/master/links/dbpedia.org/lobid.org.

**Comment by acka47** [comment]
Won't fix. Closing
