### ISSUE TITLE
Add e-resource packages 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#308]
With #207 we removed the e-resource packages that are part of the ISIL data as they are no organisations. Since then it became clear that they would be useful to have, see https://github.com/hbz/lobid-resources/issues/288.

We should think about how to re-include them:
- Should they get their own route, e.g.  `/eresource`
- They even could be added to lobid-resources?
- Or should we add them to `organisations` but exclude them from search by default?

**Comment by acka47** [comment]
As noted in https://github.com/hbz/lobid-resources/issues/496, I think we should use the third option: re-including them in the data so that the URIs resolve but exclude them from search.

**Comment by acka47** [comment]
Moving this one up as ithe related https://github.com/hbz/lobid-resources/issues/288 is important for UB Dortmund & the production launch of their discovery service.

**Comment by fsteeg** [comment]
Deployed to test:

No collections in search results, as before:

http://test.lobid.org/organisations/search

But accessible directly:

http://test.lobid.org/organisations/ZDB-1-ANR
http://test.lobid.org/organisations/ZDB-1-AIPMS

**Comment by acka47** [comment]
+1 

It would be great to also enable a search over the e resource packages in the future. Either by adding a parameter like `&collections=true` or by just adding the `type:Collections` statement. if this is easily done, we might as well add the possibility now.

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/organisations/search?q=*+AND+type:Collection

**Comment by acka47** [comment]
Very nice. +1
