### ISSUE TITLE
Include information on hierarchical relationships in JSON-LD

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#309]
Requested by @ubleipzig staff. 

By now there is information on the "Übergeordnete Einrichtung" in some entries, especially for Kiel, see e.g. http://sigel.staatsbibliothek-berlin.de/suche/?isil=DE-8-13. The information is provided in Pica+ field `029R`, see the documentation at http://sigel.staatsbibliothek-berlin.de/vergabe/adressenformat/510/. Unfortunately, the ISIL of the superordinated organisation is not in there but only the name string and the internal ID (PPN) making this not straightforward to implement. See this Pica+ snippet for [DE-8-13](http://services.dnb.de/sru/bib?operation=searchRetrieve&query=isl%3DDE-8-13&recordSchema=PicaPlus-xml&version=1.1):

```xml
<ppxml:tag id="029R" occ="">
  <ppxml:subf id="9">009003126</ppxml:subf>
  <ppxml:subf id="7">Tw</ppxml:subf>
  <ppxml:subf id="a">Universitätsbibliothek Kiel, Zentralbibliothek</ppxml:subf>
</ppxml:tag>
```

**Comment by acka47** [comment]
@jorol,@cklee: Would it be a problem to include the ISIL of the superordinated organisation somewhere in `029R`?

**Comment by cKlee** [comment]
@acka47 We made a request to the DNB for that. But neither it's sure if it gets accepted, nor there is a time horizont. If you're aiming for a quick implementation, I would suggest to go with a local data lookup.

Currently it affects only 225 resources. And another problem: Some libraries changed their organizational structure and data may be outdated. So stating that Org A is a subdivision to Org B maybe wrong.

**Comment by cKlee** [comment]
DNB set release date of field extension with ISIL in 029R to 2017-05-02.

**Comment by acka47** [comment]
Great, who would have thought that it is added so quickly. I think we can easily wait with implementation until May.

**Comment by acka47** [comment]
These arethe schema.org properties to use:

- http://schema.org/parentOrganization: "The larger organization that this organization is a subOrganization of"
- http://schema.org/subOrganization: "A relationship between two organizations where the first includes the second, e.g., as a subsidiary. "

**Comment by cKlee** [comment]
Pica+ 029R now contains subfield $e with ISIL of super organization.

**Comment by acka47** [comment]
Thanks, I will take a look at it next week.

**Comment by nichtich** [comment]
Hierarchical relationships may also include relationship between a university library and its university. This information is not included in DBS or ISIL directory but in Wikidata (see #348).

**Comment by acka47** [comment]
So, the data is there, see e.g. this current Pica+ snippet for [DE-8-13](http://services.dnb.de/sru/bib?operation=searchRetrieve&query=isl%3DDE-8-13&recordSchema=PicaPlus-xml&version=1.1):

```xml
<ppxml:tag id="029R" occ="">
  <ppxml:subf id="9">009003126</ppxml:subf>
  <ppxml:subf id="7">Tw</ppxml:subf>
  <ppxml:subf id="a">Universitätsbibliothek Kiel, Zentralbibliothek</ppxml:subf>
  <ppxml:subf id="e">DE-8</ppxml:subf>
</ppxml:tag>
```

So, we can at least at the link to the data like:

```json
{
   "id":"http://lobid.org/organisations/DE-8-13#!",
   "parentOrganization":{
      "id":"http://lobid.org/organisations/DE-8#!"
   }
}
```
For the sake of consistency, we should also add the label for the parent organization. I don't know whether there already is the possibility to look up lobid-organisations while creating the JSON but, anyway, ideally it should look like this:

```json
{
   "id":"http://lobid.org/organisations/DE-8-13#!",
   "parentOrganization":{
      "id":"http://lobid.org/organisations/DE-8#!",
      "label":"Universitätsbibliothek Kiel. Zentralbibliothek"
   }
}
```
Assigning @fsteeg. It probably makes sense that you can walk @ChristophEwertowski through the process so that he also can work on the lobid-organisations transformation in the future.

**Comment by TobiasNx** [comment]
I added the info for `parentOrganisation` but we need a mapping for getting the `subOrganisations` they are not included in the sigil data. But when we query lobid-organisation for the parentOrganisation and the id of the records, we could create a mapping for subOrganisations via triples.

**Comment by TobiasNx** [comment]
For now we have solved `parentOrganization`:
http://test.lobid.org/organisations/search?q=_exists_%3AparentOrganization&location=

http://test.lobid.org/organisations/DE-8-45.json
```
"parentOrganization": {
    "id": ["http://lobid.org/organisations/DE-8#!"](http://lobid.org/organisations/DE-8#!),
    "label": "Universitätsbibliothek Kiel, Zentralbibliothek"
  },
```

**Comment by acka47** [comment]
Nice. +1

**Comment by acka47** [comment]
I think, having the `parentOrganization` link is fine, as we can query for all orgs having a specific paren org to get a list of all sub organizations. Closing.
