### ISSUE TITLE
Classify DBS-derived organisations with libtype vocab

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#31]
Currently, all DBS-derivded institutions should be `rdf:type`d as `schema:Library`. For useful filtering  we will also need to differ acadamic from public libraries ia the`org:classification` with the [libtype](http://purl.org/lobid/libtype) vocabulary.

I already asked DBS to deliver a new csv dump with this information. As we heard yesterday it should be in column `fb` with value "0102" for public libraries (`libtype:n33`), "03" for academic libraries (`libtype:n60` :question: -> will find out whether non-university libraries also have this value) and "04" for Academic Special Library (`libtype:n81`).

**Comment by acka47** [comment]
I just found outh that the value "03" has different markers for university libraries and libraries of a univesity of applied science (Fachhochschule). As soon as we get this data we can incorporate into the RDF.

**Comment by philboeselager** [comment]
@acka47 Does the difference amongst universities and universities of applied sciences still prevent us from implementing on the basis as described above? ("0102" for public libraries, "03" for academic libraries, "04" for Academic Special Library)

**Comment by acka47** [comment]
As far as I know, column `fb` is missing in the data we have. I am still waiting for the updated csv list from the DBS colleagues and will inform you when it is ready. (Consequently, moving this to backlog.)

**Comment by acka47** [comment]
> As far as I know, column `fb` is missing in the data we have. 

I didn't look at the right file. The column is there but I am not sure whether the data is good enough to be merged with the Sigeldata.

**Comment by acka47** [comment]
The column is there, I just took a look at the wrong file. We decided to only include entries of "active" libraries, see #79. This is good, as only these have reliable information on the library classification.

We have three types of libraries in the current DBS csv: `WB`, `OEB` and `Spezbib`. How will we include this in the RDF?

1. We will always prefer the classification information from the Sigel registry as this is more granular (e.g. differing between university libraries and libraries of "Fachhochschulen").
2. `OEB` will be mapped to `http://purl.org/lobid/libtype#n33`.
3. `Spezbib` will be mapped to `http://purl.org/lobid/libtype#n81`.
4. `WB` won't be mapped at all. I suspect that nearly all of these are already in the ISIL registry anyway and, thus, classifying is covered there.

**Comment by fsteeg** [comment]
I've implemented this as described in https://github.com/hbz/lobid-organisations/issues/31#issuecomment-143684938, but when checking results on staging (and seeing that it basically makes no difference, just two additional ÖBs) I realized we already have much finer mapping to our `classification` field  based on the DBS `typ_text` column. Have a look at the classification facet for the DBS-only data: http://beta.lobid.org/organisations/search?q=%22http%3A%2F%2Fbeta.lobid.org%2Forganisations%2FDBS-*%22

This issue, and even https://github.com/hbz/lobid-organisations/issues/31#issuecomment-143684938 is rather old. Could this be obsolete due to subsequent data changes and the implementation based on `typ_text`?

**Comment by acka47** [comment]
> This issue, and even https://github.com/hbz/lobid-organisations/issues/31#issuecomment-143684938 is rather old. Could this be obsolete due to subsequent data changes and the implementation based on `typ_text`?

Maybe. I can't recall the implementation based on `typ_text` and wonb't find an issue for this. Anyway, i agree that the results are already satisfying and, thus, I am closing this issue.
