### ISSUE TITLE
DBpedia links are broken

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#318]
See e.g. http://lobid.org/organisations/DE-6?format=json:

```json
{
   "sameAs":[
      "http://dbpedia.org/resource/Universitäts-_und_Landesbibliothek_Münster"
   ]
}
```

Prepending subdomain `de` repairs the link, e.g. http://de.dbpedia.org/resource/Universitäts-_und_Landesbibliothek_Münster.

**Comment by acka47** [comment]
When we add wikidata links (#320), we should consider removing dbpedia links.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/organisations/DE-6?format=json

**Comment by acka47** [comment]
+1
