### ISSUE TITLE
Use hashbang URIs as org IDs 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#32]
In lobid-organisations 1.0  we use the [303 redirect approach](http://www.w3.org/TR/cooluris/#r303gendocument) to differentiate between a resource and its description. The result is that when I do a GET request on an organizations HTTP-URI, I get a 303 redirect to an RDF document describing the resource:

```
curl -i http://lobid.org/organisation/DE-605
HTTP/1.1 303 See Other
Date: Tue, 31 Mar 2015 13:03:48 GMT
Location: /organisation/DE-605/about
Content-Length: 0
Content-Type: text/plain
```

In this description I  – amongst others – can see the following triple:
`<http://lobid.org/organisation/DE-605/about>
      <http://xmlns.com/foaf/0.1/primaryTopic>
              <http://lobid.org/organisation/DE-605>. `

In lobid-organisations 2.0 the distinction between a resource and a document currently doesn't exist:

```
curl -i http://beta.lobid.org/organisations/DE-605
HTTP/1.1 200 OK
Date: Tue, 31 Mar 2015 13:10:28 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 1358

{
  "dbsID": "ZY571",
  "isil": "DE-605",
  "isPrimaryTopicOf": "http://dispatch.opac.d-nb.de/DB=1.2/CMD?ACT=SRCHA&IKT=8529&TRM=DE-605",
  "@context": "http://beta.lobid.org/organisations/context.jsonld",
  "type": "http://schema.org/Organization",
  "linkedTo": "http://lobid.org/organisation/DE-605",
  "rs": "053150000000",
  "name": "Nordrhein-westfälischer Bibliotheksverbund. Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen",
  "url": "http://www.hbz-nrw.de",
  "id": "http://beta.lobid.org/organisations/DE-605",
  "telephone": "0049 221 4 00 75-0",
  "email": "mailto:info-hbz@hbz-nrw.de",
  "address": {
    "postOfficeBoxNumber": "27 04 51",
    "addressLocality": "Köln",
    "type": "http://schema.org/PostalAddress",
    "addressCountry": "Germany",
    "postalCode": "50510"
  },
  "location": [{
      "type": "http://schema.org/Place",
      "address": {
        "type": "http://schema.org/PostalAddress",
        "addressCountry": "Germany",
        "postalCode": "50674",
        "streetAddress": "Jülicher Str. 6",
        "addressLocality": "Köln"
      },
      "geo": {
        "lat": "50.93410",
        "lon": "6.93549"
      }
    }],
  "classification": {"id": "http://purl.org/lobid/libtype#n96"},
  "fundertype": {
    "id": "http://purl.org/lobid/fundertype#n02",
    "value": "Land"
  },
  "stocksize": {
    "id": "http://purl.org/lobid/stocksize#n11",
    "value": "Zentrale ohne Bestand"
  },
  "alternateName": ["Köln HBZ"],
  "sameAs": ["http://ld.zdb-services.de/resource/organisations/DE-605"],
  "containedIn": "http://www.geonames.org/6553049",
  "ags": "5315000"
}
```

To have the possibility to add information on the description vs. the actual resource we should at least adjust the ID of each organisations, using the [hash URI approach](http://www.w3.org/TR/cooluris/#hashuri). I suggest using the hash bang (`#!`) as appendix. The result would be as follows (snippet):

```
curl -i http://beta.lobid.org/organisations/DE-605
HTTP/1.1 200 OK

{
  "id": "http://beta.lobid.org/organisations/DE-605#!",
  ...
}
```

When switching the beta to production and cutting of lobid-organisations 1.0, we will have to implement a redirect from 1.0 to 2.0 with HTTP status code 301, see also http://patterns.dataincubator.org/book/unpublish.html.

**Comment by philboeselager** [comment]
As far as I understand this description, the Definition Of Done (DOD) of this issue is:
- An URI-mechanism for the differentiation between a thing (organisation) and its describing document (website) is implemented by the means of a hash bang.
- 301 redirect from lobid-organisations 1.0 to lobid-organisations 2.0 is implemented.

Please confirm.

**Comment by acka47** [comment]
> As far as I understand this description, the Definition Of Done (DOD) of this issue is:
- An URI-mechanism for the differentiation between a thing (organisation) and its describing document (website) is implemented by the means of a hash bang.
- 301 redirect from lobid-organisations 1.0 to lobid-organisations 2.0 is implemented.

Confirming the first bullet point. The second has to be done when switching beta into production and will thus get its own ticket when we are at this point.
