### ISSUE TITLE
Change alternate name

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#322]
"Ein umfassendes Verzeichnis bibliothekarischer Institutionen" / "A comprehensive directory of German library institutions" don't take into account the many museum and the archives in the directory.

**Comment by acka47** [comment]
For the dataset description I chose "Gedächtnisinstitutionen im deutschsprachigen Raum" / Libraries, archives and museums in German-speaking countries", see  https://github.com/hbz/lobid-organisations/pull/317/commits/341e5539b68a38268344e2339592cb5c9fb52c0d. Ok?

**Comment by fsteeg** [comment]
Deployed (with general usage of the structured description in the index page as discussed offline):

http://test.lobid.org/organisations

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1
