### ISSUE TITLE
Use DE-38M again as example for annotation

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#326]
I just noticed that you switched the example JSON-LD file to the hbz entry. Unfortunately, the hbz is missing some fields so that we now have five "Orphans" (annotations where the text they refer to is gone) among our annotations, see http://lobid.org/organisations/api/de

**Comment by fsteeg** [comment]
Didn't change it on purpose, thought that was the example, deployed: http://lobid.org/organisations/api/de
