### ISSUE TITLE
Provide HTML views for organisation descriptions

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#33]
Currently, we only deliver JSON-LD, whichever format is requested in the content header of the HTTP request, e.g.:

```
curl -i -H "Accept: text/html"  http://beta.lobid.org/organisations/DE-605
HTTP/1.1 200 OK
Date: Tue, 31 Mar 2015 13:22:18 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 1358

{
  "dbsID": "ZY571",
  "isil": "DE-605",
  ...
}
```

We need to provide HTML views for people visiting lobid-organisations with a browser.

**Comment by fsteeg** [comment]
This seems like a natural starting point for #132.

As a first step, I think we should support an optional `format=html` query parameter (for browser usage, we can add actual content negotiation later), which renders an `organisation.scala.html` template, which is passed the organisation's JSON and basically renders it as a table.
