### ISSUE TITLE
Enable ISIL lookup with autosuggest

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#330]
It should be possible to lookup an ISIL via the API by typing a name and getting results as auto-suggest.

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/organisations/search?q=schnütgen&format=json:isil
http://stage.lobid.org/organisations/search?q=schnütgen&format=json:name
http://stage.lobid.org/organisations/search?q=schnütgen&format=json:name&callback=jsonp123

Will add documentation and sample usage as part of https://github.com/hbz/lobid/issues/329

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1
