### ISSUE TITLE
Link to Lucene Query Parser Syntax documentation

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#331]
As our API supports it, we should probably link to the [Apache Lucene - Query Parser Syntax documentation page](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html) somewhere in our documentation, shouldn't we?

**Comment by fsteeg** [comment]
Right, as mentioned in our blog post. Documentation for the version we currently use is at: https://lucene.apache.org/core/5_5_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#package_description

**Comment by acka47** [comment]
Sub-issue of https://github.com/hbz/lobid/issues/288.

**Comment by ChristophEwertowski** [comment]
Whoever writes the link to the Query Syntax page, please also correct the spelling mistake: "Um damit zu experimentieren können sie / **Sie** das JSON-LD[...]" under the headline JSON-LD. I don't won't to push an unnecessary commit for it.

**Comment by fsteeg** [comment]
Moved to https://github.com/hbz/lobid/issues/329
