### ISSUE TITLE
Replace daia:provides

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#333]
...as the property URI doesn't resolve anymore. Same problem as with `daia:label` in https://github.com/lobid/lodmill/issues/795.

**Comment by acka47** [comment]
The best fitting property from schema.org is http://schema.org/makesOffer. I am not sure whether we should go with it.

**Comment by fsteeg** [comment]
With the upcoming release, I think we should stop changing the JSON keys, and only update URIs in the context for cases like this (both here and in lobid-resources).

**Comment by acka47** [comment]
Also, `holding:CollectedBy` doesn't resolve anymore.

**Comment by acka47** [comment]
I will solve this by replacing `daia:provides` in the context using [`schema:provider`](http://schema.org/provider) with the `@reverse` keyword as follows:

```json
{
   "provides":{
      "@type":"@id",
      "@reverse":"http://schema.org/provider"
   }
}
```

See the [relevant part from the spec](https://www.w3.org/TR/json-ld/#reverse-properties) and an example in the JSON-LD playground at http://tinyurl.com/lqjuct6.
