### ISSUE TITLE
Search by linkedTo field doesn't work

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#337]
I can't make it work to search all institutions that are part of a specific library network, e.g. GBV (http://lobid.org/organisations/DE-601#!).

Generally, there seem to be 4883 institutions that are part of a network, see http://lobid.org/organisations/search?q=linkedTo:*. But how do I get all institutions associated with a specific network?

Following the escape rules from the [Apache lucene query parser](https://lucene.apache.org/core/5_5_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#package_description) doesn't work: http://lobid.org/organisations/search?q=linkedTo:http\:\/\/lobid.org\/organisations\/DE-601#!

Furthermore:
- http://lobid.org/organisations/search?q=linkedTo:%22DE-601%22 gives the same number of results
- http://lobid.org/organisations/search?q=linkedTo:%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-601%23!%22 doesn't work

Note: I have to adjust the documentation at  https://hypothes.is/a/8kCqmA8FEeetAcdUJkT8fw and https://hypothes.is/a/ghh5hg8JEeepzetbHJpOfA when this is solved.

**Comment by fsteeg** [comment]
Deployed to staging: `http://stage.lobid.org/organisations/search?q=linkedTo.id:http\:\/\/lobid.org\/organisations\/DE-601%23\!` (to test, copy and paste the link, neither plain link nor explicit Markdown link syntax leaves the link as it is).

**Comment by ChristophEwertowski** [comment]
The link worked but the links from the website don't work. The "#" has to replaced by "%23" see [link with # which doesn't work]() / [link with %23 which works](http://stage.lobid.org/organisations/search?location=&from=0&size=20&q=linkedTo.id:http\:\/\/lobid.org\/organisations\/DE-601%23\!+AND+collects.extent.label.en:%22300,001%20-%201,000,000%22). Otherwise +1

**Comment by fsteeg** [comment]
> The link worked but the links from the website don't work.

@ChristophEwertowski: Which links? From which website?

**Comment by fsteeg** [comment]
We discussed the issue offline, @ChristophEwertowski will open a separate issue for facet links with `#`.
