### ISSUE TITLE
Add label to library service center linked with "linkedTo"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#351]
Currently, it looks like this (from the API doc example):

```json
{
  "linkedTo" : "http://lobid.org/organisations/DE-605#!"
}
```

Following our general side-car approach, it should rather look something like this:

```json
{
   "linkedTo":{
      "id":"http://lobid.org/organisations/DE-605#!",
      "label":"Hochschulbibliothekszentrum des Landes NRW (hbz)"
   }
}
```

**Comment by acka47** [comment]
It makes sense to also fix #337 when implementing this.

**Comment by fsteeg** [comment]
Deployed to staging:

http://stage.lobid.org/organisations/DE-38?format=json
http://stage.lobid.org/organisations/DE-355?format=json

**Comment by ChristophEwertowski** [comment]
+1 for the added label. I unassign myself and will do the functional review for the linked ticket #337 there.
