### ISSUE TITLE
Problem with DE-30

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#355]
Reported via email on 2017-05-12:

> bei einem kurzen Test ist mir aufgefallen dass LOBID nicht alle ISIL auflöst.
>
> Beispiel:
>> http://lobid.org/organisations/DE-30
>> http://sigel.staatsbibliothek-berlin.de/nc/suche/?isil=DE-30

Here are the facts:
- DE-30 is the ISIL for Universitätsbibliothek J. C. Senckenberg, Zentralbibliothek (ZB) 
- There is no entry  http://lobid.org/organisations/DE-30 in lobid
- The ISIL DE-30 is associated with this entry in lobid-organisations: http://lobid.org/organisations/DE-F21 which combines data from DE-30 and DE-F21  
- In the ISIL registry both [DE-30](http://sigel.staatsbibliothek-berlin.de/nc/suche/?isil=DE-30) and [DE-F21](http://sigel.staatsbibliothek-berlin.de/nc/suche/?isil=DE-F21) have the associated DBS ID "AC030" (which – looking at the DBS data – actually stands for DE-30). 

Thus, this is an error in the ISIL registry and I will ask them to remove "AC030" from DE-F21. 

Anyway, we decided to not have an array for the "isil" field in lobid as each institution only can have on isil. We should investigate whether there are other incorrect cases with two ISILs and correct them if needed.

**Comment by acka47** [comment]
[DE-F21](http://sigel.staatsbibliothek-berlin.de/nc/suche/?isil=DE-F21) is now corrected in the ISIL registry and the correct data should be in lobid-organisations tomorrow.

**Comment by fsteeg** [comment]
Fixed by the data update: http://lobid.org/organisations/DE-30

**Comment by acka47** [comment]
Closing.
