### ISSUE TITLE
DBS-URI not working if parallel ISIL exists

### ISSUE THREAD

**Issue by nichtich** [hbz/lobid-organisations#356]
[Proposing a Wikidata property to map libraries via DBS-ID](https://www.wikidata.org/wiki/Wikidata:Property_proposal/DBS_ID) I stumbled upon this: libraries without ISIL can be looked up via URI based on their DBS-ID, e.g. http://lobid.org/organisations/DBS-LE289. Libraries with ISIL have another URI (so the URI will change if an ISIL is added, right?). For instance https://lobid.org/organisations/DE-285. The latter also has DBS-ID AL285 but http://lobid.org/organisations/DBS-AL285 does not resolve. I would expect it to redirect to https://lobid.org/organisations/DE-285. This is required to link to a library via its DBS-ID independently from parallel existence of ISIL.

**Comment by acka47** [comment]
Thanks for the input, @nichtich. I also noticed that we get problems when a library which formerly only had a DBS ID gets an ISIL. As you say, the DBS ID-based URI wouldn't resolve anymore. Redirects would solve this problem. We will look into setting this up.

(Another way to solve the linking problem from Wikidata could be to directly got to the resource when it is the only on a result list. Then you could use http://lobid.org/organisations/search?q=dbsID:AL285 for the links. But this would not solve the other problems with DBS URIs that don't resolve anymore.)

**Comment by fsteeg** [comment]
Deployed to staging:

http://stage.lobid.org/organisations/DBS-AB038 (has ISIL, redirect)
http://stage.lobid.org/organisations/DBS-AT700 (no ISIL, no redirect)

**Comment by acka47** [comment]
+1
