### ISSUE TITLE
Set up Pelias locally

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#357]
Since our usage of Mapzen won't be free any longer starting next month, we should set up Pelias on our own infrastructure:

https://github.com/pelias/pelias
http://pelias.io/install.html

**Comment by acka47** [comment]
@literarymachine just told me that he caches the Mapzen lookups. Don't we use caching for the lookups? If not, this would probably be another approach to handle this.

**Comment by fsteeg** [comment]
Yes, @dr0i also brought up that option today when we talked about this. The caching would have to be persistent, so we'd have to build something for that (if we'd just use the Play cache we'd be sending all requests again after restarting the Play app).

Also, we'd still rely on the Mapzen service. If they change their terms again, or shut down parts of their service we'd have the same problem again. Also our number of requests will increase when we add geo lookups for lobid-resources.

And things that require lots of requests would just not be possible in general, like experimenting with what's sent to the service for lookups, e.g. adding some data, like a postal code, since it would change all requests (we did that a lot when implementing the current lookups to tweak results).

So overall, I think running our own Pelias server is the more sustainable approach.

**Comment by dr0i** [comment]
After [help from pelias developer](https://github.com/pelias/pelias/issues/579) the basic functionality should work, try http://weywot3.hbz-nrw.de:3100/v1/search?text=bonn (works only within hbz network). 
*Germany* and *Austria* are covered -  *Swiss* is missing because the [dataset comprises only *European Union* members](http://publications.europa.eu/code/pdf/370000en.htm). 
Let me know if the data is sufficient. If not, we may complement it by adding other datasets.

**Comment by fsteeg** [comment]
Server was down, restarted with `hduser@weywot3:~/git/api$ nohup npm start &`

http://weywot3.hbz-nrw.de:3100/v1/search?text=bonn

**Comment by acka47** [comment]
Re. the dataset. We currently have only [29 organisations from Switzerland](http://lobid.org/organisations/search?q=location.address.addressCountry:CH) in lobid-organisations, so I don't think we necessarily need it covered. However, OER World Map also uses the Mapzen API @literarymachine has shown interest in a hbz-hosted Pelias instance. If the service is also to be used by the world map, we will need world-wide coverage. /cc @philboeselager

**Comment by fsteeg** [comment]
The data doesn't seem to work for our use case, the OpenAddresses data is not good enough, see:

https://search.mapzen.com/v1/search?text=Burgstra%C3%9Fe%202,%2094350%20Falkenfels
http://weywot3.hbz-nrw.de:3100/v1/search?text=Burgstra%C3%9Fe%202,%2094350%20Falkenfels

The good result actually comes from `"source": "openstreetmap"`, not `"source": "openaddresses"`.

So we'll have to look into adding OpenStreetMap data (see http://pelias.io/install.html#openstreetmap). 

Single `osm.pbf` files for Germany, Austria, and Switzerland are available here: http://download.geofabrik.de/europe.html. When our servers are upgraded with more RAM, we might consider adding more data for use cases mentioned by @acka47 in https://github.com/hbz/lobid-organisations/issues/357#issuecomment-303645644.

**Comment by dr0i** [comment]
Indexed the osm data. See http://weywot3.hbz-nrw.de:3100/v1/search?text=Burgstra%C3%9Fe%202,%2094350%20Falkenfels. Is this suffcient now?
(btw, your mapzen-query doesn't seem to work (anymore).

**Comment by fsteeg** [comment]
Deployed to staging, results are comparable:

[http://test.lobid.org/organisations/search?q=location.geo:*](http://test.lobid.org/organisations/search?q=location.geo:*)
[http://lobid.org/organisations/search?q=location.geo:*](http://lobid.org/organisations/search?q=location.geo:*)

**Comment by acka47** [comment]
+1 I found on example where the result even was better. I am curious: How often is the OSM data updated in the pelias instance?

**Comment by dr0i** [comment]
re update: no updates planned so far. Would be a new issue?

**Comment by acka47** [comment]
FYI, Mapzen will shut down at the end of January, see https://mapzen.com/blog/shutdown/. It's good to already have our own Pelias server running.
