### ISSUE TITLE
Rank entries with "früher:" in their name lowest 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#360]
All deleted ISIL entries (see also #76 ) should be shown at the end of a result list as they currently seem to be shown mostly on top of the list see e.g. http://lobid.org/organisations/search?q=universit%C3%A4tsbibliothek. For now they can be detected by a "früher:" in the name field.

**Comment by acka47** [comment]
These entries can also be identified by the missing `type` information, see https://lobid.org/organisations/search?q=_missing_:type.

**Comment by fsteeg** [comment]
Deployed to staging.

Proposed fix is to simply not include organisations with missing `type` in search results at all:

http://stage.lobid.org/organisations/search?q=universit%C3%A4tsbibliothek

They remain accessible directly:

http://stage.lobid.org/organisations/DE-26-060

**Comment by acka47** [comment]
+1 I like this solution very much. The deleted entries were definitely polluting the result list.
