### ISSUE TITLE
Add GND links

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#361]
Some of the organisations in lobid also have a GND entry. We should add the GND URI with sameAs where it exists.

I already made some work on this which can be improved, though. 

1. Getting all sub-terms of "Library" from the GND: https://github.com/hbz/lobid-organisations/wiki/GND-Schlagw%C3%B6rter-f%C3%BCr-bibliothekarische-Einrichtungen
2. Get a list of libraries (not terminated ones) within the GND (based on 1.): https://gist.github.com/acka47/312c81a453b89e908614b7c813967cd8
3. Run the list from 2.) against the lobid-organisations reconciliation endpoint.

I also did 3.) that but wasn't very satisfied with the [result](https://gist.github.com/acka47/3b56420e061b08dc05ed6c69c5b715f5) although I did a lot of manual matching in the end. This may due to my only partial knowledge of Open Refine...

**Comment by TobiasNx** [comment]
I am not that good with sparql but wikidata has a lot of entries with dbs-id and isil, we could use wikidata to match them with the gnd.

**Comment by acka47** [comment]
Here is a Wikidata query that provides, QID, label, ISIL and GND ID. You can also download the result as tsv. Maybe we should add this query into the proces somehwere so that we won't have to update the mapping manually. We do similar things for example in Wikidata...

**Comment by acka47** [comment]
We already have Wikidata links in the JSON, see e.g. https://lobid.org/organisations/DE-101b. I am not sure how these are currently added. We should watch out to not implement parallel wikidata enrichment processes.

**Comment by TobiasNx** [comment]
This looks good. Can you also add institutions that have dbs_id but no isil?

There are some, but not many: https://w.wiki/72GG

**Comment by acka47** [comment]
Voilà: https://w.wiki/72GW

**Comment by TobiasNx** [comment]
yes we have a wikidata <-> isil mapping here: https://github.com/hbz/lobid-organisations/blob/useFixInsteadOfMorph/conf/isil2wikidata.csv

If we would have a map wikidataId, name, isil, dbs-id, gnd-id for all entries that have isil and/or dbs id. I could use this mapping  easily and would not have multiple mapping files.

**Comment by TobiasNx** [comment]
@acka47 one difference i spot between the old list and your new one is isil <-> wikidata has +11.000 entries and your new one has 3.000 entries

**Comment by acka47** [comment]
> one difference i spot between the old list and your new one is isil <-> wikidata has +11.000 entries and your new one has 3.000 entries

Yes, I did not do it right. Investigating.

**Comment by acka47** [comment]
Hm, it was correct in so far that I queried for entries that have a GND ID (which was the goal of this ticket). But by now we want a general that contains:

1. all Wikidata entries with an ISIL *or* a DBS ID
2. the GND ID if existing in Wikidata.

Here is the query for that: https://w.wiki/72Gx

**Comment by TobiasNx** [comment]
http://test.lobid.org/organisations/CH-000004-7.json

```
"gndIdentifier": "2023655-4",
....
"sameAs": [
   [ "http://www.wikidata.org/entity/Q683842"](http://www.wikidata.org/entity/Q683842),
    ["https://lobid.org/gnd/2023655-4#!"](https://lobid.org/gnd/2023655-4#!),
    ["https://ld.zdb-services.de/resource/organisations/CH-000004-7"](https://ld.zdb-services.de/resource/organisations/CH-000004-7)
  ]
```

**Comment by acka47** [comment]
Nice. +1

**Comment by acka47** [comment]
Ah, just noticed the `sameAs` statement for lobid-gnd. We did not want to mint new URIs with lobid-gnd and use the d-nb.info URIs in the RDF/JSON-LD ourselves. So we should also do it here, meaning in the concrete example: `https://lobid.org/gnd/2023655-4#!` -> `https://d-nb.info/gnd/2023655-4`

**Comment by TobiasNx** [comment]
```
 "sameAs": [
    "http://www.wikidata.org/entity/Q683842",
    "https://d-nb.info/gnd/2023655-4",
    "https://ld.zdb-services.de/resource/organisations/CH-000004-7"
  ]
```
Changed the URI.

**Comment by TobiasNx** [comment]
This should be added the link to GND to the GUI too. 
Next to the Wikidata link/icon.
@fsteeg

**Comment by TobiasNx** [comment]
#497
