### ISSUE TITLE
Script error in Firefox

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#364]
When unchecking "In Ihrer Nähe" in "Entdecken" mode. See https://youtu.be/iKYJtL0VjH0?t=8m56s.

I used Firefox 53.0.2 on Linux Mint 17.1 Cinnamon 64bit

**Comment by acka47** [comment]
I can not recreate the bug. Maybe we should already close this...

**Comment by fsteeg** [comment]
Works for me too, same browser, closing.
