### ISSUE TITLE
Show sameAs links in HTML view, especially to Wikidata

### ISSUE THREAD

**Issue by nichtich** [hbz/lobid-organisations#370]
I miss at least an icon to click on for instance from <https://lobid.org/organisations/DE-MUS-113319> to <http://www.wikidata.org/entity/Q1013521> and to GND if available (#361). This may be related to #348 but a link should be enough to start with.

**Comment by acka47** [comment]
+1 I think we should add a row above the description table where we put logos of the services link to (with the underlying sameAs link) using https://commons.wikimedia.org/wiki/File:Wikidata-logo-en.svg for wikidata. (We can then add GND, twitter, GitHub etc. in the future).

**Comment by nichtich** [comment]
There is also https://commons.wikimedia.org/wiki/File:Wikidata-logo.svg without "Wikidata" text to get a smaller logo.

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/organisations/DE-MUS-113319

**Comment by acka47** [comment]
+1
