### ISSUE TITLE
DE-43 is missing

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#379]
Reported today via mail by @jochen-lienhard.

E.g. http://lobid.org/organisations/DE-43 doesn't exist in 2.0, although it exists in 1.0, see http://lobid.org/organisation/DE-43 (and the [entry in the Sigelverzeichnis itself](http://ld.zdb-services.de/resource/organisations/DE-43)).

**Comment by dr0i** [comment]
Hm, though it exists in the source directory:

-rw-r--r-- 1 sol sol 3813 Sep  8 05:06 /tmp/lobid-organisations/DE/DE-43.xml

Will see if the resolving of #373 which results in improved logging will come up with something. Else I could imagine that the dbs ID was prioritized? Last exit is a complete debug.

**Comment by dr0i** [comment]
@acka47 just to be sure, DE-43 is not sameAs to http://lobid.org/organisations/DBS-XY213, right?

**Comment by acka47** [comment]
No, it isn't.

**Comment by acka47** [comment]
I am curious how many other ISIL resources are actually missing. We should compare a direct query against the index for the ISIL field with the number of records in the ISIL SRU export. (We need to directly query the index because eresource packags (#207) and deleted entries (#360) aren't queried using the web API.) Can you do this, @dr0i?

**Comment by dr0i** [comment]
Queried the local ES index like this: `sol@quaoar1:~/git/lobid-organisations$ curl localhost:7210/organisations/_search?q=isil:"DE-43"|json_pp ` and got this:

 >            
               "dbsID" : "DG557",
               "rs" : "064140000000",
               "isil" : [
                  "DE-43",
                  "DE-43-0",
                  "DE-969"
               ],
               "_id" : "DE-969",

The `_id` is what is looked up when using the PURL.
@acka47 yes I can - and you can too! I am willing to help when you try out your scripting abilities in real life :)  Also, try this url-template for querying all fields instead of just the internal `_id` one:
http://lobid.org/organisations/search?q=isil:DE-43

**Comment by acka47** [comment]
Ok, this is another mistake introduced by the DBS data where "Hochschul-und Landesbibliothek RheinMain" (still?) has DE-969 as ISIL.

**Comment by acka47** [comment]
I updates the dbs.csv and uploaded it to weywot2. @dr0i initiated a new transformation but it seems like the transformation and reboot of the staging server didn't work, see http://staging.lobid.org/organisations/DE-43. We'll have to check this on Monday.

**Comment by dr0i** [comment]
Well, works now fine. The `dbs.zip` must be unzipped manually to have a dbs.csv. 
re #373 Bringing something up to work nothing's more worthwile than working logging :)
Restarted production, try http://lobid.org/organisations/DE-43.
(took around 1 hour to start, should be quickened IMHO).

**Comment by acka47** [comment]
Nice. So transformation and indexing only took more time than I expected. Closing.

**Comment by acka47** [comment]
I just noticed that now the address is wrong, compare http://lobid.org/organisations/DE-43 and http://sigel.staatsbibliothek-berlin.de/nc/suche/?isil=DE-43. This will probably be fixed by #41, leaving this one open to check after #41 is done.

**Comment by jochen-lienhard** [comment]
I detected another isil that works in 1.x but not in 2.x.
DE-25-99
I will post, when we find more, that do not work.

**Comment by acka47** [comment]
Thanks for the report. Due to old DBS data this institution is under the incorrect URL with an old name: http://lobid.org/organisations/DE-Frei99 I will update the DBS data and we will soon implement #41 so that URIs for Sigel libraries are always generated from ISIL data only.

**Comment by acka47** [comment]
[DE-43-0](http://sigel.staatsbibliothek-berlin.de/nc/suche/?isil=DE-43-0) is also missing in lobid, see http://lobid.org/organisations/DE-43-0. This is probably due to the fact that noth DE-43 and DE-43-0 have the same DBS ID ("DG557") in the Sigel registry. I will talk about this with the DBS colleagues and propose a correction for the ISIL data afterwards.

**Comment by acka47** [comment]
Fixed with #41. 

http://lobid.org/organisations/DE-43
http://lobid.org/organisations/DE-43-0
http://lobid.org/organisations/DE-25-99

Closing.
