### ISSUE TITLE
Fields remain when not overwritten by update

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#38]
See e.g. http://beta.lobid.org/organisations/DE-1393-BOT. It still contains `"postOfficeBoxNumber": "10 07 55"` though this information is not in the up-to-date source data (see [here](http://sigel.staatsbibliothek-berlin.de/suche/?isil=DE-1393-BOT)). Obvioulsy, this filed wasn't deleted though when the update was transformed and indexed.

**Comment by dr0i** [comment]
Problem still exists.

**Comment by philboeselager** [comment]
No, it has not been rolled out, yet - as I wanted to wait for the code review first.

**Comment by dr0i** [comment]
I mean rolled out to a staging (aka testing) system, so that one can confirm that the issue raised here ( `postOfficeBoxNumber` http://beta.lobid.org/organisations/DE-1393-BOT) is solved with the new code.
(For this we have e.g. test.lobid.org vs lobid.org).

**Comment by fsteeg** [comment]
Reopening, fix is not deployed, corresponding pull request (https://github.com/hbz/lobid-organisations/pull/42) not merged.

**Comment by philboeselager** [comment]
Rolled out to staging: http://test.lobid.org/organisations/DE-1393-BOT

**Comment by acka47** [comment]
+1

**Comment by philboeselager** [comment]
Deployed to beta. Closing.
