### ISSUE TITLE
Can't find out provenance of DE-Frei99 (should now be DE-25-99)

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#381]
The general question I can not answer is: Where does the data that was used for creating http://lobid.org/organisations/DE-Frei99 come from? 

In https://github.com/hbz/lobid-organisations/issues/379#issuecomment-328432799 it was reported that DE-25-99 is missing in 2.0 but is there in 1.x, see http://lobid.org/organisation/DE-25-99/about vs. http://lobid.org/organisations/DE-25-99.

In https://github.com/hbz/lobid-organisations/issues/379#issuecomment-328434049 I assumed that DE-25-99 would be missing because of outdated DBS data and that the dbs.csv would have an entry with ISIL DE-Frei99 and DBS ID "DA701". But as I searched the DBS file we use for the transformation, I could neither find the DBS ID "DA701", nor the name ("Volksliedarchiv") or the street address ("Rosastraße").

This is really weird. I can't explain why the entry http://lobid.org/organisations/DE-Frei99 is actually there and where the data is coming from. What am I overlooking?

**Comment by acka47** [comment]
Maybe this will be fixed with a new DBS update ( #94 ).

**Comment by acka47** [comment]
This is still weird. There exists a form for changing the entry (https://sigel.staatsbibliothek-berlin.de/aenderungen-mitteilen/?isil=DE-Frei99) but the entry can not be viewed in the browser, see https://ld.zdb-services.de/resource/organisations/DE-Frei99 and I suspect that we are also getting the entry via OAI-PMH.

Maybe @cKlee can shed some light on the question: Why is https://ld.zdb-services.de/resource/organisations/DE-Frei99 hidden?

**Comment by cKlee** [comment]
Yep, that's weird. It happens because the record for DE-Frei99 (Deutsches Volksliedarchiv) does not exist. But the ISIL is indexed through record of DE-25-99. The non-existance of DE-Frei99 makes DE-25-99 appear (wrongly) in the form.

I guess my colleque will fix this by creating an (inactive) ISIL-record.

**Comment by acka47** [comment]
Thanks @cklee, that clarifies at least one question. But wrt this issue, I still don't know where Bibliotheken haben sie nicht auf dem Schirm. Community of Practice als Fachredaktion. Ziel ist es, das zu verstetigen.
is coming from. I will take a look at the DBS in another five years. ;-)

**Comment by cKlee** [comment]
The Deutsches Volksliedarchiv changed it's name an ISIL in 2014. I guess it was just overwritten in the record instead of creating a new one.

**Comment by cKlee** [comment]
@acka47 Can U delete the record?

**Comment by acka47** [comment]
> Can U delete the record?

As far as I know we are rebuilding from scratch regularly (right, @fsteeg 
?) so deleting will not resolve the problem.

**Comment by cKlee** [comment]
> As far as I know we are rebuilding from scratch regularly (right, @fsteeg?) so deleting will not resolve the problem.

Then the existence of DE-Frei99 is truly a mysterium.

**Comment by fsteeg** [comment]
> As far as I know we are rebuilding from scratch regularly (right, @fsteeg?)

Yes, I've attached what seems to be today's data we're getting via OAI-PMH (metadataPrefix: `PicaPlus-xml`, set: `bib`) for DE-Frei99: [DE-Frei99.xml.txt](https://github.com/hbz/lobid-organisations/files/9597388/DE-Frei99.xml.txt). We seem to be getting updates since 2013 though, so it might be the record from before it changed its name? Perhaps this would be fixed by switching to a newer base dump? (Ours seems to be a OAI-PMH response from 2013, but re-creating that via OAI-PMH ourselves should not solve the issue, as it would be the same data we're currently using.)

**Comment by acka47** [comment]
> Perhaps this would be fixed by switching to a newer base dump? (Ours seems to be a OAI-PMH response from 2013, but re-creating that via OAI-PMH ourselves should not solve the issue, as it would be the same data we're currently using.)

Sounds like we should schedule using a new base dump. I guess we would have to also load a base dump via OAI-PMH. Or can we get a PicaPlus dump anywhere, @cKlee ?

**Comment by TobiasNx** [comment]
@cKlee anyway to get a PicaPlus dump anywhere besides the OAI-PMH?

**Comment by cKlee** [comment]
@TobiasNx schreib mal bitte an isil(at)sbb.spk-berlin.de

**Comment by TobiasNx** [comment]
This issue will probably be fixed with #462

**Comment by TobiasNx** [comment]
This does not exist anymore with the new sigil process: http://test.lobid.org/organisations/DE-Frei99 does not exist anymore.

**Comment by TobiasNx** [comment]
The mystery is solved: http://lobid.org/organisations/DE-Frei99 

@cKlee and @acka47 
It is removed thanks to the new dump.
