### ISSUE TITLE
Add wikidata links for libraries with DBS ID only and no ISIL

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#383]
Currently there are only four libraries with DBS ID and without ISIL, see http://tinyurl.com/yahst2xp.

**Comment by TobiasNx** [comment]
This can be solved with aa7ec766a02f0e06783ad101d44c3cdc8c4e1688

**Comment by TobiasNx** [comment]
It seems that the example is not working yet, maybe it is when #482 is productive.

**Comment by TobiasNx** [comment]
The issue wasn't the updated wikidata file but a typo.

**Comment by TobiasNx** [comment]
No this is not true!!! 

The reason why we index DBS is to get institutions that are not registered in the ISIL registry. It seems that we the indexing of DBS did not work. Will open a ticket.

**Comment by TobiasNx** [comment]
http://lobid.org/organisations/DBS-AC213
