### ISSUE TITLE
Problems with reconciliation endpoint

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#385]
Talking with @literarymachine today about an import for CRG, we noticed that the reconciliation endpoint has two problems:

1. Running reconciliation on the name column of the customer list from EDB, obviously identical strings aren't matched, e.g. "Universitätsbibliothek der RWTH Aachen":

![reconciliation-problem](https://user-images.githubusercontent.com/160292/30481896-22394b96-9a21-11e7-8185-2874ebcdfa3d.png)

2. As you can see, no matches are automatically added but have to be confirmed. Usually matches are added automatically in open refine, see e.g. this result of reconciliating with the OEr WOrld Map endpoint.This may have something to do with the match score lobid returns.

**Comment by fsteeg** [comment]
Deployed to stage, reconcile with `http://stage.lobid.org/organisations/reconcile`.

**Comment by literarymachine** [comment]
> Running reconciliation on the name column of the customer list from EDB, obviously identical strings aren't matched, e.g. "Universitätsbibliothek der RWTH Aachen"

Resolved, thanks!

> As you can see, no matches are automatically added but have to be confirmed. Usually matches are added automatically in open refine, see e.g. this result of reconciliating with the OEr WOrld Map endpoint.This may have something to do with the match score lobid returns.

In case of the automatic matching, still only 25% are reached, but I reckon that this is due to the input data / the OpenRefine probability threshold.

All in all, +1

**Comment by acka47** [comment]
Looks much better, +1. @literarymachine, let us know if you see any further problems.

**Comment by acka47** [comment]
I just noticed another problem. The reconciliation endpoint also entries deleted from Sigel registry (with "früher: " in their name) which we decided to remove from the regular query, see #360. It would be good if they were also removed from reconicliation.

**Comment by fsteeg** [comment]
Deployed to production including fix for deleted entries, closing.

Reconcile with `http://lobid.org/organisations/reconcile`
