### ISSUE TITLE
Two entries with identical DBS IDs

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#398]
See http://lobid.org/organisations/DBS-GK708 & http://lobid.org/organisations/DE-933. Both have the value "GK708" in field `dbsID`.I would assume that this is enough to only have one entry and to redirect the first URL to the second.

Obviously, the deduplication process doesn't work like that. Is it currently necessary to have the ISIL in the DBS entry so that you only get one entry?

**Comment by acka47** [comment]
This problem seems to be the same as in #358 .

**Comment by nichtich** [comment]
And another one: <https://lobid.org/organisations/DBS-LC086> and <https://lobid.org/organisations/DE-903>

**Comment by acka47** [comment]
This is resolved now. DBS-ID-based URIs rediurect to the ISIL-based ones, so apparently the entries are merged now (as one would expect):

```
$ curl -I http://lobid.org/organisations/DBS-GK708
HTTP/1.1 301 Moved Permanently
Date: Fri, 17 Dec 2021 07:23:18 GMT
Server: Apache/2.4.10 (Linux/SUSE)
Access-Control-Allow-Origin: *
Content-Language: de
Location: /organisations/DE-933
```

```
$ curl -I https://lobid.org/organisations/DBS-LC086
HTTP/1.1 301 Moved Permanently
Date: Fri, 17 Dec 2021 07:23:50 GMT
Server: Apache/2.4.10 (Linux/SUSE)
Access-Control-Allow-Origin: *
Content-Language: de
Location: /organisations/DE-903
```

Closing.
