### ISSUE TITLE
Sorting after location doesn't work

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-organisations#403]
If I search for ["Universitätsbibliothek"](http://lobid.org/organisations/search?q=Universit%C3%A4tsbibliothek&location=) I don't only get libraries from the Rhine area in the first results but from Switzerland and Austria. "Standortabfrage" is allowed.

**Comment by acka47** [comment]
It seems to only work with institutions nearby (in the same city). A [query for "museum"](http://lobid.org/organisations/search?q=museum) looks good.
