### ISSUE TITLE
Always choose Sigel data in favor of DBS data

### ISSUE THREAD

**Issue by philboeselager** [hbz/lobid-organisations#41]
When Sigel and DBS records are merged, it is currently unpredictable which fields of the resulting output are of Sigel origin and which are of DBS origin.
We should aim to determine which data source is preferred. If we agree to generally favor Sigel data, a possible way to solve is issue could be:
- ensure, DBS data is put into the pipe before Sigel data.
- implement the TripleSort class to keep the order of triples if they contain the same subject and predicate.

**Comment by acka47** [comment]
> We should aim to determine which data source is preferred. If we agree to generally favor Sigel data,

+1 for favor Sigel data.

Benefits form Sigel over DBS data:
- Most of the time Sigel data will be more up to date than DBS data.
- If Sigel data isn't up to data it can be updated at any time and not only once a year (as DBS data).
- Corrections can be [proposed](http://sigel.staatsbibliothek-berlin.de/aenderungen-mitteilen/) by anybody not only by specific contact persons in the respective institution.

**Comment by acka47** [comment]
Is this already implemented?

**Comment by acka47** [comment]
Closing, as we don't want always want to choose SIgel over DBS for every field. An exception is `rs` for example.

**Comment by acka47** [comment]
Reopening this as for several reasons we should implement this even if DBS data for some fields may be more reliable.

- It would make it easier to say from which source a specifc information is coming.
- Currently, it is quite confusing that e.g. the `name` information (sometimes? always?) is coming from DBS data, see e.g. the [hbz entry](http://test.lobid.org/organisations/DE-605). When people try to correct it in the Sigel registry as we suggest ("Änderungen zu diesem Eintrag im Sigelverzeichnis mitteilen.") they see that the name is already correct (and different) there.
- For the upcoming development of a hbz customer registry this is a first step of preparing for data synching between different systems.

**Comment by acka47** [comment]
When a record is "deleted" in the ISIL registry, we shouldn't take any data from DBS for the entry, see e.g. #354 .

**Comment by ChristophEwertowski** [comment]
Setting up lobid-organisations locally doesn't work. Activator test runs through but `~/activator-1.3.10-minimal/bin/activator run` leads to an endless debug (at least I think so, I will let it run until a while longer). At the beginning there were HTTP status codes 200 so weywot3 seems to answer the calls.

**Comment by acka47** [comment]
#379 shows that the current merging process doesn't make a lot of sense. We even pull the ISIL that is used to generate the URI for a resource from the DBS data. We should at least soon change the preference for this field to take the ISIL from sigel data.

**Comment by acka47** [comment]
I don't think that this is fixed by changing the morph files. My guess is that we have to change the order in https://github.com/hbz/lobid-organisations/blob/976371c2b8db1bf9fc0ee2e3cdd620e049bbf706/app/transformation/Enrich.java#L84-L108 but I may as well be wrong.

**Comment by fsteeg** [comment]
Discussed offline with @acka47: It probably makes sense not to merge individual records at all. Instead, we'll take the full data from the Sigel registry and use DBS only for records not present in the Sigel registry. This will also make the provenance much clearer: every record is taken completely from either the Sigel registry or the DBS, and can link to the original data, and the transformation used.

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/organisations

**Comment by acka47** [comment]
+1. There are >1000 resources more on staging than on production!

Deploying this will also fix the following issues: 

- #379 
- #376 (both the ISIL-based and the DBS-ID-based link work) 

#381 is fixed in part as http://staging.lobid.org/organisations/DE-25-99 is there (while http://lobid.org/organisations/DE-25-99 is not)
