### ISSUE TITLE
Add sigel to data

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#411]
We right now have to map sigel to ISIL in https://github.com/hbz/lobid-resources/issues/907. If others have to do similar things it would be good to have sigel in lobid-organisations to look up the corresponding ISIL easily.

The sigel is in `008H`, subfield `d` see e.g. https://services.dnb.de/sru/bib?operation=searchRetrieve&query=isl%3DDE-605&recordSchema=PicaPlus-xml&version=1.1:

```xml
<ppxml:tag id="008H" occ="">
  <ppxml:subf id="b">ZY571</ppxml:subf>
  <ppxml:subf id="d">605</ppxml:subf>
  <ppxml:subf id="e">DE-605</ppxml:subf>
</ppxml:tag>
```

**Comment by TobiasNx** [comment]
see here: http://test.lobid.org/organisations/DE-605.json

```
"sigel": "605",
```
We should add this to the GUI, too.

**Comment by acka47** [comment]
+1 

> We should add this to the GUI, too.

I am not sure we need this. For me it's ok to only have it in the JSON for now.

**Comment by TobiasNx** [comment]
see here: http://lobid.org/organisations/DE-605.json
> 
> ```
> "sigel": "605",
> ```

deployed with #450
