### ISSUE TITLE
Nicht öffentliche Adressen werden angezeigt

### ISSUE THREAD

**Issue by cKlee** [hbz/lobid-organisations#416]
In den Adressdaten der ISIL-/Sigelstelle (PICA+ 032P) gibt es ein Unterfeld $p, welches entweder mit dem Wert 'j' (Adresse darf öffentlich angezeigt werden) oder 'n' (Adresse darf nicht öffentlich angezeigt werden) belegt ist.

Leider berücksichtig ihr diesen Kontext nicht. z.B.

http://lobid.org/organisations/ZDB-Test2.json

"Das ist die Testanschrift, Testanschriftneu, Diese Anschrift darf nicht angezeicht werden, Geheimanschriftneu"

Wir versuchen, mit den Daten der Institutionen vertrauensvoll umzugehen und möchten euch bitten, das ebenfalls zu tun.

Gruß,

Carsten

**Comment by acka47** [comment]
Danke für den Hinweis, Carsten. Wir werden das möglichst bald korrigieren.

**Comment by cKlee** [comment]
Hat sich erledigt. Danke!
