### ISSUE TITLE
Geo lookup is broken

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#419]
For example, all entries that come from the DBS have no geo coordinates, see https://lobid.org/organisations/search?q=_exists_%3AdbsID+AND+NOT+_exists_%3Aisil+AND+_exists_%3Alocation.geo

The problem is that the pelias index is missing from aither, see https://github.com/hbz/nwbib/issues/463#issuecomment-483169183.

To do: 
- [x] Fix index
- [x] adjust API URL in lobid-organisations if necessary
- [ ] add tests for geo lookup so that we from now on learn of such a problem with the pelias index directly

**Comment by dr0i** [comment]
The old installation is way too outdated and thus I decided not to fix the old one but to install a new one based on docker. Experienced an issue and [opened a PR](https://github.com/pelias/docker/pull/94).

**Comment by dr0i** [comment]
Set up Pelias as docker containers at `lod@gaia:pelias/projects/lobid_DACH`. Test like http://gaia.hbz-nrw.de:4000/v1/search?text=berlin . Not sure if all the data/functionality is good, though. Going to reconfigure and restart organisations-test to see the outcome.

**Comment by dr0i** [comment]
https://stage.lobid.org/organisations/search?q=_exists_%3AdbsID+AND+NOT+_exists_%3Aisil+AND+_exists_%3Alocation.geo now result in ~700. But is this suffcient? [Querying missing geo location data](https://stage.lobid.org/organisations/search?q=_exists_%3AdbsID+AND+NOT+_exists_%3Aisil+AND+NOT+_exists_%3Alocation.geo) result in around 10 times more documents.

**Comment by acka47** [comment]
No, that is not sufficient. Although I don't know the numbers from the last time Pelias was running, I am quite sure there must be a problem somewhere.

**Comment by dr0i** [comment]
There was  the polylines data missing. Also, the `whosonfirst` filenames of the data had to be renamed to be taken into account. After `pelias compose down; pelias compose up` and reindexing lobid-organisations there are ~5k dbsIDs with a geo location, but still 3k without. Still have to dig a bit deeper to get the proper data I guess.

**Comment by dr0i** [comment]
In https://github.com/hbz/lobid-organisations/issues/89 it is stated that ~1.2k are without geo data. So now we have 1.8k less than before.  Discussed with @acka47: we will leave it as it is until someone is asking for improvement.
