### ISSUE TITLE
Wikidata links missing

### ISSUE THREAD

**Issue by nichtich** [hbz/lobid-organisations#426]
It looks like all links from organizations to corresponding Wikidata items have been removed from the data. E.g. <https://lobid.org/organisations/DE-7> and <https://lobid.org/organisations/DE-MUS-113319> (#370).

**Comment by acka47** [comment]
The links are even gone from the JSON where they were added with #320. We might reopen that issue or go on here. You decide, @fsteeg .

**Comment by acka47** [comment]
+1
