### ISSUE TITLE
Switch sameAs links to ISIL registry to https

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#428]
Similar to but much less invasive than https://github.com/hbz/lobid-gnd/issues/243. The URIs in the ISIL-/Sigelverzeichnis were also switched to https, see e.g. https://ld.zdb-services.de/data/organisations/DE-1a.ttl

As we create the RDF by ourselves and only have the ISIL registry URIs in the sameAs statements, we only have to update those. I guess, we just have to add an "s" here:

https://github.com/hbz/lobid-organisations/blob/4e7eb3cad63c38707cfd78adc126771e1b1e63c1/conf/morph-enriched.xml#L374

**Comment by TobiasNx** [comment]
Fixed with the fix, see:
http://test.lobid.org/organisations/DE-1a.json

```
"sameAs": [
   [ "http://www.wikidata.org/entity/Q170109"](http://www.wikidata.org/entity/Q170109),
    ["https://lobid.org/gnd/5036103-X#!"](https://lobid.org/gnd/5036103-X#!),
    ["https://ld.zdb-services.de/resource/organisations/DE-1a"](https://ld.zdb-services.de/resource/organisations/DE-1a)
  ]
```

**Comment by acka47** [comment]
+1

**Comment by TobiasNx** [comment]
> Fixed with the fix, see: http://test.lobid.org/organisations/DE-1a.json
> 
> ```
>  "sameAs": [
>     "http://www.wikidata.org/entity/Q170109",
>     "https://lobid.org/gnd/5036103-X#!",
>     "https://ld.zdb-services.de/resource/organisations/DE-1a"
>   ]
> ```

http://lobid.org/organisations/DE-1a.json

Deployed with #450
