### ISSUE TITLE
Outdated links to local catalogs

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-organisations#431]
From the email _Wtrlt: WG: Neue OPAC-Links_ from Thu, 6 Aug 2020 09:54:32 by T. Schön (removed the points 3 and 4 because they just stated that there is nothing to do):

> der Mail unten ist zu entnehmen, dass es für die von der Sporthochschule betreuten Lokalsysteme neue Links gibt.
> Auf der Webseite ist das aufgefallen. Dort können wir sie aber nicht ändern, weil wir sie dort automatisch über lobid beziehen.
> Es geht also um die Korrektur auf der lobid-Ebene.

>[...]
> => 

>  aufgefallen, dass auf den Einträgen im Verzeichnis
> 
> https://www.hbz‑nrw.de/produkte/verbunddienstleistungen/verbundbibliotheken/   …
> 
> 
> die Links zu den von uns gehosteten ALEPH‑OPACS teilweise
> nicht mehr aktuell sind. Auf welchen anderen Seiten des hbz
> dies ebenfalls der Fall sein kann, weiß ich nicht.
> 
> Hier die Liste der aktuellen Links (die sicherlich bis zur
> ALMA Einführung Bestand haben):
> 
> 
> 1. folkwang‑universitaet‑der‑kuenste‑bibliothek
> 
> https://www.hbz‑nrw.de/produkte/verbunddienstleistungen/verbundbibliotheken/folkwang‑universitaet‑der‑kuenste‑bibliothek  
> 
> ISIL: DE‑1156
> neuer OPAC‑Link:  mhe.zbsport.de
> 
> 
> 2. Kunstakademie Düsseldorf
> 
> https://www.hbz‑nrw.de/produkte/verbunddienstleistungen/verbundbibliotheken/kunstakademie‑duesseldorf‑bibliothek  
> 
> ISIL: DE‑Due18
> neuer OPAC‑Link:  kad.zbsport.de
> 
> 
> 3. Robert‑Schumann‑Hochschule Düsseldorf
> 
> https://www.hbz‑nrw.de/produkte/verbunddienstleistungen/verbundbibliotheken/robert‑schumann‑hochschule‑duesseldorf‑bibliothek  
> 
> ISIL: DE‑1972
> neuer OPAC‑Link:  der angebene Link kann so bleiben, da persistent.
> 
> 4. hochschule‑fuer‑musik‑und‑tanz‑koeln
> 
> https://www.hbz‑nrw.de/produkte/verbunddienstleistungen/verbundbibliotheken/hochschule‑fuer‑musik‑und‑tanz‑koeln‑bibliothek  
> 
> ISIL: DE‑Kn38
> neuer OPAC‑Link:  der angebene Link kann so bleiben, da persistent.
> 
> 
> 5. Stadtbibliothek Trier
> 
> Diese Bibliothek hat vor Kurzem ihren Namen geändert.
> Auf der verlinkten Seite
> https://www.hbz‑nrw.de/produkte/verbunddienstleistungen/verbundbibliotheken/stadtbibliothektrier  
> steht das schon richtig,  auf der Übersichtsseite
> https://www.hbz‑nrw.de/produkte/verbunddienstleistungen/verbundbibliotheken  
> steht noch der alte Name.
> 
> ISIL: DE‑121
> neuer OPAC‑Link:  str.zbsport.de
> 
> Beim Anklicken der Links und auch beim Zurücksprung auf die Übersichtsseite
> ist mir noch aufgefallen, dass es teilweise fast eine Minute dauert, bis
> die Seiten geladen werden.

**Comment by dr0i** [comment]
Just wrote this mail:


> 1 ) Sieht so aus als ob das doch genauso schon in lobid (und auf der hbz-Seite) steht => kein Handlungsbedarf
2 ) Die veralteten Daten stehen so im Sigelverzeichnis. Da wir dieses als Primäre Quelle nutzen sollten (u.a.) die URLs zu den OPACS dort geändert werden, damit auch andere Dienste, die auf dem Sigelverzeichnis aufbauen aktualisiert werden können. Ändern geht hier: http://sigel.staatsbibliothek-berlin.de/aenderungen-mitteilen/?isil=DE-Due18
3 ) kein Handlungsbedarf
4 ) kein Handlungsbedarf
5 ) In lobid steht für https://lobid.org/organisations/DE-121 als Titel "Wissenschaftliche Bibliothek der Stadt Trier", also, wenn ich es richtig verstanden habe, ist das der aktuelle Name. Warum auf der Übersichtsseite der alte Name steht ? Deligiere an den Webmaster vom hbz.

**Comment by acka47** [comment]
I just requested to adjust  2) and 5) in the Sigelverzeichnis.

**Comment by acka47** [comment]
Everything is updated by now in ISIL registry, lobid.organisations and on the hbz website. Closing.
