### ISSUE TITLE
Missing isil: DE-61-93

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-organisations#433]
Email from T. Schön from 03.09.20:
The [Isil DE-61-93 could not be found](https://lobid.org/organisations/search?q=isil%3A"DE-61-93") by customers from Digibib.
I could not find that Isil in the zdb directory, too.

This Isil seems to exist, see e.g. https://www.lobid.org/resources/HT019681342.json.
We got a tab_sigel from Verbund where this sigel is defined.

Don't know how lobid-organisations works here, it doesn't seem to use the tab_sigel (which itself would not be sufficient, anyway).

**Comment by acka47** [comment]
The screenshot from the email Tiziane forwardedwas taken from this page: https://lobid.org/organisations/DE-61-93

However, I think there are a lot of (sub-)ISILs in lobid-resources that are not in lobid-organisations. See e.g. this ticket where those are also mentioned: https://github.com/hbz/lobid-resources/issues/340#issue-216738550

I think this is not a problem with lobid-organisations and could thus be closed here. However, we should inform the original reporter about it....

**Comment by acka47** [comment]
Even better is this comment wrt subsigels in hbz01 that are not in the ISIL registry: https://github.com/hbz/nwbib/issues/77#issuecomment-69893521

**Comment by dr0i** [comment]
Ok, closing.

**Comment by dr0i** [comment]
Hm , just a note:
It seems a bit unfortunate that these subsigels are IDs in use. While allowed, it always hurt to try to lookup something with no luck. Bad web practice.

**Comment by acka47** [comment]
I agree but don't think we should start ponering how we could change this. The best option would be to register them in the ISIL registry and there are apparently good reasons to not do this. (At least ist says so as result of the discussion in 2014/15.)

**Comment by fsteeg** [comment]
I see two ways we could improved the user experience here:

- In the item information in lobid-resources, we could check if the lobid-organisations entry actually exists and only display a link if it does, and plain text of the organisation name (or even a link to the super organisation) otherwise
- Improve the error message on non-existing organisations, with something like "This probably means this item is not part of the ISIL registry...", with a link etc.
