### ISSUE TITLE
Use DBS geo data

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-organisations#434]
With this weekend the data we get from DBS (T.Nap) is in part enriched with geo data. This geo data shall be used in favour of of ZDB-Sigelverzeichnis.

**Comment by dr0i** [comment]
Deployed to staging, see e.g. https://test.lobid.org/organisations/DBS-AA022.json

**Comment by dr0i** [comment]
Already deployed to production (since the data there was outdated anyway (#435)).

**Comment by acka47** [comment]
It's hard to review with no previous state to compare to and without the map being shown. Coverage already looks good, there are now only [922 entries](https://lobid.org/organisations/search?q=NOT+_exists_%3Alocation.geo) (4,6%) without geo coordinates.

**Comment by dr0i** [comment]
Odd - making your query re "entries with missing geo coordinates" against test, I only got 22 hits. While "test" has 105 more resources indexed overall. So, test seems to rule. :confused:

**Comment by dr0i** [comment]
However, the new data is indexed and we leave it as it is.

**Comment by dr0i** [comment]
A note:
after doing https://github.com/hbz/lobid-organisations/issues/435 the data in production is now at sync with test :)
Going update the README so that not only a crontabbed index update works but also the manual dispatching is been documented.
