### ISSUE TITLE
Post "index" not working

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-organisations#435]
An `curl  -XPOST http://localhost:7200/organisations/index` doesn't work: the data is not updated in the index.
As a workaround, in the crontab it's scheduled to restart the app. This _does_ trigger the indexation of the new/updated data.

Tested when working at #434.

**Comment by acka47** [comment]
Good to see you are giving lobid-organisations some love.

**Comment by dr0i** [comment]
Just had do that again while deploying #434 on production. It is confirmed -  "tranform", "index" AND a restart is needed.

**Comment by dr0i** [comment]
Workaround documented and crontabbed. Closing.
