### ISSUE TITLE
Images won't load from Wikimedia Commons proxy 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#444]
Images from Wikimedia Commons won't load in the browser. Same as https://github.com/hbz/lobid-gnd/issues/291, as it uses the same proxy:

- There is no error notification in the browser console.
- Resolving a proxy URL – e.g. https://lobid.org/imagesproxy?url=https://commons.wikimedia.org/wiki/Special:FilePath/Museum%20Butzbach%20Aussenansicht.jpg – gives a notification, strangely as an image; "Die Grafik ... kann nicht angezeigt werden, weil sie Fehler enthält."
- Loading the image directly works, though, see https://upload.wikimedia.org/wikipedia/commons/1/12/Museum_Butzbach_Aussenansicht.jpg.

**Comment by dr0i** [comment]
Strangely, the solution in https://github.com/hbz/lobid-gnd/issues/291 doesn't seem to work here.

**Comment by dr0i** [comment]
Don't know why it seemed to worked re: https://github.com/hbz/lobid-gnd/issues/291#issuecomment-870350085 because there only the response header was set, not the request header.
Did now set the "request header" using curl php.

**Comment by acka47** [comment]
Fixed on production. +1 Closing.
