### ISSUE TITLE
Format CSV field isil is empty

### ISSUE THREAD

**Issue by cKlee** [hbz/lobid-organisations#447]
lobid.org/organisations/search?q=type:Library&size=300&&format=csv:isil gives me an empty list.

**Comment by acka47** [comment]
It looks like the results to this query are sorted alphabetically by `id`. Thus, the first ~1200 entries in this query are DBS entris, that just not have an ISIL. 

Checking the `id` makes clear that only one entry from the 999 first results to this query is not coming from DBS:

`$ curl "https://lobid.org/organisations/search?q=type:Library&size=999&format=csv:id"| grep DBS | wc -l`

It starts to work at around number ~1200:

`$ curl "https://lobid.org/organisations/search?q=type:Library&size=300&from=1201&format=csv:isil"`

If you only want results with ISIL in your response, you can adjust your query with `_exists_:isil` like this:

`$ curl "https://lobid.org/organisations/search?q=type:Library+AND+_exists_:isil&size=300&from=901&format=csv:isil"`

@cKlee, please close this issue if this is resolved.

**Comment by cKlee** [comment]
Danke Adrian!
