### ISSUE TITLE
Re-organize Sigel data update process

### ISSUE THREAD

**Issue by philboeselager** [hbz/lobid-organisations#45]
As discussed in https://github.com/hbz/lobid-organisations/pull/42/files#r31126569 , the Sigel data update process should be re-organized. DOD:
- Current updates do not include (all) data of former updates.
- No code adjustments are necessary when a new calendar year begins.

**Comment by acka47** [comment]
Bullet point one probably is about deleted fields. We are not sure about number two. @philboeselager do you still know what this is about?

**Comment by acka47** [comment]
Can this issue be closed, @fsteeg?

**Comment by fsteeg** [comment]
Not sure, I think we should discuss this with @SBRitter.

**Comment by acka47** [comment]
@fsteeg, you wanted to do something about the lobid-organisations data OAI-PMH import. Maybe this issue is the right place for it...

**Comment by acka47** [comment]
This issue is confusing and we can create a separate issue if we some day want to improve the update process. Closing.
