### ISSUE TITLE
Get info about deprecated and replaced Isils from Pica+ 035D $b

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-organisations#457]
Okay. We can do this once. But what to do on future redirects? We suggest that you extract this from Pica+ 035D $b when importing our data.

_Originally posted by @cKlee in https://github.com/hbz/lobid-resources/issues/1768#issuecomment-1557120618_

**Comment by TobiasNx** [comment]
Added `replaces` and `replacedBy` properties:

http://test.lobid.org/organisations/DE-1373.json

```
"replaces": [
    {
      "isil": "DE-18-17",
      "id": ["http://lobid.org/organisations/DE-18-17#!"](http://lobid.org/organisations/DE-18-17#!),
      "type": "Organisation"
    }
  ]
```

http://lobid.org/organisations/DE-464#!

```
"replacedBy": [
    {
      "isil": "DE-465",
      "id": ["http://lobid.org/organisations/DE-465#!"](http://lobid.org/organisations/DE-465#!),
      "type": "Organisation"
    }
  ],
```

Added properties to the context:
http://test.lobid.org/organisations/context.jsonld

**Comment by acka47** [comment]
Looks good but there are problems with the properties used:  [https://schema.org/replacedBy](https://schema.org/replacedBy) and  [https://schema.org/replaces](https://schema.org/replaces) don't exist, there is only a more complex [`ReplaceAction`](https://schema.org/ReplaceAction) in schema.org. I took a short look at LOV but did not find a suitable proprerty.

**Comment by TobiasNx** [comment]
What about:
https://www.dublincore.org/resources/userguide/publishing_metadata/#dcterms:isReplacedBy
https://www.dublincore.org/resources/userguide/publishing_metadata/#dcterms:replaces

**Comment by acka47** [comment]
I like the `gndo` properties more as they eplicitely mention corporate bodies in the description, e.g. `gndo:predecessor`:

> A corporate body or a work being the predecessor of another corporate body or work

**Comment by TobiasNx** [comment]
there is also:
https://d-nb.info/standards/elementset/gnd#precedingCorporateBody
https://d-nb.info/standards/elementset/gnd#succeedingCorporateBody

**Comment by acka47** [comment]
> there is also:
> https://d-nb.info/standards/elementset/gnd#precedingCorporateBody
> https://d-nb.info/standards/elementset/gnd#succeedingCorporateBody

Fine for me. e-resource packages do not have this kind of information, do they? If yes, the general property would be the safer choice.

**Comment by TobiasNx** [comment]
you are right. lets take the more general version.

**Comment by cKlee** [comment]
E-resource packages do have this data. So the more general should be the right choice.

**Comment by TobiasNx** [comment]
> Added `replaces` and `replacedBy` properties:
> 
> http://test.lobid.org/organisations/DE-1373.json
> 
> ```
> "replaces": [
>     {
>       "isil": "DE-18-17",
>       "id": "http://lobid.org/organisations/DE-18-17#!",
>       "type": "Organisation"
>     }
>   ]
> ```
> 
> http://lobid.org/organisations/DE-464#!
> 
> ```
> "replacedBy": [
>     {
>       "isil": "DE-465",
>       "id": "http://lobid.org/organisations/DE-465#!",
>       "type": "Organisation"
>     }
>   ],
> ```
> 
> Added properties to the context: http://test.lobid.org/organisations/context.jsonld

Now the examples have successor and predecessor.

**Comment by TobiasNx** [comment]
> > Added `replaces` and `replacedBy` properties:
> > http://test.lobid.org/organisations/DE-1373.json
> > ```
> > "replaces": [
> >     {
> >       "isil": "DE-18-17",
> >       "id": "http://lobid.org/organisations/DE-18-17#!",
> >       "type": "Organisation"
> >     }
> >   ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > http://lobid.org/organisations/DE-464#!
> > ```
> > "replacedBy": [
> >     {
> >       "isil": "DE-465",
> >       "id": "http://lobid.org/organisations/DE-465#!",
> >       "type": "Organisation"
> >     }
> >   ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Added properties to the context: http://test.lobid.org/organisations/context.jsonld
> 


Now the examples have successor and predecessor on prod too.

http://lobid.org/organisations/DE-464#!
http://test.lobid.org/organisations/DE-1373.json

@fsteeg should we add this to the GUI?
