### ISSUE TITLE
Enable CSV export

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#47]
Based on [customer feedback](https://twitter.com/hauschke/status/608595744300367872) by @hauschke: Enable users to download result list as CSV.

**Comment by acka47** [comment]
@philboeselager I guess this doesn't take too much effort at some point as we will also implement this in the oerworldmap project that uses the same technology, see https://github.com/hbz/oerworldmap/issues/35, does it?

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/organisations/search?q=kunst&size=300&format=csv
http://test.lobid.org/organisations/search?q=kunst&size=300&format=csv:name,isil,url,classification.label

Documentation at:

http://test.lobid.org/organisations/api#content_types
http://test.lobid.org/organisations/api#csv

**Comment by acka47** [comment]
Looks good to me. @hauschke, it would be great if you could also take a look at this.

**Comment by fsteeg** [comment]
@acka47 I'd suggest we deploy this for now, we can always tweak it based on feedback later.

**Comment by acka47** [comment]
+1
