### ISSUE TITLE
Identify the several libraries and ZDB-packages that are more in test

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-organisations#479]
I assume that they are missing libraries from DBS:

http://test.lobid.org/organisations/DBS-SJ425

**Comment by TobiasNx** [comment]
On Prod: 21239
On Test: 21255

Multiple libraries are deleted on test, therfore there are more than 16

**Comment by TobiasNx** [comment]
Stadtbücherei Haiger: http://test.lobid.org/organisations/DBS-GA523#! -Duplicate to: http://lobid.org/organisations/DE-4225#!
Patientenbibliothek Diakonissenanstalt: http://test.lobid.org/organisations/DBS-NI178#! - Does not exist in Prod
Kath. Öffentliche Bibliothek St. Jacobus: http://test.lobid.org/organisations/DBS-NT996#! - Does not exist in Prod
Frauenbücherei St. Laurentius: http://test.lobid.org/organisations/DBS-PD095#! - Does not exist in Prod
Kath. Öffentliche Bücherei St. Peter: http://test.lobid.org/organisations/DBS-PR154#! - Does not exist in Prod
Kath. Öffentliche Bibliothek St. Barbara Breinig: http://test.lobid.org/organisations/DBS-QA294#! - Does not exist in Prod
Kath. Öffentliche Bibliothek St. Fronleichnam. Bücherinsel Adalbertsteinweg: http://lobid.org/organisations/DBS-QC916#! - Does not exist in Prod
Kath. Öffentliche Bücherei St. Cäcilia Nothberg: http://lobid.org/organisations/DBS-QF991#! - Does not exist in Prod
Kath. Krankenhausbücherei Eifelhöhen-Klinik: http://test.lobid.org/organisations/DBS-QU367#! - Does not exist in Prod
Kath. Öffentliche Bibliothek St. Bonifatius: http://lobid.org/organisations/DBS-RT010#! - Does not exist in Prod
Kath. Öffentliche Bücherei St. Lambertus: http://lobid.org/organisations/DBS-RT071#! - Does not exist in Prod
Krankenhaus St. Josef, Patientenbücherei: http://lobid.org/organisations/DBS-SJ425#! - Does not exist in Prod
Kath. Öffentliche Bibliothek Herz Jesu: http://lobid.org/organisations/DBS-TA985#! - Does not exist in Prod
Kath. Öffentliche Bücherei Christus König: http://lobid.org/organisations/DBS-TL750#! - Does not exist in Prod
Gemeindebücherei Lauben: http://lobid.org/organisations/DE%5F4050#!: http://test.lobid.org/organisations/search?q=GX708&location= Dubletter Eintrag in Prod und halbfalscher Eintrag in Test http://lobid.org/organisations/DE_4050#!
1 | http://lobid.org/organisations/DE-MUS-15052#! - Existiert nicht in Test, aber auch nicht mehr im Sigel-Verzeichnis:  	DE-MUS-15052
http://lobid.org/organisations/DE-Test4#!  - Existiert nicht in Test, da Test
http://lobid.org/organisations/ISILDE-MUS-161828#! Existiert nicht in Test, aber auch nicht mehr im Sigel-Verzeichnis:  	DE-MUS-15052
http://lobid.org/organisations/ZDB-2-CMPH#!   - Existiert nicht in Test, da überschriebene ISIL
http://lobid.org/organisations/ZDB-2-RMBE#! - Existiert nicht in Test, da überschriebene ISIL
http://lobid.org/organisations/ZDB-2-RMED#! - Existiert nicht in Test, da überschriebene ISIL
http://lobid.org/organisations/ZDB-2-RMEE#! - Existiert nicht in Test, da überschriebene ISIL
http://lobid.org/organisations/ZDB-2-RMH#! - Existiert nicht in Test, da überschriebene ISIL
http://lobid.org/organisations/ZDB-Test2#!  - Existiert nicht in Test, da Test
http://lobid.org/organisations/ZDB-Test2a#!  - Existiert nicht in Test, da Test
http://lobid.org/organisations/ZDB-Test3#! - Existiert nicht in Test, da Test

**Comment by acka47** [comment]
Could it be that libraries that have been removed from DBS have not been deleted in lobid-organisations?

**Comment by TobiasNx** [comment]
I don't know about the update routine? Do we still get new DBS-Data (dbs.csv) and rebuild lobid-organisations: https://github.com/hbz/lobid-organisations/issues/94

**Comment by acka47** [comment]
> I don't know about the update routine? Do we still get new DBS-Data (dbs.csv) and rebuild lobid-organisations:

In 2018 we implemented regular DBS updates, see  #94.

**Comment by TobiasNx** [comment]
Need to have another look. It seems that the total hits are still deviating.

**Comment by TobiasNx** [comment]
The difference consists mainly of DBS records that were not indexed in prod. Related to #475 
Some updates of deleted records in Sigil that are not fetched via OAI-PMH. Related to #487
Deleted test files and errors from prod, that are fixed and not provided anymore in test.
