### ISSUE TITLE
Add addressCountry to DBS-derived data

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#48]
Currently, we have no valid function for filtering results by country (see also http://infobib.de/2015/06/10/wie-viele-bibliotheken-gibt-es-in-deutschland/comment-page-1/#comment-15154). As soon as we add `addressCountry` to the DBS-derived entries we will be able to filter by country via http://beta.lobid.org/organisations/search?q=location.address.addressCountry:Germany.
 (snippet)
Currently, the RDF of a library description solely derived from DBS looks like this (from http://beta.lobid.org/organisations/DBS-JA893):

```javascript
{
               "dbsID" : "JA893",
               "location" : [
                  {
                     "type" : "http://schema.org/Place",
                     "openingHoursSpecification" : {
                        "@type" : "http://schema.org/OpeningHoursSpecification",
                        "description" : "Mo + Do 16.00-19.00 Uhr"
                     },
                     "address" : {
                        "addressLocality" : "Großhabersdorf",
                        "type" : "http://schema.org/PostalAddress",
                        "streetAddress" : "Fernabrünsterstr. 11"
                     }
                  }
               ]
}
```

What's missing is something like `"addressCountry" : "Germany"`.

Country info is in the `iso` column in dbs.csv. Either we should map the iso codes on country names like this:
- AUT -> Austria
- CHE -> Switzerland
- CZE -> Czech Republic
- DEU -> Germany
- ESP - Spain
- FRA -> France
- ITA -> Italy

Or – wich is probably the better way – we switch to using iso country codes in the data.

**Comment by philboeselager** [comment]
@acka47 : can you please specify: What exactly do you mean by "THE data" (in: "... we switch to using iso country codes in the data."). Do you aim on s.th. like: 

    {
               ... [
                  {
                     ...
                     "address" : {
                        "addressLocality" : "Großhabersdorf",
                        "type" : "http://schema.org/PostalAddress",
                        "streetAddress" : "Fernabrünsterstr. 11",
                        "addressCountry" : "DEU"
                     }
                  }
               ]
    }

?

**Comment by acka47** [comment]
Yes, I was thinking about doing it similar to oerworldmap where we use the Alpha-2 codes (see https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes for reference). I'd prefer using Alpha-2 codes here as they are most widely used.

We would have to adjust the data derived from Sigelverzeichnis accordingly as well where we currently have the whole country name written in `addressCountry`. (Will make a ticket for this as soon as we have decided for a solution.)

**Comment by philboeselager** [comment]
Well, it's fine for me. Who is going to make a decision? (Do you think there's anyone non-agreeing?)

**Comment by acka47** [comment]
As `AddressCountry` is now part of DBS-only derived resources, I am closing this issue. For further adjustment using the country code, a new issue exists, see #73 .
