### ISSUE TITLE
Add cron-job for updating wikidataLookup.tsv

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-organisations#482]
Use this:
https://github.com/hbz/lobid-organisations/blob/0e06fafae82b755e4ddf75d054cd33f632c641e8/conf/wikidataLookup.sparql

For updating this:
https://github.com/hbz/lobid-organisations/blob/master/conf/wikidataLookup.tsv

Also the lookup-file for testing should be moved in a separate folder.

**Comment by dr0i** [comment]
Deployed.
Functional review: @TobiasNx .

**Comment by TobiasNx** [comment]
Why has every institution a ISIL now? This is an error!!!

**Comment by TobiasNx** [comment]
I opened the ticket: https://github.com/hbz/lobid-organisations/issues/501

**Comment by dr0i** [comment]
Reverted with f077fa1 with 2c6a656.

**Comment by TobiasNx** [comment]
This seems to work now again. Closing
