### ISSUE TITLE
Test does not receive updates after 21-07-23 / Issue with the interval for the updates.

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-organisations#487]
http://lobid.org/organisations/DE-290-PAS#! (früher: Dortmund, Universitätsbibliothek, Informationszentrum Technik und Patente)
http://test.lobid.org/organisations/DE-290-PAS#! (Universitätsbibliothek, Informationszentrum Technik und Patente)

The deletion is not yet processed in [test.lobid](http://test.lobid.org/organisations/). But the Pica-Data show it is delted also the prod:
https://services.dnb.de/sru/bib?operation=searchRetrieve&query=isl%3DDE-290-PAS&recordSchema=PicaPlus-xml&version=1.1

**Comment by TobiasNx** [comment]
I identified the problem, the last records have dateCreated or datemodified 21-07-23. That are exactly 50 days after the update start. This is the configured in the conf file with 50. Therefore this means that the second interval is not start.

**Comment by dr0i** [comment]
Note to self:
It's not enough not merge and restart on server. also the `cron.sh` has to be triggered - this rebuilds the data (and gets the new data).

It's working , see http://test.lobid.org/organisations/DE-290-PAS.
Closing.
