### ISSUE TITLE
Add geo coordinates to DBS-derived entries

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#49]
Currently, we only have geo coordinates for organizations from the Sigelverzeichnis. We also have to geocode [the ones solely derived from DBS data](http://beta.lobid.org/organisations/search?q=@id=DBS), e.g. http://beta.lobid.org/organisations/DBS-GF429#!.

**Comment by philboeselager** [comment]
@dr0i : you mean https://github.com/hbz/oerworldmap.prototype/blob/7a7d30ffb1dc36368e0067652742b3adb9743086/oer-data/src/main/java/org/hbz/oerworldmap/Transform.java --> geoWithHttpLookup() as a starting point?

**Comment by dr0i** [comment]
Yes.It's is a nicer way (more metafacture like) than https://github.com/lobid/lodmill/blob/master/lodmill-rd/src/main/java/org/lobid/lodmill/PipeLobidOrganisationEnrichment.java. The latter gives you the heuristics used by the old lobid organisations for getting geo data. If you are also going to use OSM, look at their API now, they may have changed/improved things.

**Comment by philboeselager** [comment]
ES Index on q.....1, Index: "organisations-20151111-pvb"

**Comment by acka47** [comment]
@philboeselager Could you put this and the other changes on http://beta.test.lobid.org/organisations? This would make it easier for me to review...

**Comment by fsteeg** [comment]
@acka47 @philboeselager That should be http://test.lobid.org/organisations (not sure why your `beta.test` link even works), see details at https://github.com/hbz/lobid-organisations/issues/71.

**Comment by philboeselager** [comment]
@fsteeg Thanks - I knew what acka ment ;-)
@acka47 new index is connected to http://test.lobid.org/organisations/

**Comment by acka47** [comment]
Can you say something about the number of organizations where the geo lookup worked? From the entries of [this list of 199 DBS-derived entries](http://test.lobid.org/organisations/search?q=@id=DBS&size=199) 146 have geo information. From [this list](http://test.lobid.org/organisations/search?q=@id=DBS&size=199&from=200) only 54.

Do you do the lookup on the data with posta code in `streetAddress` (see https://github.com/hbz/lobid-organisations/issues/50#issuecomment-156358151)? This could be a reason for the relatively low number of hits...

**Comment by philboeselager** [comment]
#83 has been merged. Deployed to beta.lobid.org . Closing.
