### ISSUE TITLE
DBS Libraries without ISIL are missing on Prod

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-organisations#501]
We index the libraries from DBS because we also want all libraries that are in DBS and are NOT registered in the ISIL Registry too.
These libraries are now missing.

The total count of libraries should at least be + 21.200 see also my last check:

https://github.com/hbz/lobid-organisations/issues/479#issuecomment-1669805225

**Comment by TobiasNx** [comment]
test still has them: http://test.lobid.org/organisations/search?q=&location=

**Comment by TobiasNx** [comment]
http://test.lobid.org/organisations/DBS-AA004.json exists
http://lobid.org/organisations/DBS-AA004.json does not :(

**Comment by dr0i** [comment]
For whatever reason the file `./app/transformation/input/dbs.csv` was empty. I copied the file manually (it _was_ generated correctly at Sun 3:00) and restarted ETl. Lookks good now : >21k entries (http://lobid.org/organisations/search?q=*).

**Comment by dr0i** [comment]
Closing.
