### ISSUE TITLE
App cannot be started due to "MapperParsingException"

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-organisations#502]
> Oops, cannot start the server.
ElasticsearchException[Bulk insert failed: failure in bulk execution:
[8844]: index [organisations], type [organisation], id [DBS-XY123], message [MapperParsingException[failed to parse]; nested: ElasticsearchParseException[field [lat] missing];]]
        at controllers.Index.indexData(Index.java:212)

**Comment by dr0i** [comment]
From the data that failed to be indexed:
> enriched.prod.out.json-dbs:{"rs":"055150000000","type":"Library","[...]"geo":{"lon":"7.633706"},"type":"Place"}],

Clearly, there is the `geo.lat` missing.
@TobiasNx could you fix this with setting a dummy fro `geo.lat`or (better?) dump the whole `geo` entry if one of `lat` or `lon` is missing?

**Comment by TobiasNx** [comment]
When I test this locally there seems to be no error. This is an error because of the pelias lookup which only seems to have an lon but no lat which is strange.

General question how is pelias build and should we update it? Also because of #476 and #483 
Otherwise workaround as you suggested would work fine.

```
if exists("latDbs")
	copy_field("latDbs","@visitorLocation.geo.lat") # <!-- dbs verzeichnis -->
elsif exists("latVisitor")
	copy_field("latVisitor","@visitorLocation.geo.lat") # <!-- zdb sigel verzeichnis -->
elsif exists("@geoLookupDbs") # <!-- geo lookup pelias -->
	copy_field("@geoLookupDbs","@geoLookupDbsLat")
	lookup("@geoLookupDbsLat","addLatMap", delete:"true")
	copy_field("@geoLookupDbsLat","@visitorLocation.geo.lat")
end

if exists("lonDbs")
	copy_field("lonDbs","@visitorLocation.geo.lon") # <!-- dbs verzeichnis -->
elsif exists("lonVisitor") 
	copy_field("lonVisitor","@visitorLocation.geo.lon") # <!-- zdb sigel verzeichnis -->
elsif exists("@geoLookupDbs")
	copy_field("@geoLookupDbs","@geoLookupDbsLon")
	lookup("@geoLookupDbsLon","addLongMap" , delete:"true") # <!-- geo lookup pelias -->
	copy_field("@geoLookupDbsLon","@visitorLocation.geo.lon")
end
```

**Comment by dr0i** [comment]
re pelias: as discussed offline we will not look into it.

**Comment by dr0i** [comment]
Thx for the fast fix!
Note: Interestingly, the error was caused by `dbsID:DBS-XY123`.  And this resource  now _has_ it's geo coordinate: http://lobid.org/organisations/DBS-XY123.json .

**Comment by dr0i** [comment]
Closing as solved..
