### ISSUE TITLE
Reconciliation endpoint is broken

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#509]
Reported by @tzeumer via https://openbiblio.social/@vform/112026730254574476.

The endpoint only delivers back the service manifest, even for a batch query, see e.g. https://lobid.org/organisations/reconcile?queries=%7B%22q0%22%3A%7B%22query%22%3A%22k%C3%B6ln%22%7D%7D

**Comment by fsteeg** [comment]
The organisations reconciliation service is very rudimentary, e.g. it does not support GET queries for reconciliation (like the link in the original comment above). It also stumbles over a trailing `/` in the URL.

But basic POST reconciliation requests do work: `curl --data 'queries={"q1":{"query":"hbz"}}' https://lobid.org/organisations/reconcile`

**Comment by acka47** [comment]
Ah, ok. I have tried it out in OpenRefine and this still works. @tzeumer , is this ok for you? Did you want to work on this in OpenRefine anyway?

**Comment by tzeumer** [comment]
Yes, I want to use it in OpenRefine. Somehow I got from the reconcile screen to https://reconciliation-api.github.io/testbench/#/ and testet it there with an ISIL. But that failed. I thought, I tried it in OpenRefine directly, too. But you are right, it works there. Sorry, maybe I should have tested more before complaining. 

Thanks for the review and quick feedback @acka47 and @fsteeg

**Comment by acka47** [comment]
Thanks for the response. So I am closing this issue. Let us know about any further problems or when you need any reconciliation features the API does not support yet. (There aren't many features because this is basically the same API setup as 2015 when we had our first contact with implementing a reconciliation API after Christian Hauschke wanted to batch match some library names to an ISIL, see https://github.com/hbz/lobid-organisations/issues/55. )
