### ISSUE TITLE
Remove "@"s in JSON

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#51]
As far as I know we mapped `"@id"` to `"id"` in the JSON-LD context so that users not familiar with JSON-LD won't be presented any confusing `@`s – apart from `@context` – in the JSON.

From the [context document](http://beta.lobid.org/organisations/context.jsonld):

```javascript
"id": "@id",
"type": "@type"
```

[Example entry](http://beta.lobid.org/organisations/DE-9) (snippet):

```javascript
"@type": "http://schema.org/Library",
"@id": "http://beta.lobid.org/organisations/DE-9#!"
```

**Comment by acka47** [comment]
For the time being, we will keep all the `@`s. Will further discuss whether we might change this, when @fsteeg is back.

**Comment by dr0i** [comment]
After discussion with @philboeselager @acka47 @fsteeg @dr0i: we wil get rid of the `@` in [lobid-resources](https://github.com/hbz/lobid-resources).
To be coherent, this should also be done in lobid-organisations.

**Comment by fsteeg** [comment]
To clarify: this is for the new 2.0 APIs, not the current production APIs. And the 2.0 organisations API is already `@graph`-less, see: http://weywot2.hbz-nrw.de:9200/organisations/organisation/DE-605/_source

**Comment by acka47** [comment]
> the 2.0 organisations API is already `@graph`-less, see: http://weywot2.hbz-nrw.de:9200/organisations/organisation/DE-605/_source

Can't have a look at this via vpn. Anyway, this issue isn't only about the `@graph`. We still have `@`s in beta-organisations – other than in `@context` which we won't get rid of – which have to be removed. See http://beta.lobid.org/organisations/DE-6.

**Comment by fsteeg** [comment]
OK, I'm starting to understand: originally, the new `lobid-organisations` was `@`-less, except for the `@context`. This is what I saw in the old `organisations` index I mentioned in https://github.com/hbz/lobid-organisations/issues/51#issuecomment-136745292. Then, in 2d6f8be9be401cc3beb3fceff0624882f9ff2dad, the `@`s were introduced. Therefore in the current API at http://beta.lobid.org/organisations we have the `@`s. Now pull request https://github.com/hbz/lobid-organisations/pull/70 removes them again, but that is not deployed yet.

**Comment by acka47** [comment]
As we decided in an offline discussion to remove the `@`s I will remove the question mark from the title and move this to "ready".

**Comment by philboeselager** [comment]
An index containing this issue's changes is provided on quaoar1 : organisations-issue51 . It is currently referred by test.lobid.org . The changes also solve #52 .

**Comment by acka47** [comment]
+1

**Comment by philboeselager** [comment]
Deployed to beta.lobid.org. Closing.

**Comment by fsteeg** [comment]
Reopening: reported by @acka47 in https://github.com/hbz/slides/pull/2#issuecomment-187608517.

`@`s are back in production: http://beta.lobid.org/organisations/DE-6

But not on staging: http://test.lobid.org/organisations/DE-6

Code in master looks good:
https://github.com/hbz/lobid-organisations/blob/master/src/main/resources/morph-enriched.xml#L9

Should be a deployment issue.

**Comment by fsteeg** [comment]
Fixed deployemnt issue on production (was using wrong index), see:

http://beta.lobid.org/organisations/DE-6

**Comment by acka47** [comment]
+1
