### ISSUE TITLE
Remove duplicate "@type" : "PostalAddress"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#52]
Reported by @dbs via email (thanks!):

> Looking at the following example of DE-6 in the JSON-LD playground 
> (http://tinyurl.com/oc5t66c) there's a complaint about "type" and 
> "@type" being used in the same stanza. ("type" is set to "@type" in the 
> context document, not 100% sure why).
> 
> If I change "type" to "@type" then it seems happier, but that raises the 
> question: why are there two type identifiers for PostalAddress in the 
> first place? The offending bit is as follows:
> 
>           "address" : {
>              "postalCode" : "48143",
>              "type" : "http://schema.org/PostalAddress",
>              "streetAddress" : "Krummer Timpen 3",
>              "@type" : "http://schema.org/PostalAddress",
>              "addressCountry" : "Germany",
>              "addressLocality" : "Münster"
>           },
> 
> If I remove the first "type" entirely, then JSON-LD playground at least 
> seems happy. The Google structured data testing tool, of course, is 
> hopeless as it doesn't seem to parse context documents :/

To do: Remove the line `"@type" : "http://schema.org/PostalAddress"` as we don't want any `@`s in the JSON. See also #51 for removing further `@`s we currently have in the data.

**Comment by acka47** [comment]
This problem only holds for ISIL-derived data, resources from DBS-only are ok, see e.g. http://beta.lobid.org/organisations/DBS-AA609#!.

**Comment by philboeselager** [comment]
As agreed with @acka47 we keep "@type" for now and remove "type" for now. Having discussed the whole @-issue (see ticket #51), we still might change to "type".

**Comment by philboeselager** [comment]
solved within #51

**Comment by philboeselager** [comment]
Can be tested : http://test.lobid.org/organisations/DE-6 .

**Comment by acka47** [comment]
+1 (It looks like this is already deployed on production, though.)

**Comment by philboeselager** [comment]
Deployed to beta.lobid.org. Closing.
