### ISSUE TITLE
Organisation with wrong ISIL/ID

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#53]
Reported by @hauschke. He says that there would be 1100 of 1980 that are missing in beta.lobid.org/organisations. So far, he only provided one example that wouldn't exist in beta but in production: http://lobid.org/organisation/DE-Gl2

Found the problem for this individual case: The resource actually exists but under te wrong ID/URI: http://beta.lobid.org/organisations/DE-GI2#! It has ISIL "DE-Gl2" (with lowercase "L") while the lobid URI has a capitalized "i" instead.

This doesn't seem to be a systematic mistake, http://beta.lobid.org/organisations/DE-Gl4#! and http://beta.lobid.org/organisations/DE-Gl1#! are correct.

Hopefully, @hauschke will provide us with some more examples.

**Comment by hauschke** [comment]
Sorry, it's not nearly 1100, it's only three organisations:
- Gl2
- B721
- Bi15

**Comment by acka47** [comment]
@hauschke Thanks for the report! I will have a look into this and @philboeselager will improve the data when he's back from holidays.

**Comment by acka47** [comment]
Re. B721:

- Rather, it seems to be incorrect in production. http://ld.zdb-services.de/resource/organisations/DE-B721 doesn't exist anymore but http://ld.zdb-services.de/resource/organisations/DE-2070s. In production, we have duplicates: [DE-B721](http://lobid.org/organisation/DE-B721) and [DE-2070s](http://lobid.org/organisation/DE-2070s).
- Accordingly, there is no entry http://beta.lobid.org/organisations/DE-B721 but the organisation can be found here: http://beta.lobid.org/organisations/DE-2070s#!

**Comment by acka47** [comment]
Re. Bi15.

Somethin went wrong there in transforming the data. The library is recorded here: http://beta.lobid.org/organisations/DE&#8209,Bi8. As you can see the ISIL is wrong but the sameAs links to ZDB are correct. If needed, we should open a separate issue for this.

**Comment by philboeselager** [comment]
* Concerning DE&#8209 : this wrong isil results from the entry in our DBS dump data (dbsID: CU088). This is a data (source) issue, not a processing issue. @acka47 : can you address that (if still present in our last dump) ?
* Concerning DE-2070s / DE-B721 : this is already fixed by our last solved issues, see http://test.lobid.org/organisations/DE-2070s and http://test.lobid.org/organisations/DE-B721 .
* Concerning DE-GI2 / DE-Gl2 : these isils are "same as" in http://test.lobid.org/organisations/DE-GI2 (capitalized "i").

From the processing point of view, this issue can be closed.

**Comment by philboeselager** [comment]
@acka47 : As discussed, the first and the third bullet point should be reported to DBS.

**Comment by acka47** [comment]
I reported the errors and they will be fixed in DBS. I guess we shouldn't wait for the next dDBS dump to fix this in lobid. My suggestion: I provide you with a corrected CSV file which only contains active DBS libraries. You run the Sigel merge and transformation with this file and we will have both the errors corrected and #79 solved. What do you think?

**Comment by acka47** [comment]
As already discussed online we will have to discuss with DBS colleagues the workflow for correcting data and regularly synching lobid with DBS.

**Comment by philboeselager** [comment]
@acka47 As I understand it correctly, this issue can be closed. I'm not sure whether still to open a new issue "Discuss DBS correction workflow".

**Comment by acka47** [comment]
You are right. Closing (and just opened #94)
