### ISSUE TITLE
Polish index page documentation

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#58]
At http://beta.lobid.org/organisations:

- high level overview of the data set
- logos (hbz, lobid)
- favicon
- link to github (main page, contributors, report issue)

**Comment by fsteeg** [comment]
Deployed to http://beta.lobid.org/organisations

**Comment by acka47** [comment]
Looks good but there are still some things to do:

- We should also have this documented in German (with language negotiation via HTTP header) as most interested parties will be from Germany.
- We should replace the favicon by hbz logo or butterfly.
- The second sentence should read: "The source data sets are the German ISIL registry and the base data from the German Library Statistics (DBS)."
- An additional query example of a simple name query would be good, e.g. http://beta.lobid.org/organisations/search?q=name%3Astadtbibliothek%20berlin

**Comment by fsteeg** [comment]
Updated text and added `name` sample query: http://beta.lobid.org/organisations

Favicon was already updated (often cached). Opened issued #63 (translation) and #64 (negotiation).

**Comment by acka47** [comment]
+1 I guess it's polished enough for now. I will do the translation. We also will have to provide some more detailed documentation of the API for potential users, see https://twitter.com/Dennis_Zielke/status/608616238923829248.

**Comment by acka47** [comment]
Closing.
