### ISSUE TITLE
Support indexing test data into local Elasticsearch

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#61]
- Update README to document indexing into localhost (not just hbz internal)
- Fix issue: `[organisations] already exists` on first run with empty Elasticsearch

**Comment by fsteeg** [comment]
The first point is being implemented as part of https://github.com/hbz/lobid-organisations/issues/130

@SBRitter: Did you encounter the second point while testing?

**Comment by SBRitter** [comment]
I don't get this message when running mvn test or mvn clean install. So, I think it's fine.
