### ISSUE TITLE
Translate index page content

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#63]
See #58 

@acka47 I'd suggest a pull request with a full second version of the `index.scala.html` file, e.g. named `index_de.scala.html`.

**Comment by acka47** [comment]
Similar to https://github.com/lobid/lodmill/issues/80.

**Comment by fsteeg** [comment]
Closing, is actually part of #64, and with the new frontend should be implemented on the string level, not page level as I sugggested above.
