### ISSUE TITLE
Serve `en` or `de` index pages based on language header

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#64]
See https://github.com/hbz/lobid-organisations/issues/58#issuecomment-131015168. Depends on #63.

With optional manual switch.

**Comment by fsteeg** [comment]
Deployed to staging, see (uses language requested via HTTP, switch via nav bar, right side):

http://test.lobid.org/organisations
http://test.lobid.org/organisations/search?q=köln&format=html
http://test.lobid.org/organisations/DE-605?format=html

**Comment by SBRitter** [comment]
+1
