### ISSUE TITLE
Provide detailed documentation of API capabilities

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#65]
See https://github.com/hbz/lobid-organisations/issues/58#issuecomment-131113112.

**Comment by acka47** [comment]
I will take over the documentation of JSON-LD properties annotating example resources with hypothes.is.

**Comment by acka47** [comment]
See also https://www.w3.org/TR/dwbp/, especially for dataset metadata.

**Comment by acka47** [comment]
I created a description of the dataset in #255 .

**Comment by acka47** [comment]
I added annotations with hypothes.is to http://lobid.org/organisations/DE-38M?format=json. This is only viewable with the [chrome plugin](https://chrome.google.com/webstore/detail/hypothesis-web-pdf-annota/bjfhmglciegochdpefhhlphglcehbmek), though.

What's next?

- [ ] Create a hypothes.is account with user "lobid"
- [ ] Add JSON example as code snippet to API documentation page
- [ ] Annotate the example on the docu page
- [ ] [Embed hypothes.is](https://hypothes.is/for-publishers/) on the docu page

**Comment by acka47** [comment]
I annotated the example in German. Unfortunately, the annotations are also shown on the English representation of the page, even with `Content-Language` added (#287). I wil ask on the hypothes.is developers list whether they can add support for HTTlanguage headers.

**Comment by acka47** [comment]
With #292, the language problem is solved. The German documentation can be found at http://lobid.org/organisations/api/de. @ChristophEwertowski, could you please take a look at the documentation and see whether it works well enough? There is an example JSON respons that is annotated with hypothes.is. You have to click on the highlighted fields to see the corresponding annotation.

**Comment by ChristophEwertowski** [comment]
It doesn't work well enough because multiple links to examples don't work:
* the last 3 of "API-Grundlagen"
* Ortsbezogene Suche
* second example of "Benutzerdefinierte Felder"
* in hypothes.is: 
    * under "rs" (but I suppose that's the point)
    * the DOI at "url" contains a point too much and can't resolve

Following points are nice to have:
* missing examples
    * "Gemeindeschlüssel"/"ags"
    * "provides"
    * "wikipedia" (example necessary?)
* missing "Abdeckung"
    * containedIn
    * all address sub-properties
    * geo
    * wikipedia
    * email
    * isil
    * name_en
    * sameAs

**Comment by acka47** [comment]
Thanks for the check. I corrected the links in hypothes.is. (You now have the login details for user "lobid" so that you can directly correct them in the future.) Regarding the other links, there seem to be problems with the relative URLs as we already had earlier on. See e.g. https://github.com/hbz/lobid-organisations/blob/master/app/views/api.scala.html#L16-L18 for some of the links. I guess, @fsteeg should best fix this.

**Comment by ChristophEwertowski** [comment]
Reimport of deleted message before acka47 last message:

It doesn't work well enough because multiple links to examples don't work:
* [] the last 3 of "API-Grundlagen"
* [] Ortsbezogene Suche
* [] second example of "Benutzerdefinierte Felder"
* [] in hypothes.is:
    * under "rs" (but I suppose that's the point)
    * the DOI at "url" contains a point too much and can't resolve (DONE)

Following points are nice to have:
* [] missing examples
    * "Gemeindeschlüssel"/"ags"
    * "provides"
    * "wikipedia" (example necessary?)

* [] missing "Abdeckung"
    * containedIn
    * all address sub-properties
    * geo
    * wikipedia
    * email
    * isil
    * name_en
    * sameAs

**Comment by fsteeg** [comment]
Deployed fixed links to staging, see: https://github.com/hbz/lobid-organisations/pull/298

**Comment by ChristophEwertowski** [comment]
The annotation to "url" went up, so I put it back into the right place. If someone else has more examples, feel free to annotate. Otherwise: +1
