### ISSUE TITLE
Set up staging system for lobid-organisations

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#71]
Since the new lobid-organisations is now used in NWBib, we should set up a separate staging system for reviewing changes before deploying them to http://beta.lobid.org/organisations.

**Comment by fsteeg** [comment]
I've set up a staging system in `sol@quaoar1:~/git/lobid-organisations-staging/web`, added both lobid-organisations (port 7200) and lobid-organisations-staging (port 7201) to `/etc/monit/conf.d/play-instances.rc` and set up the proxy for http://test.lobid.org/organisations. This system can be used to stage and review changes, e.g. for #70.

@dr0i, could you review monit and scripts structure on quaoar1?

**Comment by dr0i** [comment]
* Scripts don't run because of the `web` directory. 
* `monit` doesn't monitor the lobid-organisations , see  `lynx localhost:2812`.  You may have to reload the `monit` configs

**Comment by fsteeg** [comment]
Thanks, fixed the path issue, restarted monit, now seems to be working fine. Closing.

**Comment by philboeselager** [comment]
The path issue still seems to be open on quaoar1?! What was the solution?

**Comment by philboeselager** [comment]
Ah, found the solution: call the restart script with "/web". Closing.
