### ISSUE TITLE
Use ISO 3166-1 Alpha-2 codes for field "addressCountry"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#73]
See https://github.com/hbz/lobid-organisations/issues/48#issuecomment-134863822.

**Comment by acka47** [comment]
This should be in `review` or even `working`, shouldn't it? Can't see the change on test yet, e.g. http://test.lobid.org/organisations/DE-3... Re-assigning @philboeselager

**Comment by fsteeg** [comment]
Deployed to staging. Only works for DBS libraries though.

See:
http://test.lobid.org/organisations/DBS-AH089
http://test.lobid.org/organisations/DE-20

**Comment by acka47** [comment]
Still only works for DBS libraries, see e.g.:

http://test.lobid.org/organisations/DBS-AH089
http://test.lobid.org/organisations/DE-20

Obviously, https://github.com/hbz/lobid-organisations/commit/cb3ed72a1106fc3a2b4d3c6601aba66073617489 hasn't been deployed on staging yet.

**Comment by philboeselager** [comment]
Since our workshop didn't last until eob today, I can deploy that now.

**Comment by acka47** [comment]
This is either not deployed or the data wasn't transformed and re-indexed on staging. Assigning @fsteeg to do this.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/organisations/DBS-AH089
http://test.lobid.org/organisations/DE-20

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://beta.lobid.org/organisations/DBS-AH089
http://beta.lobid.org/organisations/DE-20

**Comment by acka47** [comment]
Reopening as there are again no country codes used in production, aolthough they are on staging. Probably the same underlying problem as for https://github.com/hbz/lobid-organisations/issues/51#issuecomment-187627498

**Comment by fsteeg** [comment]
Fixed deployemnt issue on production (was using wrong index), see:

http://beta.lobid.org/organisations/DBS-AH089
http://beta.lobid.org/organisations/DE-20

**Comment by acka47** [comment]
+1
