### ISSUE TITLE
Mark deprecated ISIL entries with schema:dissolutionDate

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#76]
There are ~650 entries in lobid-organisations that are marked "ungültiger / gelöschter Eintrag" in the ISIL registry. Many (all?) of them have "früher:" in their name, see http://beta.lobid.org/organisations/search?q=name:fr%C3%BCher. 

In the source data, deprecated entries are marked in field `035E` with an `I` := Informationssatz (logisch gelöscht), see the [Feldübersicht](https://wiki.d-nb.de/download/attachments/43090988/normdaten_badr.pdf).

We can't just leave them out because we shouldn't just stop using URIs once minted. But we could mark them as deprecated and show them at the end of result lists. One option would be to indicate the end of existence with http://schema.org/dissolutionDate. For the examples, I looked at, the date of deletion can be found in `050D`, e.g. DE-MUS-798618 (snippet from [SRU XML](http://services.dnb.de/sru/bib?operation=searchRetrieve&query=isl%3DDE-MUS-798618&recordSchema=PicaPlus-xml&version=1.1):

``` xml
<ppxml:tag id="050D" occ="">
  <ppxml:subf id="a">
Löschung2015-03; IFM 28-09-11 Grundlieferung; 20-12-12 Aktualisierung; Löschbestätigung 10-03-15 durch Nolde Stiftung Seebüll
  </ppxml:subf>
</ppxml:tag>
```

**Comment by acka47** [comment]
`schema:dissolutionDate` is suggested to be used on type `Organization`, though. As there are a lot of eBook packages among the deprecated entries (e.g. http://beta.lobid.org/organisations/ZDB-41-UTBV#!) it might not make sense to use it. On the other side, schema.org doesn't use `rdfs:domain` but `schema:domainIncludes` so there is no strong reason to not use the property on other types of entities.

**Comment by acka47** [comment]
> `schema:dissolutionDate` is suggested to be used on type `Organization`, though. As there are a lot of eBook packages among the deprecated entries (e.g. http://beta.lobid.org/organisations/ZDB-41-UTBV#!) it might not make sense to use it

As we removed the eBook packages from lobid-organisations with #207 this makes totally sense now.

**Comment by TobiasNx** [comment]
> See additional info:
> 
> [hbz/lobid-resources#1768 (comment)](https://github.com/hbz/lobid-resources/pull/1768#issuecomment-1557120618)
> 
> http://lobid.org/organisations/DE-Frei161 https://sigel.staatsbibliothek-berlin.de/suche?q=DE-Frei161&sort=sortby%20isl%2Fsort.ascending
> 
> http://lobid.org/organisations/DE-Ob1# https://sigel.staatsbibliothek-berlin.de/suche?q=DE-Ob1&sort=sortby%20isl%2Fsort.ascending

https://github.com/hbz/lobid-organisations/issues/451

Issue became relevant again.

**Comment by TobiasNx** [comment]
@acka47 suggested to add a dissolutionDate 2099-12-31 if no date is provided, so that every record with `035Ea =I` has a dissolutionDate

http://test.lobid.org/organisations/DE-464.json
 ` "dissolutionDate": "2021-12-01",`

Still needs to be added to the context.
