### ISSUE TITLE
Take into account status of DBS entries

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#79]
We will somehow have to take into account the status of the libraries as indicated in the DBS csv file.

In total, there are 16,624 entries/rows. The different status are distributed like this:

- `aktiv`: 9,503
- no status entry: 3,748
- `geschlossen/aufgelöst`: 2,068 
- `keine Beteiligung an DBS`: 678
-  `aufgegangen/übernommen`: 399
- `vorübergeh. geschlossen`: 187 
- `nur Adresse erfasst`: 41

We will have to talk to the DBS colleagues and decide what we will do with entries that have a status other than `aktiv`.

**Comment by acka47** [comment]
Though the numbers above are from an old csv file, the underlying problem is still there. For the time being we will only include entries with stats `1` ("aktiv"). The other might be interesting but it is probably better when we don't include them because:

1. The entries might be quite old having been added during the 1990ies.
2. We can't reproduce when the status of an entry was changed which would be quite important information.

**Comment by philboeselager** [comment]
Currently processing only active Bibs, incl. geodata (see #49 and #50). Will index enriched data when back in the office (Nov. 10th).

**Comment by philboeselager** [comment]
@acka47 see processed data on q.....1, Index: "organisations-20151111-pvb"

**Comment by acka47** [comment]
+1
