### ISSUE TITLE
"email" property named incorrectly "ema" for DBS-derived entries

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#84]
See for example http://beta.lobid.org/organisations/DBS-TH866#! or other [DBS-drived entries](http://beta.lobid.org/organisations/search?q=@id=DBS) with email information.

**Comment by acka47** [comment]
"ema" is the name of the column in the csv we received from DBS...

**Comment by acka47** [comment]
+1 Looks good on test, e.g. http://test.lobid.org/organisations/DBS-TH866#!

**Comment by fsteeg** [comment]
Seems to be deployed, closing. See: http://beta.lobid.org/organisations/DBS-TH866
