### ISSUE TITLE
pretty-print jsonld

### ISSUE THREAD

**Issue by nichtich** [hbz/lobid-organisations#85]
Without pretty-printing the JSON-LD response is unreadable for quick inspecting.

**Comment by fsteeg** [comment]
@nichtich Thanks Jakob, good point.

@acka47 Deployed to staging, see :

`curl http://test.lobid.org/organisations/DE-6`
`curl http://test.lobid.org/organisations/search?q=hbz`

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

`curl http://beta.lobid.org/organisations/DE-6`
`curl http://beta.lobid.org/organisations/search?q=hbz`
