### ISSUE TITLE
Implement integration test for DBS geo enrichment

### ISSUE THREAD

**Issue by philboeselager** [hbz/lobid-organisations#88]
#49 and #50 have been implemented without an integration test. Once, the geodata service runs on a stable server, it would be nice to have an integration test be set up.

**Comment by philboeselager** [comment]
The following branch might be used as a basis for a such integration test, but be aware of that this code was written to query against an inbuilt Elasticsearch Index, which is not an integration scenario. https://github.com/hbz/lobid-organisations/tree/issue/%2350_withTest

**Comment by fsteeg** [comment]
Since the geodata service will remain an internal service only accessible in the hbz network, we won't be able to access it in automated integration tests in Travis builds. Instead, we will check out the service and run it locally as part of the Travis build, see #103. Closing.
