### ISSUE TITLE
DBS-derived organizations without geo coordinates

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#89]
As said in https://github.com/hbz/lobid-organisations/issues/49#issuecomment-156359791, there are a lot DBS-derived entries without geo coordinates. See, e.g. this list: http://beta.lobid.org/organisations/search?q=@id=DBS&size=20&from=250

At öleast for some entries, the reason for the missing geo data is that no street address is provided by DBS. From the csv file, I can see that 124 of the entries.

First of all, I would like to know how many entries in total are lacking geo corrdinates. Can I find this out with elasticsearch, i.e. can I get all entries where a particular field is missing?

**Comment by hauschke** [comment]
I have found 148 institutions without geonames, and subsequently(?) without lat&lon:
https://gist.github.com/hauschke/b4c998dbee1bb0f75947#file-missing_geonames-csv

Related?

**Comment by dr0i** [comment]
Just as a note - in the old lobid-organisations, some of these ISILs _do_ have geo-data,  e.g. [DE-198](http://lobid.org/organisation/DE-198).

**Comment by fsteeg** [comment]
To fix this, we need to

- do a full reindexing to get coordinates for updated entries
- implement automatic geo lookup during updates as in the old lobid-organisations

**Comment by acka47** [comment]
Re. `containedIn`, as asked by @fsteeg on twitter (https://twitter.com/fsteeg/status/677483772451954688). This is added based on the "Regionalschlüssel" (`rs`). See https://github.com/hbz/lobid-organisations/pull/17#issue-49874090 where it reads:

> * Add look-up of geonames in map using 8-digit "Gemeindeschlüssel" ("032P.n" of Sigel and a 8-digit derivation of "gemeindekennzahl" in DBS) for field "containedIn"

**Comment by fsteeg** [comment]
Some confusion here:

- Original issue was about missing geo coordinates for DBS entries, this is a geo lookup issue and remains open
- @hauschke mentioned missing geonames (not geo coordinates). As far as I can tell, only 1/4 of the the orgs even have a geo name in the containedIn field: http://beta.lobid.org/organisations/search?q=containedIn:* vs. http://beta.lobid.org/organisations/search?q=*
- @dr0i mentioned all Sigel-Orgs have geo coordinates in the old API, but this is true for the new one too (at least for the two examples given)

So what I wrote in the comment above about the steps we need to take is nonsense. The original issue remains (geo coordinates for DBS entries), and geonames are what they are and we have no plans to change anything. For Sigel-Orgs everything seems to be fine, thus I'll remove the nwbib-launch label, unassign myself and move to backlog.

@hauschke If there's anything you need, get in contact (perhaps in a new issue).

**Comment by hauschke** [comment]
Example of organisation without lat+long, and without geonamed id: 
http://beta.lobid.org/organisations/DBS-WA339

Should have:
 "containedIn" : "http://www.geonames.org/2875558"

**Comment by acka47** [comment]
> Example of organisation without lat+long, and without geonamed id: 
http://beta.lobid.org/organisations/DBS-WA339

> Should have:
 "containedIn" : "http://www.geonames.org/2875558" 

Generally, only DBS entries contain "Regionalschlüssel" which are then mapped to GeoNames. There can be three reasons why entries don't have a GeoNames link.

1.  Entries solely derived from ISIL registry (i.e. that are not also part of DBS) don't have a link to GeoNames as the "Regionalschlüssel" is missing.
2. For some DBS-derived entries, the base data has a "Regionalschlüssel" in it, it can not be found in the RDF, though, and probably isn't used for matching with Geo Names.
3. Some entries might have a "Regionalschlüssel" and can't be mapped to GeoNames as they key is missing there. (I am not sure that these cases actually exist.)

This is one reason for some DBS ent

**Comment by acka47** [comment]
At least 739 entries don't have `rs` and `containedIn` (link to GeoNames) as they are entries for moved/renamed libraries: http://beta.lobid.org/organisations/search?q=name:fr%C3%BCher 

See also #76.

**Comment by dr0i** [comment]
@hauschke wrote:

> I have found 148 institutions without geonames, and subsequently(?) without lat&lon:

How do you have created that data? Seems that many/all ISILs mentioned there in fact *do* have lat/lon & geonames data.

**Comment by hauschke** [comment]
My mistake. Geonames is missing, lat&long is mostly there. I used https://github.com/hbz/lobid-organisations/issues/55#issuecomment-129771979 to gather the data and extracted lat&long from geoname.rdf.

**Comment by fsteeg** [comment]
So #92 and #93 look good, we have a new issue #90.

I think we can close this. Assiging to @acka47 for review.

**Comment by acka47** [comment]
looking again at http://beta.lobid.org/organisations/search?q=@id=DBS&size=20&from=250 I notice that a lot of these organizations don't have a street address which probably is the reason for them not having any geo coordinates. I checked the DBS organisations list and found out that 124 of them don't have a street address.

**Comment by acka47** [comment]
Checking DBS entries as we did for ISIL entries in https://github.com/hbz/lobid-organisations/issues/93#issuecomment-171934304:

1. get total of entries with `dbsID`: https://beta.lobid.org/organisations/search?q=dbsID:* =>​  12.299
2. get total of entries with `dbsID` and geo data : "https://beta.lobid.org/organisations/search?q=dbsID:*%20AND%20location.geo:* => ​9.714
3. DBS-derived entires that are not expected to have geo data (because of missing street address: => 124

=> 2461 (still ~20 %)  DBS-derived entries without geo data

**Comment by acka47** [comment]
up tod ate numbers:

- entries with dbsID and no geo coordinates: https://beta.lobid.org/organisations/search?q=dbsID:*+AND+_missing_:location.geo -> 3706
- DBS-derived entires that are not expected to have geo data (because of missing street address: => 124

That's way to much entries without coordinates. Adding "org-launch" label.

**Comment by fsteeg** [comment]
Continuing from https://github.com/hbz/lobid-organisations/issues/251#issuecomment-243378930.

We have 4379 addresses with a non-OK geodata result in the lobid-organisations staging transformation.

**Comment by fsteeg** [comment]
@acka47 suggested using Pelias [1] via the Mapzen search API [2] yesterday.

I've replaced our geo lookup with Mapzen API calls, and results look good: we get locations for almost all DBS organisations. These won't be all correct, but that was not guaranteed with the previous lookup either. Current version deployed to staging:

https://test.lobid.org/organisations/search?q=dbsID:*+AND+_missing_:location.geo

API terms [3] are very usable: 6 requests per second, 30000 per day. We have 9391 DBS organisations, so we can easily do full transformations including lookups. I'm caching the results, and we only transform updates daily, so actual numbers will be way less.

[1] https://github.com/pelias/pelias
[2] https://mapzen.com/documentation/search/search/
[3] https://mapzen.com/documentation/search/api-keys-rate-limits/

**Comment by acka47** [comment]
\o/ +1

**Comment by acka47** [comment]
For checking accuracy of OSM lookups, we can at some point automatically compare geo coordinates with regionalschlüssel. E.g. I can easily see querying for libraries in NRW via field `rs` that at least the two lookups went wrong: http://beta.lobid.org/organisations/search?q=rs:05*

**Comment by acka47** [comment]
Here are some checks based on rs that currently don't look that good:

- Schleswig-Holstein: http://staging.lobid.org/organisations/search?q=rs%3A01*
- Niedersachsen: http://staging.lobid.org/organisations/search?q=rs%3A03*
- Hessen: http://staging.lobid.org/organisations/search?q=rs%3A06*
- Rheinland-Pfalz: http://staging.lobid.org/organisations/search?q=rs%3A07*
ä- Baden-Württemberg: http://staging.lobid.org/organisations/search?q=rs%3A08*

**Comment by fsteeg** [comment]
Deployed a new version to staging where these queries look better. The confidence treshold used is too high though, resulting in missing location data for 3056 organisations. Plus, due to a bug, these organisations are skipped entirely. Will continue by fixing the bug and lowering the treshold.

**Comment by fsteeg** [comment]
Processed with treshold of `0.7`, yields similar values to current beta, slight improvement:

http://test.lobid.org/organisations/search?q=dbsID:*+AND+_missing_:location.geo
http://beta.lobid.org/organisations/search?q=dbsID:*+AND+_missing_:location.geo

I think we should move the treshold down a little further and check the results again.

**Comment by acka47** [comment]
Yes, the results look very good. We might even test a lower threshold.

**Comment by fsteeg** [comment]
Reprocessed with slightly lower treshold (`0.675`) and additional rule: if (street AND (postal code OR city)) match, use the result, no matter what the confidence is (I saw cases with missing postal codes in Mapzen but complete street and city match resulting in 0.5 confidence).

Results in 1218 missing locations (1921 in beta):

http://test.lobid.org/organisations/search?q=dbsID:*+AND+_missing_:location.geo

False positives look good too:

http://test.lobid.org/organisations/search?q=rs:01*
http://test.lobid.org/organisations/search?q=rs:03*
http://test.lobid.org/organisations/search?q=rs:05*
http://test.lobid.org/organisations/search?q=rs:06*
http://test.lobid.org/organisations/search?q=rs:07*
http://test.lobid.org/organisations/search?q=rs:08*

**Comment by fsteeg** [comment]
Log output for the 1218 missing locations: [missing-geo.txt](https://github.com/hbz/lobid-organisations/files/451899/missing-geo.txt)

**Comment by acka47** [comment]
+1
