### ISSUE TITLE
DBS-derived entries missing "Regionalschlüssel"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#90]
From https://github.com/hbz/lobid-organisations/issues/89#issuecomment-165464188:

> For some DBS-derived entries, the base data has a "Regionalschlüssel" in it, it can not be found in the RDF, though, and probably isn't used for matching with Geo Names.

- We have 12.304 entries with DBS ID, see http://beta.lobid.org/organisations/search?q=dbsID:*.
- We only have 4828 with DBS ID and `rs`: http://beta.lobid.org/organisations/search?q=dbsID:*%20AND%20rs:*
- We have 6649 entries over all with `rs`: http://beta.lobid.org/organisations/search?q=rs:*
- Most of the entries (6621) with `rs` also have `containedIn`: http://beta.lobid.org/organisations/search?q=containedIn:*%20AND%20rs:*
- 6986 entries have `ags`: http://beta.lobid.org/organisations/search?q=ags:*
- 6682 entries with `ags` have `containedIn` link: http://beta.lobid.org/organisations/search?q=containedIn:*%20AND%20ags:*

This is all quite strange. I will investigate this sometimes in 2016...

**Comment by acka47** [comment]
I took a look at the source DBS csv file. Actually, nearly every entry has a regionalschlüssel in it. I wanted to present some functions using the "rs" or "ags" field in our webcast tomorrow but won't do it as the necessary data isn't there...

**Comment by acka47** [comment]
I think, I found the problem. Actually, the Regionalschlüssel from DBS isn't taken into account at all. In the morph the field where the key comes from is name "gemeindekennzahl", see https://github.com/hbz/lobid-organisations/blob/706adc1f0ef4d29584d7c1d956c0501f4d6a5bd8/src/main/resources/morph-enriched.xml#L21-L24. In the csv file that is transformed the relevant field is named "stk_2007".

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/organisations/search?q=dbsID:*+AND+rs:*

I also changed what I believe was a bug in the previous version: if the DBS `stk_2007` is 11 digits, a `0` is prependend (this wasn't actually working before). If it's 12 digits, it's used as it is. Does that make sense?

**Comment by acka47** [comment]
> I also changed what I believe was a bug in the previous version: if the DBS `stk_2007` is 11 digits, a `0` is prependend (this wasn't actually working before).

Hmm, @SBRitter and me did some work on the "rs" (Regionalschlüssel). In fact, it really has to have 12 digits, see https://de.wikipedia.org/wiki/Amtlicher_Gemeindeschl%C3%BCssel#Regionalschl.C3.BCssel. For today, I can not dig deeper into this.

Didn't find an error in th examples I looked at, so: +1

**Comment by fsteeg** [comment]
Yes, it looked like it was meant to be implemented that way, but due to an ordering bug it was not actually working (`0` was prepended to 12 digit values, last digit was cut off).
