### ISSUE TITLE
Enable automated updates for current code and data

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#91]
Currently automated setup (in hduser's crontab on weywot1) uses old code and writes to unused index.

We need to:

- [x] Set up geodata service, which is used in the current code~~, under lobid.org/geodata~~ (no public service)
- [x] Update the lobid-organisations version used by crontab (currently on weywot2)
- [x] Update index names/aliases to make sure lobid-organisations/web on quaoar1 uses the data produced by the crontab'ed code

Tagging nwbib-launch since the beta lobid-organisations is used in nwbib, requiring up-to-date data.

**Comment by dr0i** [comment]
Ah - this may be the cause, among others, for #92 and #93.

**Comment by fsteeg** [comment]
Implemented and set up for staging:

- Latest version of geodata enrichment code is in master: ~~https://github.com/hbz/lobid-organisations/pull/96~~
- Geodata service is running internally at http://gaia.hbz-nrw.de:7400 (should move to quaoar1, see https://github.com/hbz/geodata/issues/23)
- Updated and tested the lobid-organisations version (currently on weywot2) used by crontab (on weywot1) (should move to quaoar1, see https://github.com/hbz/lobid-organisations/issues/101)
- Indexing on weywot2 is configured to index into quaoar1, which is used by both http://beta.lobid.org/organisations (index: organisations) and http://test.lobid.org/organisations (index: organisations-staging)

Crontabbed version is set up to index into organisations-staging. Will set up for production on Monday.

**Comment by fsteeg** [comment]
Automated updates are set up to write to 'organisations' (production) index, closing.
