### ISSUE TITLE
Missing new ISILs

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-organisations#92]
Tracing #89 I found that In the old service http://lobid.org/organisation/GB-UkLeUBL exists  (it was updated/created yesterday) while in the new one  https://beta.lobid.org/organisations/GB-UkLeUBL it doesn't.

**Comment by acka47** [comment]
This is due to the fact that we pulled in the MARC organization codes into the old service at some point. It could be fixed with #5.

I doubt that it is true that "it was updated/created yesterday".

In https://github.com/lobid/lodmill/issues/118#issuecomment-28786396 you wrote:

> all records not comig from ZDB Siil file are no more transformed, and thus residing in an old state

**Comment by dr0i** [comment]
> This is due to the fact that we pulled in the MARC organization codes into the old service at some point. It could be fixed with #5.

 It's not coming from MARC. Follow the link to the source, the zdb isil service http://sigel.staatsbibliothek-berlin.de/suche/?isil=GB-UkLeUBL

> I doubt that it is true that "it was updated/created yesterday".

that, you shouldn't. You know not the files and logs I know of ;)

**Comment by acka47** [comment]
Ok, my test obviously wasn't the right one (and it even took more time). I looked at the LoC dump at http://id.loc.gov/download/ and saw that UkLeUBL (also) is part of the MARC organization codes...

**Comment by fsteeg** [comment]
Seems to be caused by the missing updates (#91).

Deployed to staging: https://test.lobid.org/organisations/GB-UkLeUBL

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: https://beta.lobid.org/organisations/GB-UkLeUBL

See also https://github.com/hbz/lobid-organisations/issues/91 for automatic update setup.
