### ISSUE TITLE
ISIL organizations without geo coordinates

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-organisations#93]
This one is derived from #89 where the topic is missing geo data in DBS entries.

Missing geo data in new service, e.g.:
http://beta.lobid.org/organisations/DE-Mb109, http://beta.lobid.org/organisations/DE-Wol4

Same data existing in old service:
http://lobid.org/organisation/DE-Mb109, http://lobid.org/organisation/DE-Wol4

@fsteeg Is there a way to get all entries of the new service lacking geo data ? Maybe grep the raw data records?

**Comment by dr0i** [comment]
Are these correct queries to calculate how many entries are lacking geo data?

1. get total of isils: "beta.lobid.org/organisations/search?q=isil:*" =>​ 15.975
2. get total of isils with geo data : "beta.lobid.org/organisations/search?q=isil:* AND location.geo:*" => ​12.753
3. get total of isils that are not expected to have geo data: "http://beta.lobid.org/organisations/search?q=name:fr%C3%BCher%20AND%20isil:*" => ​739

=> 2483 (~15 %)  ISILs without geo data

**Comment by fsteeg** [comment]
Looks good in current setup with automated updates. See:

http://beta.lobid.org/organisations/DE-Mb109
http://beta.lobid.org/organisations/DE-Wol4

**Comment by acka47** [comment]
Following @dr0i's steps from https://github.com/hbz/lobid-organisations/issues/93#issuecomment-165712167, it doesn't look that good:

1. get total of isils: https://beta.lobid.org/organisations/search?q=isil:* =>​  16.021
2. get total of isils with geo data : "https://beta.lobid.org/organisations/search?q=isil:*%20AND%20location.geo:* => ​12.850
3. get total of isils that are not expected to have geo data: http://beta.lobid.org/organisations/search?q=name:fr%C3%BCher%20AND%20isil:* => ​746

=> 2425 (still ~15 %)  ISILs without geo data

Or is something wrong with this method?

**Comment by acka47** [comment]
Checking the whole data with the same method:

- total entries: https://beta.lobid.org/organisations/search?q=* => 23.253
- entries with geo data: https://beta.lobid.org/organisations/search?q=*%20AND%20location.geo:* 18.146
- entries not expected to have geo data: http://beta.lobid.org/organisations/search?q=name:fr%C3%BCher => 746

Entries missing geo data: 4361 (~ 19%)

**Comment by fsteeg** [comment]
So the reasoning is that all entries both from DBS and Sigel should have geo data, unless their name contains "früher". Is this correct?

**Comment by acka47** [comment]
> So the reasoning is that all entries both from DBS and Sigel should have geo data, unless their name contains "früher". Is this correct?

Yes, this is correct. The ones with "früher" don't contain enough information for geocoding, see e.g. http://beta.lobid.org/organisations/DE-MUS-798618#!.

**Comment by fsteeg** [comment]
One of the samples from the original issue description that was OK a few days ago is now missing again, and your sample from above that should have no geo data now actually does. See also #97.

**Comment by acka47** [comment]
> and your sample from above that should have no geo data now actually does

This is quite strange as the source data doesn't contain any address information. Compare http://services.dnb.de/sru/bib?operation=searchRetrieve&query=isl%3DDE-MUS-798618&recordSchema=PicaPlus-xml&version=1.1 (which is what we get as input as far as I know) and http://beta.lobid.org/organisations/DE-MUS-798618#

**Comment by fsteeg** [comment]
Yes, weird. The address seems to be correct, though.

Another thing, about the queries from https://github.com/hbz/lobid-organisations/issues/93#issuecomment-171935301: I've added some logging while running the transformation and can see that many addresses simply get no result from our geodata service.

The service is still quite in flux, and we have a few open issues (https://github.com/hbz/geodata/issues), which require updates in the transformation, so I don't think we'll be able to fix this for `nwbib-launch`. I also don't think it's critical. At worst, there will be some pins missing in the holdings map.

I suggest we remove `nwbib-launch`, and move this and #97 to the backlog.

**Comment by acka47** [comment]
> I suggest we remove `nwbib-launch`, and move this and #97 to the backlog.

 +1. Will do so.

**Comment by acka47** [comment]
Up to date numbers in two queries.

- Number of entries with ISIL, and no geo coordinates: 
https://beta.lobid.org/organisations/search?q=isil:*+AND+_missing_:location.geo -> 940
=isil:*+AND+missing_:
- total of isils that are not expected to have geo data: http://beta.lobid.org/organisations/search?q=name:fr%C3%BCher%20AND%20isil:* => ​861

That's geo coordinates for 79 entries missing. This already looks quite to me. But work on the geodata service might even bring better results...

**Comment by acka47** [comment]
As this already looks quite good I am not putting the "org-launch" label on this issue.

**Comment by acka47** [comment]
@fsteeg told to me offline that we actually don't have a lookup for ISIL entries implemented. Nearly all entries have geo coordinates because they have been added to the source data (the ISIL registry). See http://sigel.staatsbibliothek-berlin.de/de/aktuelles/einzelansicht/article/2016-06-03-2436/. Thus, we obviously don't need to implement a lookup. Closing.
