### ISSUE TITLE
DE-180 not found when searching for "Universitätsbibliothek Mannheim"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#98]
Take a look at http://beta.lobid.org/organisations/search?q=Universit%C3%A4tsbibliothek%20Mannheim. 
http://beta.lobid.org/organisations/DE-180 isn't part of the list, though its name is "Universitätsbibliothek Mannheim". Actually, it should be the first result in the list.

Probably something wrong with the encoding.

**Comment by fsteeg** [comment]
Seems to be fixed due to some subsequent changes, see third result for:

http://beta.lobid.org/organisations/search?q=Universitätsbibliothek+Mannheim
